"""Auto-generated debug runner — only ``_inline_inputs`` and ``_user_compare`` are editable.

Re-execute the kernel in the parent build_output directory:

    python {this_file}

When a sibling ``golden.py`` exists, inputs are loaded via
``golden.generate_inputs`` and the run is validated against
``compute_golden``. Otherwise (JIT path) the inputs declared inline in
``_inline_inputs`` are used, and ``_user_compare`` is invoked after
replay so you can write your own assertions.

------------------------------------------------------------------------
CLI flags (forwarded to ``pypto.runtime.debug.replay._main``)
------------------------------------------------------------------------
  --platform PLAT          target platform (default: a2a3)
  --device-id N            hardware device index (default: 0)
  --pmu LEVEL              enable PMU profiling at LEVEL
  --swimlane               enable L2 swimlane capture
  --dump-tensor [LEVEL]    dump per-task tensors to disk (bare=1 partial, 2 full)
  --dep-gen                enable dep_gen profiling
  --no-recompile           reuse cached .so/.bin (ignores cpp edits)
  --no-rebuild-from-pto    skip ptoas/*.pto -> kernels/*.cpp rebuild
  --log-level LEVEL        runtime log level: debug/v0..v9/info/warn/error/null
  --log-sync-pypto         also push --log-level to PyPTO's C++ logger
  --validate               compare outputs vs. golden.py (auto-on if golden.py exists)
  --no-validate            skip golden validation; runs ``_user_compare`` instead

Examples:
  python {this_file} --pmu 2 --swimlane              # DFX-on run
  python {this_file} --log-level debug               # verbose runtime trace
  python {this_file} --no-validate                   # skip golden, run _user_compare
  python {this_file} --no-recompile --no-rebuild-from-pto   # fast re-run, no rebuild

Run ``python {this_file} --help`` for the authoritative list — flags are
defined in :func:`pypto.runtime.debug.replay._main`, not here, so the
``--help`` text is always in sync.

Generated by pypto.runtime.debug.run_script_writer.
"""

import sys
from pathlib import Path

import torch

from pypto.runtime.debug.replay import _main

_WORK_DIR = Path(__file__).resolve().parent.parent


def _inline_inputs():
    """Materialise inputs from shape / dtype info embedded at compile time."""
    hidden_states = torch.randn((16, 5120), dtype=torch.bfloat16)
    input_rms_weight = torch.randn((1, 5120), dtype=torch.float32)
    wq = torch.randn((5120, 5120), dtype=torch.bfloat16)
    wk = torch.randn((5120, 1024), dtype=torch.bfloat16)
    wv = torch.randn((5120, 1024), dtype=torch.bfloat16)
    q_norm_weight = torch.randn((1, 128), dtype=torch.float32)
    k_norm_weight = torch.randn((1, 128), dtype=torch.float32)
    seq_lens = torch.randint(0, 8, (16,), dtype=torch.int32)
    block_table = torch.randint(0, 8, (512,), dtype=torch.int32)
    slot_mapping = torch.randint(0, 8, (16,), dtype=torch.int32)
    rope_cos = torch.randn((4096, 128), dtype=torch.float32)
    rope_sin = torch.randn((4096, 128), dtype=torch.float32)
    k_cache = torch.randn((524288, 128), dtype=torch.bfloat16)
    v_cache = torch.randn((524288, 128), dtype=torch.bfloat16)
    wo = torch.randn((5120, 5120), dtype=torch.bfloat16)
    w_gate = torch.randn((5120, 17408), dtype=torch.bfloat16)
    w_up = torch.randn((5120, 17408), dtype=torch.bfloat16)
    w_down = torch.randn((17408, 5120), dtype=torch.bfloat16)
    post_rms_weight = torch.randn((1, 5120), dtype=torch.float32)
    out = torch.zeros((16, 5120), dtype=torch.bfloat16)
    return [hidden_states, input_rms_weight, wq, wk, wv, q_norm_weight, k_norm_weight, seq_lens, block_table, slot_mapping, rope_cos, rope_sin, k_cache, v_cache, wo, w_gate, w_up, w_down, post_rms_weight, out]


def _user_compare(hidden_states, input_rms_weight, wq, wk, wv, q_norm_weight, k_norm_weight, seq_lens, block_table, slot_mapping, rope_cos, rope_sin, k_cache, v_cache, wo, w_gate, w_up, w_down, post_rms_weight, out):
    """Hand-written comparison for the JIT path (no ``golden.py``).

    Invoked from ``_main`` after ``replay`` finishes when golden validation
    did NOT run. Output tensors have been populated in-place by the kernel.
    Edit the body to add your own assertions, for example::

        expected = a + b
        assert torch.allclose(c, expected, rtol=1e-5, atol=1e-5), (
            f"max diff = {(c - expected).abs().max().item()}"
        )
    """
    return  # TODO: add your comparison here


if __name__ == "__main__":
    sys.exit(_main(
        [str(_WORK_DIR), *sys.argv[1:]],
        inline_inputs=_inline_inputs,
        user_compare=_user_compare,
        default_platform="a2a3",
    ))
