# Copyright (c) PyPTO Contributors.
# This program is free software, you can redistribute it and/or modify it under the terms and conditions of
# CANN Open Software License Agreement Version 2.0 (the "License").
# Please refer to the License for details. You may not use this file except in compliance with the License.
# THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
# INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
# See LICENSE in the root of the software repository for the full text of the License.
# -----------------------------------------------------------------------------------------------------------

repos:

    # Common
    - repo: local
      hooks:
        - id: check-headers
          name: check-headers
          entry: python tests/lint/check_headers.py
          language: python
          language_version: python3
          pass_filenames: false

        - id: check-english-only
          name: check-english-only
          entry: python tests/lint/check_english_only.py
          language: python
          language_version: python3
          pass_filenames: false
          exclude: ^(3rdparty/|docs/zh-cn/|README\.zh-CN\.md)

    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.6.0
      hooks:
        - id: check-added-large-files
          exclude: ^docs/images/
        - id: check-yaml
        - id: end-of-file-fixer
        - id: trailing-whitespace

    # C++ linting
    - repo: https://github.com/pre-commit/mirrors-clang-format
      rev: v21.1.0
      hooks:
        - id: clang-format
          types_or: [c++, c]
          exclude: ^3rdparty/

    - repo: https://github.com/cpplint/cpplint
      rev:  2.0.0
      hooks:
        - id: cpplint
          exclude: ^3rdparty/
          args:
            - --root=include
            - --linelength=110
            - --filter=-whitespace/parens,-whitespace/indent_namespace,-runtime/references

    # Markdown linting
    - repo: https://github.com/DavidAnson/markdownlint-cli2
      rev: v0.20.0
      hooks:
        - id: markdownlint-cli2
          args:
            - --fix
            - --config
            - tests/lint/.markdownlint.yaml

    # Python linting
    - repo: https://github.com/astral-sh/ruff-pre-commit
      rev: v0.14.8
      hooks:
        - id: ruff-check
          types_or: [python, pyi]
          args: [--fix]
          exclude: ^tests/ut/codegen/test_orchestration_codegen\.py$
        - id: ruff-format
          types_or: [python, pyi]

    - repo: https://github.com/RobertCraigie/pyright-python
      rev: v1.1.407
      hooks:
      - id: pyright
        additional_dependencies: [pytest==7.0.0, torch==2.8.0, numpy==2.0.0]
