import { useMemo, useState } from "react";

const run = { id: "_jit_l3_decode_csa_20260903_010617", program: "decode_csa_test", platform: "a2a3 · 2 ranks · device 0", tasks: 86, edges: 338, passSnapshots: 52, hints: 230 };
const rankData = {
  0: { span: "4.88 ms", trace: "merged_swimlane_20260903_010746.json", top: "qk_pv_aiv_spmd", slots: [["qk_pv_aiv_spmd", "AIV", "48 blocks", "658.88 µs", "881.22 µs", 92], ["csa_merge_pack_publish_spmd", "AIV", "48 blocks", "387.44 µs", "660.42 µs", 71], ["qk_pv_aic_spmd", "AIC", "24 blocks", "626.49 µs", "830.26 µs", 67], ["indexer_topk_group_wave_spmd", "AIV", "48 blocks", "112.91 µs", "132.74 µs", 33]] },
  1: { span: "3.77 ms", trace: "merged_swimlane_20260903_010747.json", top: "qk_pv_aiv_spmd", slots: [["qk_pv_aiv_spmd", "AIV", "48 blocks", "668.31 µs", "948.46 µs", 96], ["csa_merge_pack_publish_spmd", "AIV", "48 blocks", "441.98 µs", "756.12 µs", 76], ["qk_pv_aic_spmd", "AIC", "24 blocks", "632.90 µs", "896.00 µs", 69], ["indexer_topk_group_wave_spmd", "AIV", "48 blocks", "112.60 µs", "130.58 µs", 31]] },
};
const candidates = [
  { id: "pipeline", area: "decode_csa.py:397", title: "先释放 Vec 共存压力，再验证 stage=2", evidence: "PH-MR-001：每 stage 32 KB；当前仅 1/2 buffer 可用，软件流水被序列化。", impact: "核内流水 · 高置信证据" },
  { id: "tile", area: "decode_csa.py:245–264", title: "收敛 CSA Vec 传输的末维粒度", evidence: "多处 64B / 256B load-store 低于 a2a3 的 512B cache-line 建议。", impact: "MTE 效率 · 需保留数值语义" },
  { id: "rank", area: "rank0 ↔ rank1", title: "先验证 CSA merge 的 rank 尾部差异", evidence: "rank0 / rank1 的执行窗口分别为 4.88 / 3.77 ms；不能把跨 rank 尾部直接归因为单核。", impact: "L3 调度 · 需要 paired replay" },
];
const sourceGroups = [["qkv_proj_rope.py", 62], ["hc_pre.py", 41], ["decode_indexer.py", 29], ["decode_compressor_ratio4.py", 23], ["decode_indexer_compressor.py", 22], ["decode_csa.py", 17], ["decode_o_proj.py", 13], ["decode_sparse_attn_csa.py", 10]];
const navItems = [["overview", "运行概览", "Run summary"], ["critical", "关键路径", "Critical path"], ["kernels", "Kernel 分析", "Core & task evidence"], ["queue", "调优队列", "Evidence-backed changes"], ["compiler", "编译证据", "Passes & diagnostics"]];

function Metric({ label, value, tone = "" }) { return <article className={`metric ${tone}`}><span>{label}</span><strong>{value}</strong></article>; }
function HotspotTable({ rank, selected, onSelect, filter = "" }) { const query = filter.toLowerCase(); return <div className="hotspot-table"><div className="table-head"><span>Kernel / task</span><span>Core</span><span>Blocks</span><span>Avg</span><span>Max</span><span>占用</span></div>{rankData[rank].slots.filter(([name]) => !query || name.toLowerCase().includes(query)).map(([name, core, blocks, avg, max, load]) => <button key={name} className={`hotspot-row ${selected === name ? "selected" : ""}`} onClick={() => onSelect(name)}><span><b>{name}</b><small>{name === "qk_pv_aiv_spmd" ? "Task r2t53 · attention core" : "runtime callable"}</small></span><span className={`core ${core.toLowerCase()}`}>{core}</span><span>{blocks}</span><span>{avg}</span><span>{max}</span><span className="load"><i style={{ width: `${load}%` }} /></span></button>)}</div>; }

export function App() {
  const [active, setActive] = useState("overview");
  const [rank, setRank] = useState(0);
  const [selectedKernel, setSelectedKernel] = useState("qk_pv_aiv_spmd");
  const [candidate, setCandidate] = useState("pipeline");
  const [experiment, setExperiment] = useState(false);
  const [filter, setFilter] = useState("");
  const selected = useMemo(() => rankData[rank].slots.find(row => row[0] === selectedKernel) ?? rankData[rank].slots[0], [rank, selectedKernel]);
  const currentCandidate = candidates.find(item => item.id === candidate);
  const setRankAndKeepSelection = (nextRank) => { setRank(nextRank); if (!rankData[nextRank].slots.some(row => row[0] === selectedKernel)) setSelectedKernel(rankData[nextRank].top); };

  return <div className="shell">
    <header className="topbar"><div className="brand"><span className="brand-mark">P</span><span>PyPTO <b>Performance Control</b></span></div><div className="run-crumb"><span>Runs</span><i>/</i><strong>{run.id}</strong></div><div className="top-status"><span className="live-dot" />Artifacts indexed <button className="quiet">Export case</button></div></header>
    <aside className="sidebar"><div className="run-card"><span className="eyebrow">ACTIVE RUN</span><strong>{run.program}</strong><small>{run.platform}</small><div><span>real device trace</span><b>complete</b></div></div><nav><span className="nav-label">WORKSPACE</span>{navItems.map(([id, title, sub]) => <button key={id} className={`nav-item ${active === id ? "active" : ""}`} onClick={() => setActive(id)}><span className="nav-index">0{navItems.findIndex(item => item[0] === id) + 1}</span><span><b>{title}</b><small>{sub}</small></span></button>)}</nav><div className="side-foot"><span>BASELINE LOCKED</span><b>trace + deps + passes</b></div></aside>
    <main className="main">
      <section className="page-head"><div><span className="eyebrow cyan">PERFORMANCE RUN</span><h1>{active === "overview" ? "从真实执行开始收敛调优面" : navItems.find(item => item[0] === active)?.[1]}</h1><p>所有结论都绑定当前 run 的 swimlane、依赖图、pass 快照和编译诊断；候选改动不会伪造性能收益。</p></div><div className="rank-switch"><button className={rank === 0 ? "active" : ""} onClick={() => setRankAndKeepSelection(0)}>rank 0</button><button className={rank === 1 ? "active" : ""} onClick={() => setRankAndKeepSelection(1)}>rank 1</button></div></section>
      {active === "overview" && <><section className="metrics"><Metric label="rank 0 execution window" value="4.88 ms" tone="warn" /><Metric label="rank 1 execution window" value="3.77 ms" /><Metric label="cross-rank window skew" value="+29.3%" tone="warn" /><Metric label="runtime graph" value="86 tasks · 338 edges" /><Metric label="compiler diagnostics" value="230 hints" tone="warn" /></section><section className="layout two-one"><article className="panel path-panel"><div className="panel-head"><div><span className="eyebrow">CURRENT BOTTLENECK SURFACE</span><h2>CSA attention 的 AIV/AIC 配对任务</h2></div><button className="text-button" onClick={() => setActive("critical")}>查看关键路径 →</button></div><div className="path-stage"><span className="stage-tag">01</span><div><b>qk_pv_aiv_spmd</b><small>48 block events · rank {rank} avg {rankData[rank].slots[0][3]} · max {rankData[rank].slots[0][4]}</small></div><em>Vec / AIV</em></div><div className="path-link" /><div className="path-stage"><span className="stage-tag">02</span><div><b>csa_merge_pack_publish_spmd</b><small>48 block events · rank {rank} avg {rankData[rank].slots[1][3]} · merge / publish tail</small></div><em>Vec / AIV</em></div><div className="path-link" /><div className="path-stage muted-stage"><span className="stage-tag">03</span><div><b>qk_pv_aic_spmd</b><small>24 block events · rank {rank} avg {rankData[rank].slots[2][3]}</small></div><em>Cube / AIC</em></div><p className="note">这是按每 rank 的 worker trace 聚合出的热点面，不是跨 rank 对齐后的端到端 critical path。先固定 paired replay，再决定是否动核。</p></article><article className="panel evidence-panel"><span className="eyebrow">EVIDENCE HEALTH</span><h2>可复验，而非猜测</h2><dl><dt>Swimlane</dt><dd>{rankData[rank].trace}</dd><dt>Dependencies</dt><dd>deps.json · {run.edges} edges</dd><dt>Compiler</dt><dd>passes_dump · {run.passSnapshots} snapshots</dd><dt>Diagnostics</dt><dd>perf_hints.log · {run.hints} entries</dd></dl><button className="outline" onClick={() => setActive("compiler")}>打开证据索引</button></article></section><section className="panel hotspot-panel"><div className="panel-head"><div><span className="eyebrow">HOTSPOT INVENTORY · RANK {rank}</span><h2>按累积 core time 排序</h2></div><span className="badge cyan">4081 worker events / 129 callables</span></div><HotspotTable rank={rank} selected={selectedKernel} onSelect={setSelectedKernel} /></section></>}
      {active === "critical" && <section className="layout critical-layout"><article className="panel trace-panel"><div className="panel-head"><div><span className="eyebrow">WORKER VIEW · RANK {rank}</span><h2>任务窗口与 core 分布</h2></div><span className="trace-window">0 — {rankData[rank].span}</span></div><div className="trace-scale"><span>0</span><span>1 ms</span><span>2 ms</span><span>3 ms</span><span>4 ms</span></div>{["AIV 00–23", "AIC 00–11", "AIV 24–47", "AICPU scheduler"].map((name, index) => <button key={name} className={`trace-lane ${index < 2 ? "focus" : ""}`} onClick={() => setSelectedKernel(index === 1 ? "qk_pv_aic_spmd" : "qk_pv_aiv_spmd")}><span>{name}</span><div className="track"><i className={index === 1 ? "cube" : index === 3 ? "cpu" : "vec"} style={{ left: `${[4, 20, 13, 9][index]}%`, width: `${[74, 63, 54, 78][index]}%` }} /><i className="dim" style={{ left: `${[80, 70, 70, 62][index]}%`, width: "12%" }} /></div></button>)}<div className="trace-callout"><b>当前选择：{selected[0]}</b><span>追踪后续 task、输入 tensor 与可调参数前，先判定它是否位于被测窗口的尾部。</span></div></article><aside className="panel inspector"><span className="eyebrow">SELECTED CALLABLE</span><h2>{selected[0]}</h2><div className="big-number">{selected[4]}<small>max block duration</small></div><dl><dt>Core</dt><dd>{selected[1]}</dd><dt>Active blocks</dt><dd>{selected[2]}</dd><dt>Mean per block</dt><dd>{selected[3]}</dd><dt>Source signal</dt><dd>merged swimlane</dd><dt>Next evidence</dt><dd>memory + pipeline group</dd></dl><button className="primary" onClick={() => { setCandidate(selected[0].includes("qk_pv") ? "pipeline" : "rank"); setActive("queue"); }}>形成可验证候选 →</button></aside></section>}
      {active === "kernels" && <section className="layout kernel-layout"><article className="panel hotspot-panel"><div className="panel-head"><div><span className="eyebrow">KERNEL PROFILER</span><h2>调用级瓶颈，不把总时长误读为单 block</h2></div><input value={filter} onChange={event => setFilter(event.target.value)} placeholder="过滤 callable" /></div><HotspotTable rank={rank} selected={selectedKernel} onSelect={setSelectedKernel} filter={filter} /><div className="split-bar"><span>AIV aggregate</span><i><b style={{ width: "69%" }} /></i><em>qk_pv + merge publish</em></div><div className="split-bar"><span>AIC aggregate</span><i><b className="cube-fill" style={{ width: "47%" }} /></i><em>qk_pv accumulation</em></div></article><aside className="panel hint-summary"><span className="eyebrow">HINT COVERAGE</span><h2>源文件诊断分布</h2>{sourceGroups.filter(([file]) => file.toLowerCase().includes(filter.toLowerCase()) || !filter).map(([file, count]) => <button key={file} onClick={() => setCandidate(file === "decode_csa.py" ? "pipeline" : "tile")}><span>{file}</span><b>{count}</b><i style={{ width: `${count / 62 * 100}%` }} /></button>)}<p>230 条提示主要是 PH001；它们是候选入口，不等于每条都值得改。</p></aside></section>}
      {active === "queue" && <section className="layout queue-layout"><article className="panel candidate-list"><div className="panel-head"><div><span className="eyebrow">TUNING QUEUE</span><h2>先选择要验证的因果假设</h2></div><span className="badge">{experiment ? "1 experiment staged" : "no experiment staged"}</span></div>{candidates.map(item => <button key={item.id} className={`candidate ${candidate === item.id ? "selected" : ""}`} onClick={() => setCandidate(item.id)}><span className="candidate-id">0{candidates.indexOf(item) + 1}</span><div><small>{item.area}</small><b>{item.title}</b><p>{item.evidence}</p></div><em>{item.impact}</em></button>)}</article><aside className="panel candidate-detail"><span className="eyebrow cyan">VALIDATION SPEC</span><h2>{currentCandidate.title}</h2><p className="detail-evidence">{currentCandidate.evidence}</p><div className="spec"><span>Baseline</span><b>{run.id}</b><span>Target rank</span><b>rank {rank}</b><span>Measurement</span><b>paired trace + same inputs</b><span>Correctness</span><b>required before timing</b><span>Decision rule</span><b>repeated gain above noise</b></div><button className={experiment ? "primary success" : "primary"} onClick={() => setExperiment(true)}>{experiment ? "Experiment staged · immutable baseline" : "创建验证实验"}</button><button className="outline" onClick={() => setExperiment(false)}>清除草稿</button><p className="footnote">Demo 只创建实验规格，不执行上板，也不会展示未经测量的 speedup。</p></aside></section>}
      {active === "compiler" && <section className="layout compiler-layout"><article className="panel pass-panel"><div className="panel-head"><div><span className="eyebrow">COMPILER EVIDENCE</span><h2>从 source 意图到 runtime 可见信号</h2></div><span className="badge violet">52 pass snapshots</span></div><div className="pass-list">{[["17", "AutoTileMatmulL0", "L0 tile search"], ["24", "InjectGMPipeBuffer", "GM pipeline allocation"], ["30", "LowerPipelineLoops", "stage replication"], ["31", "CanonicalizeIOOrder", "pipeline IO ordering"], ["35", "MemoryReuse", "Vec buffer coalescing"], ["36", "AllocateMemoryAddr", "capacity report"]].map(([n, name, desc]) => <button key={n} className={n === "35" ? "pass active" : "pass"} onClick={() => setCandidate(n === "35" ? "pipeline" : "tile")}><span>{n}</span><b>{name}</b><small>{desc}</small><i>snapshot</i></button>)}</div><div className="diagnostic"><span>PH-MR-001</span><p>software pipeline requested depth 2 in Vec, but only 1 of 2 buffers fit; stages serialize.</p><button onClick={() => { setCandidate("pipeline"); setActive("queue"); }}>转为验证项 →</button></div></article><aside className="panel artifact-panel"><span className="eyebrow">ARTIFACT MAP</span><h2>当前数据集</h2><dl><dt>Runtime</dt><dd>rank0 / rank1 swimlane</dd><dt>Graph</dt><dd>two deps.json files</dd><dt>Source map</dt><dd>two name_map.json files</dd><dt>IR</dt><dd>00–51 passes_dump</dd><dt>Build</dt><dd>64 InCore cache contexts</dd><dt>Hints</dt><dd>perf_hints.log</dd></dl><button className="outline" onClick={() => setActive("overview")}>回到执行概览</button></aside></section>}
    </main>
  </div>;
}
