// Kernel Function: post_rms_reduce
// Generated by PyPTO IR Compiler (PTO backend)

#include <cstdint>

#ifndef __gm__
#define __gm__
#endif

#ifndef __aicore__
#if defined(__CPU_SIM)
#define __aicore__
#else
#define __aicore__ [aicore]
#endif
#endif

#include <pto/pto-inst.hpp>
#include "tensor.h"


using namespace pto;


// --- ptoas-generated code ---

enum class PTOAutoSyncTailMode : int {
  kBarrierAll = 0,
  kSetWaitMte3ToSEvent0 = 1,
};

static __aicore__ inline void ptoas_auto_sync_tail(
    PTOAutoSyncTailMode mode = PTOAutoSyncTailMode::kBarrierAll) {
  switch (mode) {
  case PTOAutoSyncTailMode::kSetWaitMte3ToSEvent0:
    set_flag(PIPE_MTE3, PIPE_S, EVENT_ID0);
    wait_flag(PIPE_MTE3, PIPE_S, EVENT_ID0);
    break;
  case PTOAutoSyncTailMode::kBarrierAll:
  default:
    pipe_barrier(PIPE_ALL);
    break;
  }
}

static __aicore__ void post_rms_reduce(__gm__ float* v1, __gm__ float* v2, __gm__ float* v3) {
  const float v4 = 9.99999997E-7f;
  const float v5 = 1.95312503E-4f;
  const int64_t v6 = 256;
  const int64_t v7 = 2;
  const int64_t v8 = 20;
  const float v9 = 0.0f;
  const int64_t v10 = 1;
  const int64_t v11 = 5120;
  const int64_t v12 = 16;
  const int64_t v13 = 0;
  const int64_t v14 = 49280;
  const int64_t v15 = 32896;
  const int64_t v16 = 16512;
  const int64_t v17 = 128;
  const int64_t v18 = 64;
  using T = float;

  #if defined(__DAV_VEC__)
  set_mask_norm();
  set_vector_mask(-1, -1);
  Tile<TileType::Vec, float, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v19 = Tile<TileType::Vec, float, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v10, v12);
  uint64_t v20 = (uint64_t) v18;
  TASSIGN(v19, v20);
  set_flag(PIPE_V, PIPE_MTE2, EVENT_ID0);
  set_flag(PIPE_V, PIPE_MTE2, EVENT_ID1);
  TEXPANDS(v19, v9);
  for (size_t v21 = (size_t) v13; v21 < ((size_t) v8); v21 += (size_t) v7) {
    int64_t v22 = (int64_t) ((uint64_t) ((int64_t) v21) * (uint64_t) v6);
    int64_t v23 = (int64_t) ((uint64_t) v22 + (uint64_t) v6);
    Tile<TileType::Vec, float, 16, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v24 = Tile<TileType::Vec, float, 16, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v12, v6);
    uint64_t v25 = (uint64_t) v17;
    TASSIGN(v24, v25);
    pto::Shape<1, 1, 1, 16, 256> v26 = pto::Shape<1, 1, 1, 16, 256>();
    pto::Stride<81920, 81920, 81920, 5120, 1> v27 = pto::Stride<81920, 81920, 81920, 5120, 1>();
    GlobalTensor<float, pto::Shape<1, 1, 1, 16, 256>, pto::Stride<81920, 81920, 81920, 5120, 1>, pto::Layout::ND> v28 = GlobalTensor<float, pto::Shape<1, 1, 1, 16, 256>, pto::Stride<81920, 81920, 81920, 5120, 1>, pto::Layout::ND>(v1 + (v13 + v13 * v11 + v22 * v10), v26, v27);
    wait_flag(PIPE_V, PIPE_MTE2, EVENT_ID0);
    TLOAD(v24, v28);
    Tile<TileType::Vec, float, 16, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v29 = Tile<TileType::Vec, float, 16, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v12, v6);
    uint64_t v30 = (uint64_t) v16;
    TASSIGN(v29, v30);
    pto::Shape<1, 1, 1, 16, 256> v31 = pto::Shape<1, 1, 1, 16, 256>();
    pto::Stride<81920, 81920, 81920, 5120, 1> v32 = pto::Stride<81920, 81920, 81920, 5120, 1>();
    GlobalTensor<float, pto::Shape<1, 1, 1, 16, 256>, pto::Stride<81920, 81920, 81920, 5120, 1>, pto::Layout::ND> v33 = GlobalTensor<float, pto::Shape<1, 1, 1, 16, 256>, pto::Stride<81920, 81920, 81920, 5120, 1>, pto::Layout::ND>(v2 + (v13 + v13 * v11 + v22 * v10), v31, v32);
    TLOAD(v29, v33);
    set_flag(PIPE_MTE2, PIPE_V, EVENT_ID0);
    Tile<TileType::Vec, float, 16, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v34 = Tile<TileType::Vec, float, 16, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v12, v6);
    uint64_t v35 = (uint64_t) v15;
    TASSIGN(v34, v35);
    pto::Shape<1, 1, 1, 16, 256> v36 = pto::Shape<1, 1, 1, 16, 256>();
    pto::Stride<81920, 81920, 81920, 5120, 1> v37 = pto::Stride<81920, 81920, 81920, 5120, 1>();
    GlobalTensor<float, pto::Shape<1, 1, 1, 16, 256>, pto::Stride<81920, 81920, 81920, 5120, 1>, pto::Layout::ND> v38 = GlobalTensor<float, pto::Shape<1, 1, 1, 16, 256>, pto::Stride<81920, 81920, 81920, 5120, 1>, pto::Layout::ND>(v1 + (v13 + v13 * v11 + v23 * v10), v36, v37);
    wait_flag(PIPE_V, PIPE_MTE2, EVENT_ID1);
    TLOAD(v34, v38);
    Tile<TileType::Vec, float, 16, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v39 = Tile<TileType::Vec, float, 16, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v12, v6);
    uint64_t v40 = (uint64_t) v14;
    TASSIGN(v39, v40);
    pto::Shape<1, 1, 1, 16, 256> v41 = pto::Shape<1, 1, 1, 16, 256>();
    pto::Stride<81920, 81920, 81920, 5120, 1> v42 = pto::Stride<81920, 81920, 81920, 5120, 1>();
    GlobalTensor<float, pto::Shape<1, 1, 1, 16, 256>, pto::Stride<81920, 81920, 81920, 5120, 1>, pto::Layout::ND> v43 = GlobalTensor<float, pto::Shape<1, 1, 1, 16, 256>, pto::Stride<81920, 81920, 81920, 5120, 1>, pto::Layout::ND>(v2 + (v13 + v13 * v11 + v23 * v10), v41, v42);
    TLOAD(v39, v43);
    set_flag(PIPE_MTE2, PIPE_V, EVENT_ID1);
    Tile<TileType::Vec, float, 16, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v44 = Tile<TileType::Vec, float, 16, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v12, v6);
    uint64_t v45 = (uint64_t) v17;
    TASSIGN(v44, v45);
    wait_flag(PIPE_MTE2, PIPE_V, EVENT_ID0);
    TADD(v44, v24, v29);
    Tile<TileType::Vec, float, 16, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v46 = Tile<TileType::Vec, float, 16, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v12, v6);
    uint64_t v47 = (uint64_t) v17;
    TASSIGN(v46, v47);
    pipe_barrier(PIPE_V);
    TMUL(v46, v44, v44);
    Tile<TileType::Vec, float, 16, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v48 = Tile<TileType::Vec, float, 16, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v12, v6);
    uint64_t v49 = (uint64_t) v16;
    TASSIGN(v48, v49);
    Tile<TileType::Vec, float, 16, 1, BLayout::ColMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v50 = Tile<TileType::Vec, float, 16, 1, BLayout::ColMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v12, v10);
    uint64_t v51 = (uint64_t) v13;
    TASSIGN(v50, v51);
    pipe_barrier(PIPE_V);
    TROWSUM(v50, v46, v48);
    Tile<TileType::Vec, float, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v52 = Tile<TileType::Vec, float, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v10, v12);
    uint64_t v53 = (uint64_t) v13;
    TASSIGN(v52, v53);
    Tile<TileType::Vec, float, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v54 = Tile<TileType::Vec, float, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v10, v12);
    uint64_t v55 = (uint64_t) v13;
    TASSIGN(v54, v55);
    pipe_barrier(PIPE_V);
    TADD(v54, v19, v52);
    Tile<TileType::Vec, float, 16, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v56 = Tile<TileType::Vec, float, 16, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v12, v6);
    uint64_t v57 = (uint64_t) v17;
    TASSIGN(v56, v57);
    wait_flag(PIPE_MTE2, PIPE_V, EVENT_ID1);
    TADD(v56, v34, v39);
    Tile<TileType::Vec, float, 16, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v58 = Tile<TileType::Vec, float, 16, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v12, v6);
    uint64_t v59 = (uint64_t) v17;
    TASSIGN(v58, v59);
    pipe_barrier(PIPE_V);
    TMUL(v58, v56, v56);
    Tile<TileType::Vec, float, 16, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v60 = Tile<TileType::Vec, float, 16, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v12, v6);
    uint64_t v61 = (uint64_t) v16;
    TASSIGN(v60, v61);
    Tile<TileType::Vec, float, 16, 1, BLayout::ColMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v62 = Tile<TileType::Vec, float, 16, 1, BLayout::ColMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v12, v10);
    uint64_t v63 = (uint64_t) v15;
    TASSIGN(v62, v63);
    pipe_barrier(PIPE_V);
    TROWSUM(v62, v58, v60);
    set_flag(PIPE_V, PIPE_MTE2, EVENT_ID0);
    Tile<TileType::Vec, float, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v64 = Tile<TileType::Vec, float, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v10, v12);
    uint64_t v65 = (uint64_t) v15;
    TASSIGN(v64, v65);
    Tile<TileType::Vec, float, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v66 = Tile<TileType::Vec, float, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v10, v12);
    uint64_t v67 = (uint64_t) v18;
    TASSIGN(v66, v67);
    pipe_barrier(PIPE_V);
    TADD(v66, v54, v64);
    set_flag(PIPE_V, PIPE_MTE2, EVENT_ID1);
  }
  Tile<TileType::Vec, float, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v68 = Tile<TileType::Vec, float, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v10, v12);
  uint64_t v69 = (uint64_t) v17;
  TASSIGN(v68, v69);
  pipe_barrier(PIPE_V);
  TMULS(v68, v19, v5);
  Tile<TileType::Vec, float, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v70 = Tile<TileType::Vec, float, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v10, v12);
  uint64_t v71 = (uint64_t) v17;
  TASSIGN(v70, v71);
  pipe_barrier(PIPE_V);
  TADDS(v70, v68, v4);
  Tile<TileType::Vec, float, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v72 = Tile<TileType::Vec, float, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v10, v12);
  uint64_t v73 = (uint64_t) v17;
  TASSIGN(v72, v73);
  pipe_barrier(PIPE_V);
  TSQRT(v72, v70);
  Tile<TileType::Vec, float, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v74 = Tile<TileType::Vec, float, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v10, v12);
  uint64_t v75 = (uint64_t) v16;
  TASSIGN(v74, v75);
  pipe_barrier(PIPE_V);
  TRECIP(v74, v72);
  set_flag(PIPE_V, PIPE_MTE3, EVENT_ID0);
  Tile<TileType::Vec, float, 16, 1, BLayout::ColMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v76 = Tile<TileType::Vec, float, 16, 1, BLayout::ColMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v12, v10);
  uint64_t v77 = (uint64_t) v16;
  TASSIGN(v76, v77);
  pto::Shape<1, 1, 1, 16, 1> v78 = pto::Shape<1, 1, 1, 16, 1>();
  pto::Stride<16, 16, 16, 1, 16> v79 = pto::Stride<16, 16, 16, 1, 16>();
  GlobalTensor<float, pto::Shape<1, 1, 1, 16, 1>, pto::Stride<16, 16, 16, 1, 16>, pto::Layout::DN> v80 = GlobalTensor<float, pto::Shape<1, 1, 1, 16, 1>, pto::Stride<16, 16, 16, 1, 16>, pto::Layout::DN>(v3 + (v13 + v13 * v10 + v13 * v12), v78, v79);
  wait_flag(PIPE_V, PIPE_MTE3, EVENT_ID0);
  TSTORE(v80, v76);
  wait_flag(PIPE_V, PIPE_MTE2, EVENT_ID0);
  wait_flag(PIPE_V, PIPE_MTE2, EVENT_ID1);
  #endif // __DAV_VEC__

  ptoas_auto_sync_tail(PTOAutoSyncTailMode::kBarrierAll);
  return;
}
// --- Kernel entry point ---
extern "C" __aicore__ __attribute__((always_inline)) void kernel_entry(__gm__ int64_t* args)
{
    // Unpack tensor: attn_proj_fp32_inline468__rv_v5
    __gm__ Tensor* attn_proj_fp32_inline468__rv_v5_tensor = reinterpret_cast<__gm__ Tensor*>(args[0]);
    __gm__ float* attn_proj_fp32_inline468__rv_v5 = reinterpret_cast<__gm__ float*>(attn_proj_fp32_inline468__rv_v5_tensor->buffer.addr) + attn_proj_fp32_inline468__rv_v5_tensor->start_offset;

    // Unpack tensor: cur__rv_v2
    __gm__ Tensor* cur__rv_v2_tensor = reinterpret_cast<__gm__ Tensor*>(args[1]);
    __gm__ float* cur__rv_v2 = reinterpret_cast<__gm__ float*>(cur__rv_v2_tensor->buffer.addr) + cur__rv_v2_tensor->start_offset;

    // Unpack tensor: inv_rms_tile_inline123__ssa_v0
    __gm__ Tensor* inv_rms_tile_inline123__ssa_v0_tensor = reinterpret_cast<__gm__ Tensor*>(args[2]);
    __gm__ float* inv_rms_tile_inline123__ssa_v0 = reinterpret_cast<__gm__ float*>(inv_rms_tile_inline123__ssa_v0_tensor->buffer.addr) + inv_rms_tile_inline123__ssa_v0_tensor->start_offset;

    // Forward to ptoas-generated function
    post_rms_reduce(attn_proj_fp32_inline468__rv_v5, cur__rv_v2, inv_rms_tile_inline123__ssa_v0);
}
