// Kernel Function: qk_norm
// Generated by PyPTO IR Compiler (PTO backend)

#include <cstdint>

#ifndef __gm__
#define __gm__
#endif

#ifndef __aicore__
#if defined(__CPU_SIM)
#define __aicore__
#else
#define __aicore__ [aicore]
#endif
#endif

#include <pto/pto-inst.hpp>
#include "tensor.h"


using namespace pto;


// --- ptoas-generated code ---

enum class PTOAutoSyncTailMode : int {
  kBarrierAll = 0,
  kSetWaitMte3ToSEvent0 = 1,
};

static __aicore__ inline void ptoas_auto_sync_tail(
    PTOAutoSyncTailMode mode = PTOAutoSyncTailMode::kBarrierAll) {
  switch (mode) {
  case PTOAutoSyncTailMode::kSetWaitMte3ToSEvent0:
    set_flag(PIPE_MTE3, PIPE_S, EVENT_ID0);
    wait_flag(PIPE_MTE3, PIPE_S, EVENT_ID0);
    break;
  case PTOAutoSyncTailMode::kBarrierAll:
  default:
    pipe_barrier(PIPE_ALL);
    break;
  }
}

static __aicore__ void qk_norm(__gm__ float* v1, __gm__ float* v2, __gm__ float* v3, __gm__ float* v4, __gm__ float* v5, __gm__ float* v6, __gm__ float* v7, __gm__ float* v8, __gm__ float* v9) {
  const float v10 = 9.99999997E-7f;
  const float v11 = 0.0078125f;
  const int64_t v12 = 80;
  const int64_t v13 = 640;
  const int64_t v14 = 128;
  const int64_t v15 = 1;
  const int64_t v16 = 5120;
  const int64_t v17 = 16;
  const int64_t v18 = 41984;
  const int64_t v19 = 1024;
  const int64_t v20 = 512;
  const int64_t v21 = 0;
  const int64_t v22 = 82944;
  using T = float;

  #if defined(__DAV_VEC__)
  set_mask_norm();
  set_vector_mask(-1, -1);
  Tile<TileType::Vec, float, 16, 1, BLayout::ColMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v23 = Tile<TileType::Vec, float, 16, 1, BLayout::ColMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v17, v15);
  uint64_t v24 = (uint64_t) v22;
  TASSIGN(v23, v24);
  pto::Shape<1, 1, 1, 16, 1> v25 = pto::Shape<1, 1, 1, 16, 1>();
  pto::Stride<16, 16, 16, 1, 16> v26 = pto::Stride<16, 16, 16, 1, 16>();
  GlobalTensor<float, pto::Shape<1, 1, 1, 16, 1>, pto::Stride<16, 16, 16, 1, 16>, pto::Layout::DN> v27 = GlobalTensor<float, pto::Shape<1, 1, 1, 16, 1>, pto::Stride<16, 16, 16, 1, 16>, pto::Layout::DN>(v2 + (v21 + v21 * v15 + v21 * v17), v25, v26);
  TLOAD(v23, v27);
  Tile<TileType::Vec, float, 1, 128, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v28 = Tile<TileType::Vec, float, 1, 128, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v15, v14);
  uint64_t v29 = (uint64_t) v21;
  TASSIGN(v28, v29);
  pto::Shape<1, 1, 1, 1, 128> v30 = pto::Shape<1, 1, 1, 1, 128>();
  pto::Stride<128, 128, 128, 128, 1> v31 = pto::Stride<128, 128, 128, 128, 1>();
  GlobalTensor<float, pto::Shape<1, 1, 1, 1, 128>, pto::Stride<128, 128, 128, 128, 1>, pto::Layout::ND> v32 = GlobalTensor<float, pto::Shape<1, 1, 1, 1, 128>, pto::Stride<128, 128, 128, 128, 1>, pto::Layout::ND>(v3 + (v21 + v21 * v14 + v21 * v15), v30, v31);
  TLOAD(v28, v32);
  Tile<TileType::Vec, float, 1, 128, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v33 = Tile<TileType::Vec, float, 1, 128, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v15, v14);
  uint64_t v34 = (uint64_t) v20;
  TASSIGN(v33, v34);
  pto::Shape<1, 1, 1, 1, 128> v35 = pto::Shape<1, 1, 1, 1, 128>();
  pto::Stride<128, 128, 128, 128, 1> v36 = pto::Stride<128, 128, 128, 128, 1>();
  GlobalTensor<float, pto::Shape<1, 1, 1, 1, 128>, pto::Stride<128, 128, 128, 128, 1>, pto::Layout::ND> v37 = GlobalTensor<float, pto::Shape<1, 1, 1, 1, 128>, pto::Stride<128, 128, 128, 128, 1>, pto::Layout::ND>(v7 + (v21 + v21 * v14 + v21 * v15), v35, v36);
  TLOAD(v33, v37);
  Tile<TileType::Vec, float, 16, 640, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v38 = Tile<TileType::Vec, float, 16, 640, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v17, v13);
  uint64_t v39 = (uint64_t) v19;
  TASSIGN(v38, v39);
  pto::Shape<1, 1, 1, 16, 640> v40 = pto::Shape<1, 1, 1, 16, 640>();
  pto::Stride<81920, 81920, 81920, 5120, 1> v41 = pto::Stride<81920, 81920, 81920, 5120, 1>();
  GlobalTensor<float, pto::Shape<1, 1, 1, 16, 640>, pto::Stride<81920, 81920, 81920, 5120, 1>, pto::Layout::ND> v42 = GlobalTensor<float, pto::Shape<1, 1, 1, 16, 640>, pto::Stride<81920, 81920, 81920, 5120, 1>, pto::Layout::ND>(v1 + (v21 + v21 * v16 + v21 * v15), v40, v41);
  TLOAD(v38, v42);
  set_flag(PIPE_MTE2, PIPE_V, EVENT_ID0);
  Tile<TileType::Vec, float, 16, 640, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v43 = Tile<TileType::Vec, float, 16, 640, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v17, v13);
  uint64_t v44 = (uint64_t) v19;
  TASSIGN(v43, v44);
  wait_flag(PIPE_MTE2, PIPE_V, EVENT_ID0);
  TROWEXPANDMUL(v43, v38, v23);
  Tile<TileType::Vec, float, 80, 128, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v45 = Tile<TileType::Vec, float, 80, 128, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v12, v14);
  uint64_t v46 = (uint64_t) v19;
  TASSIGN(v45, v46);
  Tile<TileType::Vec, float, 80, 128, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v47 = Tile<TileType::Vec, float, 80, 128, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v12, v14);
  uint64_t v48 = (uint64_t) v18;
  TASSIGN(v47, v48);
  pipe_barrier(PIPE_V);
  TCOLEXPANDMUL(v47, v45, v28);
  set_flag(PIPE_V, PIPE_MTE3, EVENT_ID0);
  Tile<TileType::Vec, float, 16, 640, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v49 = Tile<TileType::Vec, float, 16, 640, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v17, v13);
  uint64_t v50 = (uint64_t) v18;
  TASSIGN(v49, v50);
  pto::Shape<1, 1, 1, 16, 640> v51 = pto::Shape<1, 1, 1, 16, 640>();
  pto::Stride<81920, 81920, 81920, 5120, 1> v52 = pto::Stride<81920, 81920, 81920, 5120, 1>();
  GlobalTensor<float, pto::Shape<1, 1, 1, 16, 640>, pto::Stride<81920, 81920, 81920, 5120, 1>, pto::Layout::ND> v53 = GlobalTensor<float, pto::Shape<1, 1, 1, 16, 640>, pto::Stride<81920, 81920, 81920, 5120, 1>, pto::Layout::ND>(v4 + (v21 + v21 * v16 + v21 * v15), v51, v52);
  wait_flag(PIPE_V, PIPE_MTE3, EVENT_ID0);
  TSTORE(v53, v49);
  set_flag(PIPE_MTE3, PIPE_V, EVENT_ID0);
  Tile<TileType::Vec, float, 80, 128, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v54 = Tile<TileType::Vec, float, 80, 128, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v12, v14);
  uint64_t v55 = (uint64_t) v19;
  TASSIGN(v54, v55);
  pipe_barrier(PIPE_V);
  TMUL(v54, v45, v45);
  Tile<TileType::Vec, float, 80, 128, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v56 = Tile<TileType::Vec, float, 80, 128, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v12, v14);
  uint64_t v57 = (uint64_t) v18;
  TASSIGN(v56, v57);
  Tile<TileType::Vec, float, 80, 1, BLayout::ColMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v58 = Tile<TileType::Vec, float, 80, 1, BLayout::ColMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v12, v15);
  uint64_t v59 = (uint64_t) v21;
  TASSIGN(v58, v59);
  wait_flag(PIPE_MTE3, PIPE_V, EVENT_ID0);
  TROWSUM(v58, v54, v56);
  Tile<TileType::Vec, float, 1, 80, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v60 = Tile<TileType::Vec, float, 1, 80, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v15, v12);
  uint64_t v61 = (uint64_t) v21;
  TASSIGN(v60, v61);
  Tile<TileType::Vec, float, 1, 80, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v62 = Tile<TileType::Vec, float, 1, 80, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v15, v12);
  uint64_t v63 = (uint64_t) v19;
  TASSIGN(v62, v63);
  pipe_barrier(PIPE_V);
  TMULS(v62, v60, v11);
  Tile<TileType::Vec, float, 1, 80, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v64 = Tile<TileType::Vec, float, 1, 80, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v15, v12);
  uint64_t v65 = (uint64_t) v19;
  TASSIGN(v64, v65);
  Tile<TileType::Vec, float, 1, 80, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v66 = Tile<TileType::Vec, float, 1, 80, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v15, v12);
  uint64_t v67 = (uint64_t) v19;
  TASSIGN(v66, v67);
  pipe_barrier(PIPE_V);
  TADDS(v66, v64, v10);
  Tile<TileType::Vec, float, 1, 80, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v68 = Tile<TileType::Vec, float, 1, 80, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v15, v12);
  uint64_t v69 = (uint64_t) v19;
  TASSIGN(v68, v69);
  Tile<TileType::Vec, float, 1, 80, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v70 = Tile<TileType::Vec, float, 1, 80, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v15, v12);
  uint64_t v71 = (uint64_t) v19;
  TASSIGN(v70, v71);
  pipe_barrier(PIPE_V);
  TSQRT(v70, v68);
  Tile<TileType::Vec, float, 1, 80, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v72 = Tile<TileType::Vec, float, 1, 80, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v15, v12);
  uint64_t v73 = (uint64_t) v19;
  TASSIGN(v72, v73);
  Tile<TileType::Vec, float, 1, 80, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v74 = Tile<TileType::Vec, float, 1, 80, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v15, v12);
  uint64_t v75 = (uint64_t) v18;
  TASSIGN(v74, v75);
  pipe_barrier(PIPE_V);
  TRECIP(v74, v72);
  set_flag(PIPE_V, PIPE_MTE3, EVENT_ID1);
  set_flag(PIPE_V, PIPE_MTE2, EVENT_ID0);
  Tile<TileType::Vec, float, 80, 1, BLayout::ColMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v76 = Tile<TileType::Vec, float, 80, 1, BLayout::ColMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v12, v15);
  uint64_t v77 = (uint64_t) v18;
  TASSIGN(v76, v77);
  pto::Shape<1, 1, 1, 80, 1> v78 = pto::Shape<1, 1, 1, 80, 1>();
  pto::Stride<80, 80, 80, 1, 640> v79 = pto::Stride<80, 80, 80, 1, 640>();
  GlobalTensor<float, pto::Shape<1, 1, 1, 80, 1>, pto::Stride<80, 80, 80, 1, 640>, pto::Layout::DN> v80 = GlobalTensor<float, pto::Shape<1, 1, 1, 80, 1>, pto::Stride<80, 80, 80, 1, 640>, pto::Layout::DN>(v5 + (v21 + v21 * v15 + v21 * v13), v78, v79);
  wait_flag(PIPE_V, PIPE_MTE3, EVENT_ID1);
  TSTORE(v80, v76);
  set_flag(PIPE_MTE3, PIPE_V, EVENT_ID1);
  Tile<TileType::Vec, float, 16, 128, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v81 = Tile<TileType::Vec, float, 16, 128, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v17, v14);
  uint64_t v82 = (uint64_t) v19;
  TASSIGN(v81, v82);
  pto::Shape<1, 1, 1, 16, 128> v83 = pto::Shape<1, 1, 1, 16, 128>();
  pto::Stride<16384, 16384, 16384, 1024, 1> v84 = pto::Stride<16384, 16384, 16384, 1024, 1>();
  GlobalTensor<float, pto::Shape<1, 1, 1, 16, 128>, pto::Stride<16384, 16384, 16384, 1024, 1>, pto::Layout::ND> v85 = GlobalTensor<float, pto::Shape<1, 1, 1, 16, 128>, pto::Stride<16384, 16384, 16384, 1024, 1>, pto::Layout::ND>(v6 + (v21 + v21 * v19 + v21 * v15), v83, v84);
  wait_flag(PIPE_V, PIPE_MTE2, EVENT_ID0);
  TLOAD(v81, v85);
  set_flag(PIPE_MTE2, PIPE_V, EVENT_ID1);
  Tile<TileType::Vec, float, 16, 128, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v86 = Tile<TileType::Vec, float, 16, 128, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v17, v14);
  uint64_t v87 = (uint64_t) v19;
  TASSIGN(v86, v87);
  wait_flag(PIPE_MTE2, PIPE_V, EVENT_ID1);
  TROWEXPANDMUL(v86, v81, v23);
  Tile<TileType::Vec, float, 16, 128, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v88 = Tile<TileType::Vec, float, 16, 128, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v17, v14);
  uint64_t v89 = (uint64_t) v18;
  TASSIGN(v88, v89);
  wait_flag(PIPE_MTE3, PIPE_V, EVENT_ID1);
  TCOLEXPANDMUL(v88, v86, v33);
  set_flag(PIPE_V, PIPE_MTE3, EVENT_ID2);
  pto::Shape<1, 1, 1, 16, 128> v90 = pto::Shape<1, 1, 1, 16, 128>();
  pto::Stride<16384, 16384, 16384, 1024, 1> v91 = pto::Stride<16384, 16384, 16384, 1024, 1>();
  GlobalTensor<float, pto::Shape<1, 1, 1, 16, 128>, pto::Stride<16384, 16384, 16384, 1024, 1>, pto::Layout::ND> v92 = GlobalTensor<float, pto::Shape<1, 1, 1, 16, 128>, pto::Stride<16384, 16384, 16384, 1024, 1>, pto::Layout::ND>(v8 + (v21 + v21 * v19 + v21 * v15), v90, v91);
  wait_flag(PIPE_V, PIPE_MTE3, EVENT_ID2);
  TSTORE(v92, v88);
  set_flag(PIPE_MTE3, PIPE_V, EVENT_ID2);
  Tile<TileType::Vec, float, 16, 128, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v93 = Tile<TileType::Vec, float, 16, 128, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v17, v14);
  uint64_t v94 = (uint64_t) v19;
  TASSIGN(v93, v94);
  pipe_barrier(PIPE_V);
  TMUL(v93, v86, v86);
  Tile<TileType::Vec, float, 16, 128, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v95 = Tile<TileType::Vec, float, 16, 128, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v17, v14);
  uint64_t v96 = (uint64_t) v18;
  TASSIGN(v95, v96);
  Tile<TileType::Vec, float, 16, 1, BLayout::ColMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v97 = Tile<TileType::Vec, float, 16, 1, BLayout::ColMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v17, v15);
  uint64_t v98 = (uint64_t) v21;
  TASSIGN(v97, v98);
  wait_flag(PIPE_MTE3, PIPE_V, EVENT_ID2);
  TROWSUM(v97, v93, v95);
  Tile<TileType::Vec, float, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v99 = Tile<TileType::Vec, float, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v15, v17);
  uint64_t v100 = (uint64_t) v21;
  TASSIGN(v99, v100);
  Tile<TileType::Vec, float, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v101 = Tile<TileType::Vec, float, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v15, v17);
  uint64_t v102 = (uint64_t) v19;
  TASSIGN(v101, v102);
  pipe_barrier(PIPE_V);
  TMULS(v101, v99, v11);
  Tile<TileType::Vec, float, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v103 = Tile<TileType::Vec, float, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v15, v17);
  uint64_t v104 = (uint64_t) v19;
  TASSIGN(v103, v104);
  Tile<TileType::Vec, float, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v105 = Tile<TileType::Vec, float, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v15, v17);
  uint64_t v106 = (uint64_t) v19;
  TASSIGN(v105, v106);
  pipe_barrier(PIPE_V);
  TADDS(v105, v103, v10);
  Tile<TileType::Vec, float, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v107 = Tile<TileType::Vec, float, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v15, v17);
  uint64_t v108 = (uint64_t) v19;
  TASSIGN(v107, v108);
  Tile<TileType::Vec, float, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v109 = Tile<TileType::Vec, float, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v15, v17);
  uint64_t v110 = (uint64_t) v19;
  TASSIGN(v109, v110);
  pipe_barrier(PIPE_V);
  TSQRT(v109, v107);
  Tile<TileType::Vec, float, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v111 = Tile<TileType::Vec, float, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v15, v17);
  uint64_t v112 = (uint64_t) v19;
  TASSIGN(v111, v112);
  Tile<TileType::Vec, float, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v113 = Tile<TileType::Vec, float, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v15, v17);
  uint64_t v114 = (uint64_t) v18;
  TASSIGN(v113, v114);
  pipe_barrier(PIPE_V);
  TRECIP(v113, v111);
  set_flag(PIPE_V, PIPE_MTE3, EVENT_ID3);
  Tile<TileType::Vec, float, 16, 1, BLayout::ColMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v115 = Tile<TileType::Vec, float, 16, 1, BLayout::ColMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v17, v15);
  uint64_t v116 = (uint64_t) v18;
  TASSIGN(v115, v116);
  pto::Shape<1, 1, 1, 16, 1> v117 = pto::Shape<1, 1, 1, 16, 1>();
  pto::Stride<16, 16, 16, 1, 128> v118 = pto::Stride<16, 16, 16, 1, 128>();
  GlobalTensor<float, pto::Shape<1, 1, 1, 16, 1>, pto::Stride<16, 16, 16, 1, 128>, pto::Layout::DN> v119 = GlobalTensor<float, pto::Shape<1, 1, 1, 16, 1>, pto::Stride<16, 16, 16, 1, 128>, pto::Layout::DN>(v9 + (v21 + v21 * v15 + v21 * v14), v117, v118);
  wait_flag(PIPE_V, PIPE_MTE3, EVENT_ID3);
  TSTORE(v119, v115);
  #endif // __DAV_VEC__

  ptoas_auto_sync_tail(PTOAutoSyncTailMode::kBarrierAll);
  return;
}
// --- Kernel entry point ---
extern "C" __aicore__ __attribute__((always_inline)) void kernel_entry(__gm__ int64_t* args)
{
    // Unpack tensor: q_proj_inline248__rv_v5
    __gm__ Tensor* q_proj_inline248__rv_v5_tensor = reinterpret_cast<__gm__ Tensor*>(args[0]);
    __gm__ float* q_proj_inline248__rv_v5 = reinterpret_cast<__gm__ float*>(q_proj_inline248__rv_v5_tensor->buffer.addr) + q_proj_inline248__rv_v5_tensor->start_offset;

    // Unpack tensor: inv_rms_col_inline165__ssa_v0
    __gm__ Tensor* inv_rms_col_inline165__ssa_v0_tensor = reinterpret_cast<__gm__ Tensor*>(args[1]);
    __gm__ float* inv_rms_col_inline165__ssa_v0 = reinterpret_cast<__gm__ float*>(inv_rms_col_inline165__ssa_v0_tensor->buffer.addr) + inv_rms_col_inline165__ssa_v0_tensor->start_offset;

    // Unpack tensor: q_norm_w_inline277__ssa_v0
    __gm__ Tensor* q_norm_w_inline277__ssa_v0_tensor = reinterpret_cast<__gm__ Tensor*>(args[2]);
    __gm__ float* q_norm_w_inline277__ssa_v0 = reinterpret_cast<__gm__ float*>(q_norm_w_inline277__ssa_v0_tensor->buffer.addr) + q_norm_w_inline277__ssa_v0_tensor->start_offset;

    // Unpack tensor: q_proj_norm_inline375__ssa_v0
    __gm__ Tensor* q_proj_norm_inline375__ssa_v0_tensor = reinterpret_cast<__gm__ Tensor*>(args[3]);
    __gm__ float* q_proj_norm_inline375__ssa_v0 = reinterpret_cast<__gm__ float*>(q_proj_norm_inline375__ssa_v0_tensor->buffer.addr) + q_proj_norm_inline375__ssa_v0_tensor->start_offset;

    // Unpack tensor: q_inv_states_inline168__ssa_v0
    __gm__ Tensor* q_inv_states_inline168__ssa_v0_tensor = reinterpret_cast<__gm__ Tensor*>(args[4]);
    __gm__ float* q_inv_states_inline168__ssa_v0 = reinterpret_cast<__gm__ float*>(q_inv_states_inline168__ssa_v0_tensor->buffer.addr) + q_inv_states_inline168__ssa_v0_tensor->start_offset;

    // Unpack tensor: k_proj_inline383__rv_v3
    __gm__ Tensor* k_proj_inline383__rv_v3_tensor = reinterpret_cast<__gm__ Tensor*>(args[5]);
    __gm__ float* k_proj_inline383__rv_v3 = reinterpret_cast<__gm__ float*>(k_proj_inline383__rv_v3_tensor->buffer.addr) + k_proj_inline383__rv_v3_tensor->start_offset;

    // Unpack tensor: k_norm_w_inline253__ssa_v0
    __gm__ Tensor* k_norm_w_inline253__ssa_v0_tensor = reinterpret_cast<__gm__ Tensor*>(args[6]);
    __gm__ float* k_norm_w_inline253__ssa_v0 = reinterpret_cast<__gm__ float*>(k_norm_w_inline253__ssa_v0_tensor->buffer.addr) + k_norm_w_inline253__ssa_v0_tensor->start_offset;

    // Unpack tensor: k_proj_norm_inline171__ssa_v0
    __gm__ Tensor* k_proj_norm_inline171__ssa_v0_tensor = reinterpret_cast<__gm__ Tensor*>(args[7]);
    __gm__ float* k_proj_norm_inline171__ssa_v0 = reinterpret_cast<__gm__ float*>(k_proj_norm_inline171__ssa_v0_tensor->buffer.addr) + k_proj_norm_inline171__ssa_v0_tensor->start_offset;

    // Unpack tensor: k_inv_states_inline204__ssa_v0
    __gm__ Tensor* k_inv_states_inline204__ssa_v0_tensor = reinterpret_cast<__gm__ Tensor*>(args[8]);
    __gm__ float* k_inv_states_inline204__ssa_v0 = reinterpret_cast<__gm__ float*>(k_inv_states_inline204__ssa_v0_tensor->buffer.addr) + k_inv_states_inline204__ssa_v0_tensor->start_offset;

    // Forward to ptoas-generated function
    qk_norm(q_proj_inline248__rv_v5, inv_rms_col_inline165__ssa_v0, q_norm_w_inline277__ssa_v0, q_proj_norm_inline375__ssa_v0, q_inv_states_inline168__ssa_v0, k_proj_inline383__rv_v3, k_norm_w_inline253__ssa_v0, k_proj_norm_inline171__ssa_v0, k_inv_states_inline204__ssa_v0);
}
