// Kernel Function: rope_qkv
// Generated by PyPTO IR Compiler (PTO backend)

#include <cstdint>

#ifndef __gm__
#define __gm__
#endif

#ifndef __aicore__
#if defined(__CPU_SIM)
#define __aicore__
#else
#define __aicore__ [aicore]
#endif
#endif

#include <pto/pto-inst.hpp>
#include "tensor.h"
#include "intrinsic.h"


using namespace pto;


// --- ptoas-generated code ---

enum class PTOAutoSyncTailMode : int {
  kBarrierAll = 0,
  kSetWaitMte3ToSEvent0 = 1,
};

static __aicore__ inline void ptoas_auto_sync_tail(
    PTOAutoSyncTailMode mode = PTOAutoSyncTailMode::kBarrierAll) {
  switch (mode) {
  case PTOAutoSyncTailMode::kSetWaitMte3ToSEvent0:
    set_flag(PIPE_MTE3, PIPE_S, EVENT_ID0);
    wait_flag(PIPE_MTE3, PIPE_S, EVENT_ID0);
    break;
  case PTOAutoSyncTailMode::kBarrierAll:
  default:
    pipe_barrier(PIPE_ALL);
    break;
  }
}

static __aicore__ void rope_qkv(__gm__ bfloat16_t* v1, __gm__ bfloat16_t* v2, __gm__ bfloat16_t* v3, __gm__ int32_t* v4, __gm__ float* v5, __gm__ int32_t* v6, __gm__ float* v7, __gm__ float* v8, __gm__ float* v9, __gm__ float* v10, __gm__ float* v11, __gm__ float* v12, __gm__ float* v13, int64_t v14, int32_t v15, int32_t v16) {
  SaturationMode v17 = SaturationMode::OFF;
  RoundMode v18 = RoundMode::CAST_ROUND;
  const float v19 = 0.0f;
  const int64_t v20 = 11;
  const int64_t v21 = 64;
  const int64_t v22 = 80;
  const int64_t v23 = 5;
  const int64_t v24 = 8;
  const int64_t v25 = 2;
  const int64_t v26 = 4;
  const int64_t v27 = 5120;
  const int64_t v28 = 16;
  const int64_t v29 = 1;
  const int64_t v30 = 128;
  const int64_t v31 = 9728;
  const int64_t v32 = 3712;
  const int64_t v33 = 3584;
  const int64_t v34 = 3328;
  const int64_t v35 = 3072;
  const int64_t v36 = 4096;
  const int64_t v37 = 2560;
  const int64_t v38 = 2048;
  const int64_t v39 = 1792;
  const int64_t v40 = 1536;
  const int64_t v41 = 1280;
  const int64_t v42 = 1024;
  const int64_t v43 = 9472;
  const int64_t v44 = 3840;
  const int64_t v45 = 768;
  const int64_t v46 = 512;
  const int64_t v47 = 256;
  const int64_t v48 = 0;
  using T = float;

  #if defined(__DAV_VEC__)
  set_mask_norm();
  set_vector_mask(-1, -1);
  size_t v49 = (size_t) v29;
  size_t v50 = (size_t) v48;
  size_t v51 = (size_t) v23;
  set_flag(PIPE_V, PIPE_MTE2, EVENT_ID0);
  set_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID0);
  set_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID1);
  set_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID2);
  set_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID3);
  set_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID5);
  for (size_t v52 = v50; v52 < ((size_t) v26); v52 += (size_t) v25) {
    int64_t v53 = (int64_t) v52;
    int64_t v54 = (int64_t) ((uint64_t) ((int64_t) v15) * (uint64_t) v26);
    int64_t v55 = (int64_t) ((uint64_t) v54 + (uint64_t) v53);
    int64_t v56 = v55 / v28;
    int64_t v57 = v55 % v28;
    int32_t v58 = v4[v57];
    float v59 = v5[v57];
    int64_t v60 = (int64_t) ((uint64_t) ((int64_t) v58) - (uint64_t) v29);
    int32_t v61 = v6[v57];
    int64_t v62 = (int64_t) v61;
    int64_t v63 = v62 / v30;
    int64_t v64 = (int64_t) ((uint64_t) v56 * (uint64_t) v30);
    int64_t v65 = (int64_t) ((uint64_t) v56 * (uint64_t) v28);
    float v66 = v9[(int64_t) ((uint64_t) v65 + (uint64_t) v57)];
    int64_t v67 = (int64_t) ((uint64_t) ((int64_t) (uint64_t) v14 + (uint64_t) ((int64_t) (uint64_t) ((int64_t) (uint64_t) ((int64_t) (uint64_t) v63 * (uint64_t) v24) + (uint64_t) v56) * (uint64_t) v30)) + (uint64_t) ((int64_t) (uint64_t) v62 - (uint64_t) ((int64_t) (uint64_t) v63 * (uint64_t) v30)));
    int64_t v68 = (int64_t) ((uint64_t) ((int64_t) (uint64_t) v57 * (uint64_t) v30) + (uint64_t) v65);
    int64_t v69 = (int64_t) ((uint64_t) v54 + (uint64_t) ((int64_t) (uint64_t) v53 + (uint64_t) v29));
    int64_t v70 = v69 / v28;
    int64_t v71 = v69 % v28;
    int32_t v72 = v4[v71];
    float v73 = v5[v71];
    int64_t v74 = (int64_t) ((uint64_t) ((int64_t) v72) - (uint64_t) v29);
    int32_t v75 = v6[v71];
    int64_t v76 = (int64_t) v75;
    int64_t v77 = v76 / v30;
    int64_t v78 = (int64_t) ((uint64_t) v70 * (uint64_t) v30);
    int64_t v79 = (int64_t) ((uint64_t) v70 * (uint64_t) v28);
    float v80 = v9[(int64_t) ((uint64_t) v79 + (uint64_t) v71)];
    int64_t v81 = (int64_t) ((uint64_t) ((int64_t) (uint64_t) v14 + (uint64_t) ((int64_t) (uint64_t) ((int64_t) (uint64_t) ((int64_t) (uint64_t) v77 * (uint64_t) v24) + (uint64_t) v70) * (uint64_t) v30)) + (uint64_t) ((int64_t) (uint64_t) v76 - (uint64_t) ((int64_t) (uint64_t) v77 * (uint64_t) v30)));
    int64_t v82 = (int64_t) ((uint64_t) ((int64_t) (uint64_t) v71 * (uint64_t) v30) + (uint64_t) v79);
    Tile<TileType::Vec, float, 1, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v83 = Tile<TileType::Vec, float, 1, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v29, v21);
    uint64_t v84 = (uint64_t) v48;
    TASSIGN(v83, v84);
    pto::Shape<1, 1, 1, 1, 64> v85 = pto::Shape<1, 1, 1, 1, 64>();
    pto::Stride<128, 128, 128, 128, 1> v86 = pto::Stride<128, 128, 128, 128, 1>();
    GlobalTensor<float, pto::Shape<1, 1, 1, 1, 64>, pto::Stride<128, 128, 128, 128, 1>, pto::Layout::ND> v87 = GlobalTensor<float, pto::Shape<1, 1, 1, 1, 64>, pto::Stride<128, 128, 128, 128, 1>, pto::Layout::ND>(v7 + (v48 + v60 * v30 + v48 * v29), v85, v86);
    wait_flag(PIPE_V, PIPE_MTE2, EVENT_ID0);
    TLOAD(v83, v87);
    Tile<TileType::Vec, float, 1, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v88 = Tile<TileType::Vec, float, 1, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v29, v21);
    uint64_t v89 = (uint64_t) v47;
    TASSIGN(v88, v89);
    pto::Shape<1, 1, 1, 1, 64> v90 = pto::Shape<1, 1, 1, 1, 64>();
    pto::Stride<128, 128, 128, 128, 1> v91 = pto::Stride<128, 128, 128, 128, 1>();
    GlobalTensor<float, pto::Shape<1, 1, 1, 1, 64>, pto::Stride<128, 128, 128, 128, 1>, pto::Layout::ND> v92 = GlobalTensor<float, pto::Shape<1, 1, 1, 1, 64>, pto::Stride<128, 128, 128, 128, 1>, pto::Layout::ND>(v7 + (v48 + v60 * v30 + v21 * v29), v90, v91);
    wait_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID0);
    TLOAD(v88, v92);
    Tile<TileType::Vec, float, 1, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v93 = Tile<TileType::Vec, float, 1, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v29, v21);
    uint64_t v94 = (uint64_t) v46;
    TASSIGN(v93, v94);
    pto::Shape<1, 1, 1, 1, 64> v95 = pto::Shape<1, 1, 1, 1, 64>();
    pto::Stride<128, 128, 128, 128, 1> v96 = pto::Stride<128, 128, 128, 128, 1>();
    GlobalTensor<float, pto::Shape<1, 1, 1, 1, 64>, pto::Stride<128, 128, 128, 128, 1>, pto::Layout::ND> v97 = GlobalTensor<float, pto::Shape<1, 1, 1, 1, 64>, pto::Stride<128, 128, 128, 128, 1>, pto::Layout::ND>(v8 + (v48 + v60 * v30 + v48 * v29), v95, v96);
    wait_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID1);
    TLOAD(v93, v97);
    Tile<TileType::Vec, float, 1, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v98 = Tile<TileType::Vec, float, 1, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v29, v21);
    uint64_t v99 = (uint64_t) v45;
    TASSIGN(v98, v99);
    pto::Shape<1, 1, 1, 1, 64> v100 = pto::Shape<1, 1, 1, 1, 64>();
    pto::Stride<128, 128, 128, 128, 1> v101 = pto::Stride<128, 128, 128, 128, 1>();
    GlobalTensor<float, pto::Shape<1, 1, 1, 1, 64>, pto::Stride<128, 128, 128, 128, 1>, pto::Layout::ND> v102 = GlobalTensor<float, pto::Shape<1, 1, 1, 1, 64>, pto::Stride<128, 128, 128, 128, 1>, pto::Layout::ND>(v8 + (v48 + v60 * v30 + v21 * v29), v100, v101);
    TLOAD(v98, v102);
    Tile<TileType::Vec, float, 1, 128, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v103 = Tile<TileType::Vec, float, 1, 128, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v29, v30);
    uint64_t v104 = (uint64_t) v44;
    TASSIGN(v103, v104);
    pto::Shape<1, 1, 1, 1, 128> v105 = pto::Shape<1, 1, 1, 1, 128>();
    pto::Stride<1024, 1024, 1024, 1024, 1> v106 = pto::Stride<1024, 1024, 1024, 1024, 1>();
    GlobalTensor<float, pto::Shape<1, 1, 1, 1, 128>, pto::Stride<1024, 1024, 1024, 1024, 1>, pto::Layout::ND> v107 = GlobalTensor<float, pto::Shape<1, 1, 1, 1, 128>, pto::Stride<1024, 1024, 1024, 1024, 1>, pto::Layout::ND>(v10 + (v48 + v57 * v42 + v64 * v29), v105, v106);
    wait_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID2);
    TLOAD(v103, v107);
    set_flag(PIPE_MTE2, PIPE_V, EVENT_ID0);
    Tile<TileType::Vec, float, 1, 128, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v108 = Tile<TileType::Vec, float, 1, 128, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v29, v30);
    uint64_t v109 = (uint64_t) v43;
    TASSIGN(v108, v109);
    pto::Shape<1, 1, 1, 1, 128> v110 = pto::Shape<1, 1, 1, 1, 128>();
    pto::Stride<1024, 1024, 1024, 1024, 1> v111 = pto::Stride<1024, 1024, 1024, 1024, 1>();
    GlobalTensor<float, pto::Shape<1, 1, 1, 1, 128>, pto::Stride<1024, 1024, 1024, 1024, 1>, pto::Layout::ND> v112 = GlobalTensor<float, pto::Shape<1, 1, 1, 1, 128>, pto::Stride<1024, 1024, 1024, 1024, 1>, pto::Layout::ND>(v11 + (v48 + v57 * v42 + v64 * v29), v110, v111);
    TLOAD(v108, v112);
    set_flag(PIPE_MTE2, PIPE_V, EVENT_ID1);
    Tile<TileType::Vec, float, 1, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v113 = Tile<TileType::Vec, float, 1, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v29, v21);
    uint64_t v114 = (uint64_t) v42;
    TASSIGN(v113, v114);
    pto::Shape<1, 1, 1, 1, 64> v115 = pto::Shape<1, 1, 1, 1, 64>();
    pto::Stride<128, 128, 128, 128, 1> v116 = pto::Stride<128, 128, 128, 128, 1>();
    GlobalTensor<float, pto::Shape<1, 1, 1, 1, 64>, pto::Stride<128, 128, 128, 128, 1>, pto::Layout::ND> v117 = GlobalTensor<float, pto::Shape<1, 1, 1, 1, 64>, pto::Stride<128, 128, 128, 128, 1>, pto::Layout::ND>(v7 + (v48 + v74 * v30 + v48 * v29), v115, v116);
    TLOAD(v113, v117);
    Tile<TileType::Vec, float, 1, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v118 = Tile<TileType::Vec, float, 1, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v29, v21);
    uint64_t v119 = (uint64_t) v41;
    TASSIGN(v118, v119);
    pto::Shape<1, 1, 1, 1, 64> v120 = pto::Shape<1, 1, 1, 1, 64>();
    pto::Stride<128, 128, 128, 128, 1> v121 = pto::Stride<128, 128, 128, 128, 1>();
    GlobalTensor<float, pto::Shape<1, 1, 1, 1, 64>, pto::Stride<128, 128, 128, 128, 1>, pto::Layout::ND> v122 = GlobalTensor<float, pto::Shape<1, 1, 1, 1, 64>, pto::Stride<128, 128, 128, 128, 1>, pto::Layout::ND>(v7 + (v48 + v74 * v30 + v21 * v29), v120, v121);
    TLOAD(v118, v122);
    Tile<TileType::Vec, float, 1, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v123 = Tile<TileType::Vec, float, 1, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v29, v21);
    uint64_t v124 = (uint64_t) v40;
    TASSIGN(v123, v124);
    pto::Shape<1, 1, 1, 1, 64> v125 = pto::Shape<1, 1, 1, 1, 64>();
    pto::Stride<128, 128, 128, 128, 1> v126 = pto::Stride<128, 128, 128, 128, 1>();
    GlobalTensor<float, pto::Shape<1, 1, 1, 1, 64>, pto::Stride<128, 128, 128, 128, 1>, pto::Layout::ND> v127 = GlobalTensor<float, pto::Shape<1, 1, 1, 1, 64>, pto::Stride<128, 128, 128, 128, 1>, pto::Layout::ND>(v8 + (v48 + v74 * v30 + v48 * v29), v125, v126);
    TLOAD(v123, v127);
    Tile<TileType::Vec, float, 1, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v128 = Tile<TileType::Vec, float, 1, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v29, v21);
    uint64_t v129 = (uint64_t) v39;
    TASSIGN(v128, v129);
    pto::Shape<1, 1, 1, 1, 64> v130 = pto::Shape<1, 1, 1, 1, 64>();
    pto::Stride<128, 128, 128, 128, 1> v131 = pto::Stride<128, 128, 128, 128, 1>();
    GlobalTensor<float, pto::Shape<1, 1, 1, 1, 64>, pto::Stride<128, 128, 128, 128, 1>, pto::Layout::ND> v132 = GlobalTensor<float, pto::Shape<1, 1, 1, 1, 64>, pto::Stride<128, 128, 128, 128, 1>, pto::Layout::ND>(v8 + (v48 + v74 * v30 + v21 * v29), v130, v131);
    TLOAD(v128, v132);
    Tile<TileType::Vec, float, 1, 128, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v133 = Tile<TileType::Vec, float, 1, 128, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v29, v30);
    uint64_t v134 = (uint64_t) v38;
    TASSIGN(v133, v134);
    pto::Shape<1, 1, 1, 1, 128> v135 = pto::Shape<1, 1, 1, 1, 128>();
    pto::Stride<1024, 1024, 1024, 1024, 1> v136 = pto::Stride<1024, 1024, 1024, 1024, 1>();
    GlobalTensor<float, pto::Shape<1, 1, 1, 1, 128>, pto::Stride<1024, 1024, 1024, 1024, 1>, pto::Layout::ND> v137 = GlobalTensor<float, pto::Shape<1, 1, 1, 1, 128>, pto::Stride<1024, 1024, 1024, 1024, 1>, pto::Layout::ND>(v10 + (v48 + v71 * v42 + v78 * v29), v135, v136);
    TLOAD(v133, v137);
    set_flag(PIPE_MTE2, PIPE_V, EVENT_ID3);
    Tile<TileType::Vec, float, 1, 128, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v138 = Tile<TileType::Vec, float, 1, 128, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v29, v30);
    uint64_t v139 = (uint64_t) v37;
    TASSIGN(v138, v139);
    pto::Shape<1, 1, 1, 1, 128> v140 = pto::Shape<1, 1, 1, 1, 128>();
    pto::Stride<1024, 1024, 1024, 1024, 1> v141 = pto::Stride<1024, 1024, 1024, 1024, 1>();
    GlobalTensor<float, pto::Shape<1, 1, 1, 1, 128>, pto::Stride<1024, 1024, 1024, 1024, 1>, pto::Layout::ND> v142 = GlobalTensor<float, pto::Shape<1, 1, 1, 1, 128>, pto::Stride<1024, 1024, 1024, 1024, 1>, pto::Layout::ND>(v11 + (v48 + v71 * v42 + v78 * v29), v140, v141);
    TLOAD(v138, v142);
    set_flag(PIPE_MTE2, PIPE_V, EVENT_ID4);
    Tile<TileType::Vec, float, 1, 128, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v143 = Tile<TileType::Vec, float, 1, 128, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v29, v30);
    uint64_t v144 = (uint64_t) v44;
    TASSIGN(v143, v144);
    wait_flag(PIPE_MTE2, PIPE_V, EVENT_ID0);
    TMULS(v143, v103, v66);
    Tile<TileType::Vec, float, 1, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v145 = Tile<TileType::Vec, float, 1, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v29, v21);
    uint64_t v146 = (uint64_t) v44;
    TASSIGN(v145, v146);
    Tile<TileType::Vec, float, 1, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v147 = Tile<TileType::Vec, float, 1, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v29, v21);
    uint64_t v148 = (uint64_t) v36;
    TASSIGN(v147, v148);
    Tile<TileType::Vec, float, 1, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v149 = Tile<TileType::Vec, float, 1, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v29, v21);
    uint64_t v150 = (uint64_t) v35;
    TASSIGN(v149, v150);
    pipe_barrier(PIPE_V);
    TEXTRACT(v145, v143, v48, v48);
    pipe_barrier(PIPE_V);
    TCOLEXPANDMUL(v149, v145, v83);
    Tile<TileType::Vec, float, 1, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v151 = Tile<TileType::Vec, float, 1, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v29, v21);
    uint64_t v152 = (uint64_t) v34;
    TASSIGN(v151, v152);
    TEXTRACT(v147, v143, v48, v21);
    pipe_barrier(PIPE_V);
    TCOLEXPANDMUL(v151, v147, v93);
    Tile<TileType::Vec, float, 1, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v153 = Tile<TileType::Vec, float, 1, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v29, v21);
    uint64_t v154 = (uint64_t) v35;
    TASSIGN(v153, v154);
    pipe_barrier(PIPE_V);
    TSUB(v153, v149, v151);
    Tile<TileType::Vec, float, 1, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v155 = Tile<TileType::Vec, float, 1, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v29, v21);
    uint64_t v156 = (uint64_t) v34;
    TASSIGN(v155, v156);
    pipe_barrier(PIPE_V);
    TCOLEXPANDMUL(v155, v147, v88);
    Tile<TileType::Vec, float, 1, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v157 = Tile<TileType::Vec, float, 1, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v29, v21);
    uint64_t v158 = (uint64_t) v44;
    TASSIGN(v157, v158);
    TCOLEXPANDMUL(v157, v145, v98);
    Tile<TileType::Vec, float, 1, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v159 = Tile<TileType::Vec, float, 1, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v29, v21);
    uint64_t v160 = (uint64_t) v44;
    TASSIGN(v159, v160);
    pipe_barrier(PIPE_V);
    TADD(v159, v155, v157);
    Tile<TileType::Vec, bfloat16_t, 1, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v161 = Tile<TileType::Vec, bfloat16_t, 1, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v29, v21);
    uint64_t v162 = (uint64_t) v33;
    TASSIGN(v161, v162);
    TCVT(v161, v153, v18, v17);
    set_flag(PIPE_V, PIPE_MTE3, EVENT_ID2);
    Tile<TileType::Vec, bfloat16_t, 1, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v163 = Tile<TileType::Vec, bfloat16_t, 1, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v29, v21);
    uint64_t v164 = (uint64_t) v32;
    TASSIGN(v163, v164);
    pipe_barrier(PIPE_V);
    TCVT(v163, v159, v18, v17);
    set_flag(PIPE_V, PIPE_MTE3, EVENT_ID3);
    Tile<TileType::Vec, float, 1, 128, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v165 = Tile<TileType::Vec, float, 1, 128, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v29, v30);
    uint64_t v166 = (uint64_t) v44;
    TASSIGN(v165, v166);
    pipe_barrier(PIPE_V);
    wait_flag(PIPE_MTE2, PIPE_V, EVENT_ID1);
    TMULS(v165, v108, v59);
    Tile<TileType::Vec, bfloat16_t, 1, 128, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v167 = Tile<TileType::Vec, bfloat16_t, 1, 128, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v29, v30);
    uint64_t v168 = (uint64_t) v35;
    TASSIGN(v167, v168);
    pipe_barrier(PIPE_V);
    TCVT(v167, v165, v18, v17);
    set_flag(PIPE_V, PIPE_MTE3, EVENT_ID4);
    set_flag(PIPE_V, PIPE_MTE2, EVENT_ID1);
    wait_flag(PIPE_V, PIPE_MTE2, EVENT_ID1);
    for (size_t v169 = v50; v169 < v51; v169 += v49) {
      int64_t v170 = (int64_t) v169;
      float v171 = v12[(int64_t) ((uint64_t) ((int64_t) (uint64_t) ((int64_t) (uint64_t) v56 * (uint64_t) v22) + (uint64_t) ((int64_t) (uint64_t) v57 * (uint64_t) v23)) + (uint64_t) v170)];
      Tile<TileType::Vec, float, 1, 128, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v172 = Tile<TileType::Vec, float, 1, 128, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v29, v30);
      uint64_t v173 = (uint64_t) v44;
      TASSIGN(v172, v173);
      pto::Shape<1, 1, 1, 1, 128> v174 = pto::Shape<1, 1, 1, 1, 128>();
      pto::Stride<5120, 5120, 5120, 5120, 1> v175 = pto::Stride<5120, 5120, 5120, 5120, 1>();
      GlobalTensor<float, pto::Shape<1, 1, 1, 1, 128>, pto::Stride<5120, 5120, 5120, 5120, 1>, pto::Layout::ND> v176 = GlobalTensor<float, pto::Shape<1, 1, 1, 1, 128>, pto::Stride<5120, 5120, 5120, 5120, 1>, pto::Layout::ND>(v13 + (v48 + v57 * v27 + (int64_t) ((uint64_t) ((int64_t) (uint64_t) ((int64_t) (uint64_t) v56 * (uint64_t) v23) + (uint64_t) v170) * (uint64_t) v30) * v29), v174, v175);
      wait_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID3);
      TLOAD(v172, v176);
      set_flag(PIPE_MTE2, PIPE_V, EVENT_ID2);
      Tile<TileType::Vec, float, 1, 128, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v177 = Tile<TileType::Vec, float, 1, 128, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v29, v30);
      uint64_t v178 = (uint64_t) v44;
      TASSIGN(v177, v178);
      wait_flag(PIPE_MTE2, PIPE_V, EVENT_ID2);
      TMULS(v177, v172, v171);
      Tile<TileType::Vec, float, 1, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v179 = Tile<TileType::Vec, float, 1, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v29, v21);
      uint64_t v180 = (uint64_t) v44;
      TASSIGN(v179, v180);
      Tile<TileType::Vec, float, 1, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v181 = Tile<TileType::Vec, float, 1, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v29, v21);
      uint64_t v182 = (uint64_t) v36;
      TASSIGN(v181, v182);
      Tile<TileType::Vec, float, 1, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v183 = Tile<TileType::Vec, float, 1, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v29, v21);
      uint64_t v184 = (uint64_t) v43;
      TASSIGN(v183, v184);
      pipe_barrier(PIPE_V);
      TEXTRACT(v179, v177, v48, v48);
      pipe_barrier(PIPE_V);
      TCOLEXPANDMUL(v183, v179, v83);
      Tile<TileType::Vec, float, 1, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v185 = Tile<TileType::Vec, float, 1, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v29, v21);
      uint64_t v186 = (uint64_t) v34;
      TASSIGN(v185, v186);
      TEXTRACT(v181, v177, v48, v21);
      pipe_barrier(PIPE_V);
      TCOLEXPANDMUL(v185, v181, v93);
      Tile<TileType::Vec, float, 1, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v187 = Tile<TileType::Vec, float, 1, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v29, v21);
      uint64_t v188 = (uint64_t) v43;
      TASSIGN(v187, v188);
      pipe_barrier(PIPE_V);
      TSUB(v187, v183, v185);
      Tile<TileType::Vec, float, 1, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v189 = Tile<TileType::Vec, float, 1, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v29, v21);
      uint64_t v190 = (uint64_t) v34;
      TASSIGN(v189, v190);
      pipe_barrier(PIPE_V);
      TCOLEXPANDMUL(v189, v181, v88);
      Tile<TileType::Vec, float, 1, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v191 = Tile<TileType::Vec, float, 1, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v29, v21);
      uint64_t v192 = (uint64_t) v44;
      TASSIGN(v191, v192);
      TCOLEXPANDMUL(v191, v179, v98);
      Tile<TileType::Vec, float, 1, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v193 = Tile<TileType::Vec, float, 1, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v29, v21);
      uint64_t v194 = (uint64_t) v44;
      TASSIGN(v193, v194);
      pipe_barrier(PIPE_V);
      TADD(v193, v189, v191);
      Tile<TileType::Vec, bfloat16_t, 1, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v195 = Tile<TileType::Vec, bfloat16_t, 1, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v29, v21);
      uint64_t v196 = (uint64_t) v43;
      TASSIGN(v195, v196);
      TCVT(v195, v187, v18, v17);
      set_flag(PIPE_V, PIPE_MTE3, EVENT_ID0);
      Tile<TileType::Vec, bfloat16_t, 1, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v197 = Tile<TileType::Vec, bfloat16_t, 1, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v29, v21);
      uint64_t v198 = (uint64_t) v44;
      TASSIGN(v197, v198);
      pipe_barrier(PIPE_V);
      TCVT(v197, v193, v18, v17);
      set_flag(PIPE_V, PIPE_MTE3, EVENT_ID1);
      int64_t v199 = (int64_t) ((uint64_t) v68 + (uint64_t) v170);
      pto::Shape<1, 1, 1, 1, 64> v200 = pto::Shape<1, 1, 1, 1, 64>();
      pto::Stride<128, 128, 128, 128, 1> v201 = pto::Stride<128, 128, 128, 128, 1>();
      GlobalTensor<bfloat16_t, pto::Shape<1, 1, 1, 1, 64>, pto::Stride<128, 128, 128, 128, 1>, pto::Layout::ND> v202 = GlobalTensor<bfloat16_t, pto::Shape<1, 1, 1, 1, 64>, pto::Stride<128, 128, 128, 128, 1>, pto::Layout::ND>(v1 + (v48 + v199 * v30 + v48 * v29), v200, v201);
      wait_flag(PIPE_V, PIPE_MTE3, EVENT_ID0);
      TSTORE(v202, v195);
      pto::Shape<1, 1, 1, 1, 64> v203 = pto::Shape<1, 1, 1, 1, 64>();
      pto::Stride<128, 128, 128, 128, 1> v204 = pto::Stride<128, 128, 128, 128, 1>();
      GlobalTensor<bfloat16_t, pto::Shape<1, 1, 1, 1, 64>, pto::Stride<128, 128, 128, 128, 1>, pto::Layout::ND> v205 = GlobalTensor<bfloat16_t, pto::Shape<1, 1, 1, 1, 64>, pto::Stride<128, 128, 128, 128, 1>, pto::Layout::ND>(v1 + (v48 + v199 * v30 + v21 * v29), v203, v204);
      pipe_barrier(PIPE_MTE3);
      wait_flag(PIPE_V, PIPE_MTE3, EVENT_ID1);
      TSTORE(v205, v197);
      set_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID3);
    };
    set_flag(PIPE_MTE3, PIPE_V, EVENT_ID0);
    Tile<TileType::Vec, float, 11, 128, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v206 = Tile<TileType::Vec, float, 11, 128, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v20, v30);
    uint64_t v207 = (uint64_t) v44;
    TASSIGN(v206, v207);
    wait_flag(PIPE_MTE3, PIPE_V, EVENT_ID0);
    pipe_barrier(PIPE_V);
    TEXPANDS(v206, v19);
    Tile<TileType::Vec, bfloat16_t, 11, 128, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v208 = Tile<TileType::Vec, bfloat16_t, 11, 128, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v20, v30);
    uint64_t v209 = (uint64_t) v43;
    TASSIGN(v208, v209);
    pipe_barrier(PIPE_V);
    TCVT(v208, v206, v18, v17);
    set_flag(PIPE_V, PIPE_MTE3, EVENT_ID5);
    Tile<TileType::Vec, float, 1, 128, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v210 = Tile<TileType::Vec, float, 1, 128, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v29, v30);
    uint64_t v211 = (uint64_t) v44;
    TASSIGN(v210, v211);
    pipe_barrier(PIPE_V);
    wait_flag(PIPE_MTE2, PIPE_V, EVENT_ID3);
    TMULS(v210, v133, v80);
    Tile<TileType::Vec, float, 1, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v212 = Tile<TileType::Vec, float, 1, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v29, v21);
    uint64_t v213 = (uint64_t) v44;
    TASSIGN(v212, v213);
    Tile<TileType::Vec, float, 1, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v214 = Tile<TileType::Vec, float, 1, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v29, v21);
    uint64_t v215 = (uint64_t) v36;
    TASSIGN(v214, v215);
    Tile<TileType::Vec, float, 1, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v216 = Tile<TileType::Vec, float, 1, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v29, v21);
    uint64_t v217 = (uint64_t) v38;
    TASSIGN(v216, v217);
    pipe_barrier(PIPE_V);
    TEXTRACT(v212, v210, v48, v48);
    pipe_barrier(PIPE_V);
    TCOLEXPANDMUL(v216, v212, v113);
    Tile<TileType::Vec, float, 1, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v218 = Tile<TileType::Vec, float, 1, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v29, v21);
    uint64_t v219 = (uint64_t) v48;
    TASSIGN(v218, v219);
    TEXTRACT(v214, v210, v48, v21);
    pipe_barrier(PIPE_V);
    TCOLEXPANDMUL(v218, v214, v123);
    Tile<TileType::Vec, float, 1, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v220 = Tile<TileType::Vec, float, 1, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v29, v21);
    uint64_t v221 = (uint64_t) v38;
    TASSIGN(v220, v221);
    pipe_barrier(PIPE_V);
    TSUB(v220, v216, v218);
    Tile<TileType::Vec, float, 1, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v222 = Tile<TileType::Vec, float, 1, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v29, v21);
    uint64_t v223 = (uint64_t) v48;
    TASSIGN(v222, v223);
    pipe_barrier(PIPE_V);
    TCOLEXPANDMUL(v222, v214, v118);
    Tile<TileType::Vec, float, 1, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v224 = Tile<TileType::Vec, float, 1, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v29, v21);
    uint64_t v225 = (uint64_t) v44;
    TASSIGN(v224, v225);
    TCOLEXPANDMUL(v224, v212, v128);
    Tile<TileType::Vec, float, 1, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v226 = Tile<TileType::Vec, float, 1, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v29, v21);
    uint64_t v227 = (uint64_t) v44;
    TASSIGN(v226, v227);
    pipe_barrier(PIPE_V);
    TADD(v226, v222, v224);
    Tile<TileType::Vec, bfloat16_t, 1, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v228 = Tile<TileType::Vec, bfloat16_t, 1, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v29, v21);
    uint64_t v229 = (uint64_t) v47;
    TASSIGN(v228, v229);
    TCVT(v228, v220, v18, v17);
    set_flag(PIPE_V, PIPE_MTE3, EVENT_ID0);
    Tile<TileType::Vec, bfloat16_t, 1, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v230 = Tile<TileType::Vec, bfloat16_t, 1, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v29, v21);
    uint64_t v231 = (uint64_t) v46;
    TASSIGN(v230, v231);
    pipe_barrier(PIPE_V);
    TCVT(v230, v226, v18, v17);
    set_flag(PIPE_V, PIPE_MTE3, EVENT_ID1);
    Tile<TileType::Vec, float, 1, 128, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v232 = Tile<TileType::Vec, float, 1, 128, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v29, v30);
    uint64_t v233 = (uint64_t) v44;
    TASSIGN(v232, v233);
    pipe_barrier(PIPE_V);
    wait_flag(PIPE_MTE2, PIPE_V, EVENT_ID4);
    TMULS(v232, v138, v73);
    Tile<TileType::Vec, bfloat16_t, 1, 128, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v234 = Tile<TileType::Vec, bfloat16_t, 1, 128, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v29, v30);
    uint64_t v235 = (uint64_t) v38;
    TASSIGN(v234, v235);
    pipe_barrier(PIPE_V);
    TCVT(v234, v232, v18, v17);
    Tile<TileType::Vec, float, 11, 128, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v236 = Tile<TileType::Vec, float, 11, 128, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v20, v30);
    uint64_t v237 = (uint64_t) v44;
    TASSIGN(v236, v237);
    pipe_barrier(PIPE_V);
    TEXPANDS(v236, v19);
    Tile<TileType::Vec, bfloat16_t, 11, 128, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v238 = Tile<TileType::Vec, bfloat16_t, 11, 128, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v20, v30);
    uint64_t v239 = (uint64_t) v44;
    TASSIGN(v238, v239);
    pipe_barrier(PIPE_V);
    TCVT(v238, v236, v18, v17);
    pto::Shape<1, 1, 1, 1, 64> v240 = pto::Shape<1, 1, 1, 1, 64>();
    pto::Stride<128, 128, 128, 128, 1> v241 = pto::Stride<128, 128, 128, 128, 1>();
    GlobalTensor<bfloat16_t, pto::Shape<1, 1, 1, 1, 64>, pto::Stride<128, 128, 128, 128, 1>, pto::Layout::ND> v242 = GlobalTensor<bfloat16_t, pto::Shape<1, 1, 1, 1, 64>, pto::Stride<128, 128, 128, 128, 1>, pto::Layout::ND>(v2 + (v48 + v67 * v30 + v48 * v29), v240, v241);
    wait_flag(PIPE_V, PIPE_MTE3, EVENT_ID2);
    TSTORE(v242, v161);
    pto::Shape<1, 1, 1, 1, 64> v243 = pto::Shape<1, 1, 1, 1, 64>();
    pto::Stride<128, 128, 128, 128, 1> v244 = pto::Stride<128, 128, 128, 128, 1>();
    GlobalTensor<bfloat16_t, pto::Shape<1, 1, 1, 1, 64>, pto::Stride<128, 128, 128, 128, 1>, pto::Layout::ND> v245 = GlobalTensor<bfloat16_t, pto::Shape<1, 1, 1, 1, 64>, pto::Stride<128, 128, 128, 128, 1>, pto::Layout::ND>(v2 + (v48 + v67 * v30 + v21 * v29), v243, v244);
    pipe_barrier(PIPE_MTE3);
    wait_flag(PIPE_V, PIPE_MTE3, EVENT_ID3);
    TSTORE(v245, v163);
    pto::Shape<1, 1, 1, 1, 128> v246 = pto::Shape<1, 1, 1, 1, 128>();
    pto::Stride<128, 128, 128, 128, 1> v247 = pto::Stride<128, 128, 128, 128, 1>();
    GlobalTensor<bfloat16_t, pto::Shape<1, 1, 1, 1, 128>, pto::Stride<128, 128, 128, 128, 1>, pto::Layout::ND> v248 = GlobalTensor<bfloat16_t, pto::Shape<1, 1, 1, 1, 128>, pto::Stride<128, 128, 128, 128, 1>, pto::Layout::ND>(v3 + (v48 + v67 * v30 + v48 * v29), v246, v247);
    wait_flag(PIPE_V, PIPE_MTE3, EVENT_ID4);
    TSTORE(v248, v167);
    pto::Shape<1, 1, 1, 11, 128> v249 = pto::Shape<1, 1, 1, 11, 128>();
    pto::Stride<1408, 1408, 1408, 128, 1> v250 = pto::Stride<1408, 1408, 1408, 128, 1>();
    GlobalTensor<bfloat16_t, pto::Shape<1, 1, 1, 11, 128>, pto::Stride<1408, 1408, 1408, 128, 1>, pto::Layout::ND> v251 = GlobalTensor<bfloat16_t, pto::Shape<1, 1, 1, 11, 128>, pto::Stride<1408, 1408, 1408, 128, 1>, pto::Layout::ND>(v1 + (v48 + (int64_t) ((uint64_t) v68 + (uint64_t) v23) * v30 + v48 * v29), v249, v250);
    wait_flag(PIPE_V, PIPE_MTE3, EVENT_ID5);
    TSTORE(v251, v208);
    set_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID4);
    wait_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID4);
    for (size_t v252 = v50; v252 < v51; v252 += v49) {
      int64_t v253 = (int64_t) v252;
      float v254 = v12[(int64_t) ((uint64_t) ((int64_t) (uint64_t) ((int64_t) (uint64_t) v70 * (uint64_t) v22) + (uint64_t) ((int64_t) (uint64_t) v71 * (uint64_t) v23)) + (uint64_t) v253)];
      Tile<TileType::Vec, float, 1, 128, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v255 = Tile<TileType::Vec, float, 1, 128, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v29, v30);
      uint64_t v256 = (uint64_t) v43;
      TASSIGN(v255, v256);
      pto::Shape<1, 1, 1, 1, 128> v257 = pto::Shape<1, 1, 1, 1, 128>();
      pto::Stride<5120, 5120, 5120, 5120, 1> v258 = pto::Stride<5120, 5120, 5120, 5120, 1>();
      GlobalTensor<float, pto::Shape<1, 1, 1, 1, 128>, pto::Stride<5120, 5120, 5120, 5120, 1>, pto::Layout::ND> v259 = GlobalTensor<float, pto::Shape<1, 1, 1, 1, 128>, pto::Stride<5120, 5120, 5120, 5120, 1>, pto::Layout::ND>(v13 + (v48 + v71 * v27 + (int64_t) ((uint64_t) ((int64_t) (uint64_t) ((int64_t) (uint64_t) v70 * (uint64_t) v23) + (uint64_t) v253) * (uint64_t) v30) * v29), v257, v258);
      wait_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID5);
      TLOAD(v255, v259);
      set_flag(PIPE_MTE2, PIPE_V, EVENT_ID5);
      Tile<TileType::Vec, float, 1, 128, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v260 = Tile<TileType::Vec, float, 1, 128, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v29, v30);
      uint64_t v261 = (uint64_t) v43;
      TASSIGN(v260, v261);
      wait_flag(PIPE_MTE2, PIPE_V, EVENT_ID5);
      TMULS(v260, v255, v254);
      Tile<TileType::Vec, float, 1, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v262 = Tile<TileType::Vec, float, 1, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v29, v21);
      uint64_t v263 = (uint64_t) v43;
      TASSIGN(v262, v263);
      Tile<TileType::Vec, float, 1, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v264 = Tile<TileType::Vec, float, 1, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v29, v21);
      uint64_t v265 = (uint64_t) v31;
      TASSIGN(v264, v265);
      Tile<TileType::Vec, float, 1, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v266 = Tile<TileType::Vec, float, 1, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v29, v21);
      uint64_t v267 = (uint64_t) v37;
      TASSIGN(v266, v267);
      pipe_barrier(PIPE_V);
      TEXTRACT(v262, v260, v48, v48);
      pipe_barrier(PIPE_V);
      TCOLEXPANDMUL(v266, v262, v113);
      Tile<TileType::Vec, float, 1, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v268 = Tile<TileType::Vec, float, 1, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v29, v21);
      uint64_t v269 = (uint64_t) v48;
      TASSIGN(v268, v269);
      TEXTRACT(v264, v260, v48, v21);
      pipe_barrier(PIPE_V);
      TCOLEXPANDMUL(v268, v264, v123);
      Tile<TileType::Vec, float, 1, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v270 = Tile<TileType::Vec, float, 1, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v29, v21);
      uint64_t v271 = (uint64_t) v37;
      TASSIGN(v270, v271);
      pipe_barrier(PIPE_V);
      TSUB(v270, v266, v268);
      Tile<TileType::Vec, float, 1, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v272 = Tile<TileType::Vec, float, 1, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v29, v21);
      uint64_t v273 = (uint64_t) v48;
      TASSIGN(v272, v273);
      pipe_barrier(PIPE_V);
      TCOLEXPANDMUL(v272, v264, v118);
      Tile<TileType::Vec, float, 1, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v274 = Tile<TileType::Vec, float, 1, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v29, v21);
      uint64_t v275 = (uint64_t) v43;
      TASSIGN(v274, v275);
      TCOLEXPANDMUL(v274, v262, v128);
      Tile<TileType::Vec, float, 1, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v276 = Tile<TileType::Vec, float, 1, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v29, v21);
      uint64_t v277 = (uint64_t) v43;
      TASSIGN(v276, v277);
      pipe_barrier(PIPE_V);
      TADD(v276, v272, v274);
      Tile<TileType::Vec, bfloat16_t, 1, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v278 = Tile<TileType::Vec, bfloat16_t, 1, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v29, v21);
      uint64_t v279 = (uint64_t) v37;
      TASSIGN(v278, v279);
      TCVT(v278, v270, v18, v17);
      set_flag(PIPE_V, PIPE_MTE3, EVENT_ID6);
      Tile<TileType::Vec, bfloat16_t, 1, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v280 = Tile<TileType::Vec, bfloat16_t, 1, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v29, v21);
      uint64_t v281 = (uint64_t) v43;
      TASSIGN(v280, v281);
      pipe_barrier(PIPE_V);
      TCVT(v280, v276, v18, v17);
      set_flag(PIPE_V, PIPE_MTE3, EVENT_ID7);
      int64_t v282 = (int64_t) ((uint64_t) v82 + (uint64_t) v253);
      pto::Shape<1, 1, 1, 1, 64> v283 = pto::Shape<1, 1, 1, 1, 64>();
      pto::Stride<128, 128, 128, 128, 1> v284 = pto::Stride<128, 128, 128, 128, 1>();
      GlobalTensor<bfloat16_t, pto::Shape<1, 1, 1, 1, 64>, pto::Stride<128, 128, 128, 128, 1>, pto::Layout::ND> v285 = GlobalTensor<bfloat16_t, pto::Shape<1, 1, 1, 1, 64>, pto::Stride<128, 128, 128, 128, 1>, pto::Layout::ND>(v1 + (v48 + v282 * v30 + v48 * v29), v283, v284);
      wait_flag(PIPE_V, PIPE_MTE3, EVENT_ID6);
      TSTORE(v285, v278);
      pto::Shape<1, 1, 1, 1, 64> v286 = pto::Shape<1, 1, 1, 1, 64>();
      pto::Stride<128, 128, 128, 128, 1> v287 = pto::Stride<128, 128, 128, 128, 1>();
      GlobalTensor<bfloat16_t, pto::Shape<1, 1, 1, 1, 64>, pto::Stride<128, 128, 128, 128, 1>, pto::Layout::ND> v288 = GlobalTensor<bfloat16_t, pto::Shape<1, 1, 1, 1, 64>, pto::Stride<128, 128, 128, 128, 1>, pto::Layout::ND>(v1 + (v48 + v282 * v30 + v21 * v29), v286, v287);
      pipe_barrier(PIPE_MTE3);
      wait_flag(PIPE_V, PIPE_MTE3, EVENT_ID7);
      TSTORE(v288, v280);
      set_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID5);
    };
    set_flag(PIPE_V, PIPE_MTE2, EVENT_ID0);
    pto::Shape<1, 1, 1, 1, 64> v289 = pto::Shape<1, 1, 1, 1, 64>();
    pto::Stride<128, 128, 128, 128, 1> v290 = pto::Stride<128, 128, 128, 128, 1>();
    GlobalTensor<bfloat16_t, pto::Shape<1, 1, 1, 1, 64>, pto::Stride<128, 128, 128, 128, 1>, pto::Layout::ND> v291 = GlobalTensor<bfloat16_t, pto::Shape<1, 1, 1, 1, 64>, pto::Stride<128, 128, 128, 128, 1>, pto::Layout::ND>(v2 + (v48 + v81 * v30 + v48 * v29), v289, v290);
    pipe_barrier(PIPE_MTE3);
    wait_flag(PIPE_V, PIPE_MTE3, EVENT_ID0);
    TSTORE(v291, v228);
    set_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID0);
    pto::Shape<1, 1, 1, 1, 64> v292 = pto::Shape<1, 1, 1, 1, 64>();
    pto::Stride<128, 128, 128, 128, 1> v293 = pto::Stride<128, 128, 128, 128, 1>();
    GlobalTensor<bfloat16_t, pto::Shape<1, 1, 1, 1, 64>, pto::Stride<128, 128, 128, 128, 1>, pto::Layout::ND> v294 = GlobalTensor<bfloat16_t, pto::Shape<1, 1, 1, 1, 64>, pto::Stride<128, 128, 128, 128, 1>, pto::Layout::ND>(v2 + (v48 + v81 * v30 + v21 * v29), v292, v293);
    pipe_barrier(PIPE_MTE3);
    wait_flag(PIPE_V, PIPE_MTE3, EVENT_ID1);
    TSTORE(v294, v230);
    set_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID1);
    pto::Shape<1, 1, 1, 1, 128> v295 = pto::Shape<1, 1, 1, 1, 128>();
    pto::Stride<128, 128, 128, 128, 1> v296 = pto::Stride<128, 128, 128, 128, 1>();
    GlobalTensor<bfloat16_t, pto::Shape<1, 1, 1, 1, 128>, pto::Stride<128, 128, 128, 128, 1>, pto::Layout::ND> v297 = GlobalTensor<bfloat16_t, pto::Shape<1, 1, 1, 1, 128>, pto::Stride<128, 128, 128, 128, 1>, pto::Layout::ND>(v3 + (v48 + v81 * v30 + v48 * v29), v295, v296);
    pipe_barrier(PIPE_ALL);
    TSTORE(v297, v234);
    pto::Shape<1, 1, 1, 11, 128> v298 = pto::Shape<1, 1, 1, 11, 128>();
    pto::Stride<1408, 1408, 1408, 128, 1> v299 = pto::Stride<1408, 1408, 1408, 128, 1>();
    GlobalTensor<bfloat16_t, pto::Shape<1, 1, 1, 11, 128>, pto::Stride<1408, 1408, 1408, 128, 1>, pto::Layout::ND> v300 = GlobalTensor<bfloat16_t, pto::Shape<1, 1, 1, 11, 128>, pto::Stride<1408, 1408, 1408, 128, 1>, pto::Layout::ND>(v1 + (v48 + (int64_t) ((uint64_t) v82 + (uint64_t) v23) * v30 + v48 * v29), v298, v299);
    pipe_barrier(PIPE_ALL);
    TSTORE(v300, v238);
    set_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID2);
  }
  wait_flag(PIPE_V, PIPE_MTE2, EVENT_ID0);
  wait_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID0);
  wait_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID1);
  wait_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID2);
  wait_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID3);
  wait_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID5);
  #endif // __DAV_VEC__

  ptoas_auto_sync_tail(PTOAutoSyncTailMode::kBarrierAll);
  return;
}
// --- Kernel entry point ---
extern "C" __aicore__ __attribute__((always_inline)) void kernel_entry(__gm__ int64_t* args)
{
    // Read logical SPMD block identity from runtime dispatch payload
    int32_t __pypto_spmd_block_idx = get_block_idx(args);
    int32_t __pypto_spmd_block_num = get_block_num(args);

    // Unpack tensor: all_q_padded_inline257__ssa_v0
    __gm__ Tensor* all_q_padded_inline257__ssa_v0_tensor = reinterpret_cast<__gm__ Tensor*>(args[0]);
    __gm__ bfloat16_t* all_q_padded_inline257__ssa_v0 = reinterpret_cast<__gm__ bfloat16_t*>(all_q_padded_inline257__ssa_v0_tensor->buffer.addr) + all_q_padded_inline257__ssa_v0_tensor->start_offset;

    // Unpack tensor: k_cache__ssa_v0
    __gm__ Tensor* k_cache__ssa_v0_tensor = reinterpret_cast<__gm__ Tensor*>(args[1]);
    __gm__ bfloat16_t* k_cache__ssa_v0 = reinterpret_cast<__gm__ bfloat16_t*>(k_cache__ssa_v0_tensor->buffer.addr) + k_cache__ssa_v0_tensor->start_offset;

    // Unpack tensor: v_cache__ssa_v0
    __gm__ Tensor* v_cache__ssa_v0_tensor = reinterpret_cast<__gm__ Tensor*>(args[2]);
    __gm__ bfloat16_t* v_cache__ssa_v0 = reinterpret_cast<__gm__ bfloat16_t*>(v_cache__ssa_v0_tensor->buffer.addr) + v_cache__ssa_v0_tensor->start_offset;

    // Unpack tensor: seq_lens__ssa_v0
    __gm__ Tensor* seq_lens__ssa_v0_tensor = reinterpret_cast<__gm__ Tensor*>(args[3]);
    __gm__ int32_t* seq_lens__ssa_v0 = reinterpret_cast<__gm__ int32_t*>(seq_lens__ssa_v0_tensor->buffer.addr) + seq_lens__ssa_v0_tensor->start_offset;

    // Unpack tensor: inv_rms_states_inline449__ssa_v1
    __gm__ Tensor* inv_rms_states_inline449__ssa_v1_tensor = reinterpret_cast<__gm__ Tensor*>(args[4]);
    __gm__ float* inv_rms_states_inline449__ssa_v1 = reinterpret_cast<__gm__ float*>(inv_rms_states_inline449__ssa_v1_tensor->buffer.addr) + inv_rms_states_inline449__ssa_v1_tensor->start_offset;

    // Unpack tensor: slot_mapping__ssa_v0
    __gm__ Tensor* slot_mapping__ssa_v0_tensor = reinterpret_cast<__gm__ Tensor*>(args[5]);
    __gm__ int32_t* slot_mapping__ssa_v0 = reinterpret_cast<__gm__ int32_t*>(slot_mapping__ssa_v0_tensor->buffer.addr) + slot_mapping__ssa_v0_tensor->start_offset;

    // Unpack tensor: rope_cos__ssa_v0
    __gm__ Tensor* rope_cos__ssa_v0_tensor = reinterpret_cast<__gm__ Tensor*>(args[6]);
    __gm__ float* rope_cos__ssa_v0 = reinterpret_cast<__gm__ float*>(rope_cos__ssa_v0_tensor->buffer.addr) + rope_cos__ssa_v0_tensor->start_offset;

    // Unpack tensor: rope_sin__ssa_v0
    __gm__ Tensor* rope_sin__ssa_v0_tensor = reinterpret_cast<__gm__ Tensor*>(args[7]);
    __gm__ float* rope_sin__ssa_v0 = reinterpret_cast<__gm__ float*>(rope_sin__ssa_v0_tensor->buffer.addr) + rope_sin__ssa_v0_tensor->start_offset;

    // Unpack tensor: k_inv_states_inline204__ssa_v8
    __gm__ Tensor* k_inv_states_inline204__ssa_v8_tensor = reinterpret_cast<__gm__ Tensor*>(args[8]);
    __gm__ float* k_inv_states_inline204__ssa_v8 = reinterpret_cast<__gm__ float*>(k_inv_states_inline204__ssa_v8_tensor->buffer.addr) + k_inv_states_inline204__ssa_v8_tensor->start_offset;

    // Unpack tensor: k_proj_norm_inline171__ssa_v8
    __gm__ Tensor* k_proj_norm_inline171__ssa_v8_tensor = reinterpret_cast<__gm__ Tensor*>(args[9]);
    __gm__ float* k_proj_norm_inline171__ssa_v8 = reinterpret_cast<__gm__ float*>(k_proj_norm_inline171__ssa_v8_tensor->buffer.addr) + k_proj_norm_inline171__ssa_v8_tensor->start_offset;

    // Unpack tensor: v_proj_inline241__rv_v3
    __gm__ Tensor* v_proj_inline241__rv_v3_tensor = reinterpret_cast<__gm__ Tensor*>(args[10]);
    __gm__ float* v_proj_inline241__rv_v3 = reinterpret_cast<__gm__ float*>(v_proj_inline241__rv_v3_tensor->buffer.addr) + v_proj_inline241__rv_v3_tensor->start_offset;

    // Unpack tensor: q_inv_states_inline168__ssa_v8
    __gm__ Tensor* q_inv_states_inline168__ssa_v8_tensor = reinterpret_cast<__gm__ Tensor*>(args[11]);
    __gm__ float* q_inv_states_inline168__ssa_v8 = reinterpret_cast<__gm__ float*>(q_inv_states_inline168__ssa_v8_tensor->buffer.addr) + q_inv_states_inline168__ssa_v8_tensor->start_offset;

    // Unpack tensor: q_proj_norm_inline375__ssa_v8
    __gm__ Tensor* q_proj_norm_inline375__ssa_v8_tensor = reinterpret_cast<__gm__ Tensor*>(args[12]);
    __gm__ float* q_proj_norm_inline375__ssa_v8 = reinterpret_cast<__gm__ float*>(q_proj_norm_inline375__ssa_v8_tensor->buffer.addr) + q_proj_norm_inline375__ssa_v8_tensor->start_offset;

    // Unpack scalar: layer_cache_base_inline156__ssa_v0
    union { uint64_t u64; int64_t val; } layer_cache_base_inline156__ssa_v0_conv;
    layer_cache_base_inline156__ssa_v0_conv.u64 = args[13];
    int64_t layer_cache_base_inline156__ssa_v0 = layer_cache_base_inline156__ssa_v0_conv.val;

    // Forward to ptoas-generated function
    rope_qkv(all_q_padded_inline257__ssa_v0, k_cache__ssa_v0, v_cache__ssa_v0, seq_lens__ssa_v0, inv_rms_states_inline449__ssa_v1, slot_mapping__ssa_v0, rope_cos__ssa_v0, rope_sin__ssa_v0, k_inv_states_inline204__ssa_v8, k_proj_norm_inline171__ssa_v8, v_proj_inline241__rv_v3, q_inv_states_inline168__ssa_v8, q_proj_norm_inline375__ssa_v8, layer_cache_base_inline156__ssa_v0, __pypto_spmd_block_idx, __pypto_spmd_block_num);
}
