/* Reproducible, read-only extraction of the two investigation slices. */
const fs = require('node:fs');
const path = require('node:path');
const base = path.resolve(__dirname, '../../Data/DeepseekV4');
const jit = '_jit_l3_decode_csa_20260903_010617';
const definitions = {
  a2a: ['qk_pv_aic_spmd(r2t53)', 'csa_merge_pack_publish_spmd(r2t55)', 'o_group_a2a_wait(r2t56)', 'o_group_a2a_gather_spmd(r2t57)', 'o_group_a2a_complete(r2t58)', 'tp_o_a_spmd(r3t18)'],
  token: ['cp_token_allgather_push_spmd(r2t12)', 'cp_token_allgather_payload_wait(r2t13)', 'cp_token_allgather_readback_spmd(r2t14)', 'cp_token_allgather_readback_wait(r2t15)', 'cp_token_allgather_retire(r2t16)', 'kv_score_proj_spmd(r2t23)'],
};
const result = {run: jit.slice(1), generatedFrom: 'Repository traceEvents (pid=4 worker; pid=3 scheduler). No readiness inferred.', cases: {}, sources: {}, passes: []};
for (const key of Object.keys(definitions)) result.cases[key] = {ranks: []};
for (let rank = 0; rank < 2; rank++) {
  const rel = `${jit}/dfx_outputs/rank${rank}/d0`;
  const traceFile = fs.readdirSync(path.join(base, rel)).find(f => /^merged_swimlane.*json$/.test(f));
  const events = JSON.parse(fs.readFileSync(path.join(base, rel, traceFile))).traceEvents;
  const lanes = new Map(events.filter(e => e.name === 'thread_name' && e.pid === 4).map(e => [e.tid, e.args.name]));
  for (const [key, names] of Object.entries(definitions)) {
    result.cases[key].ranks[rank] = {trace: `${rel}/${traceFile}`, tasks: names.map(name => {
      const workers = events.filter(e => e.ph === 'X' && e.pid === 4 && e.name === name);
      if (!workers.length) throw Error(`Missing ${rank} ${name}`);
      const first = workers.reduce((a,b) => a.ts < b.ts ? a : b);
      const scheduled = events.find(e => e.ph === 'X' && e.pid === 3 && e.name === name && e.tid === first.tid);
      return {name: name.split('(')[0], id: name.match(/\((.*?)\)/)[1], taskId: String(first.args.taskId), start: Math.min(...workers.map(e=>e.ts)), end: Math.max(...workers.map(e=>e.ts+e.dur)), fanin: first.args['fanin-hint'], fanout: first.args['fanout-hint'], event: first, dispatch: scheduled?.args['dispatch-time-us'] ?? null, kernel: workers.length === 1 ? first.args['kernel-duration-us'] : null, setup: workers.length === 1 ? first.args.local_setup_us : null, cores: workers.map(e=>({start:e.ts, end:e.ts+e.dur,lane:lanes.get(e.tid)||String(e.tid),eventId:e.id})), rootHash: first.args.rootHash ?? null, callOpMagic: first.args.callOpMagic ?? null, leafHash: first.args.leafHash ?? null};
    })};
  }
}
function snippet(file, needle, before=3, after=12) {
  const lines = fs.readFileSync(path.join(base,file),'utf8').split('\n');
  const i = lines.findIndex(l=>l.includes(needle));
  if(i<0) throw Error(`Missing source ${needle}`);
  const start=Math.max(0,i-before);
  let end=i+after+1;
  if(lines[i].trimStart().startsWith('def ')) {
    const next=lines.findIndex((l,n)=>n>i&&l.startsWith('    @pl.function'));
    if(next>i)end=Math.min(end,next);
  }
  return {file,line:i+1,start:start+1,lines:lines.slice(start,end)};
}
result.sources.oConst=snippet('deepseek_v4_flash_dspark/decode_o_proj.py','ATTENTION_PUBLISH_WORKERS =',3,7);
result.sources.oWait=snippet('deepseek_v4_flash_dspark/decode_o_proj.py','name_hint="o_group_a2a_wait"',2,22);
result.sources.tokenConst=snippet('deepseek_v4_flash_dspark/decode_cp_token_allgather.py','COMM_ROW_TILE =',2,12);
result.sources.tokenWait=snippet('deepseek_v4_flash_dspark/decode_cp_token_allgather.py','name_hint="cp_token_allgather_payload_wait"',2,21);
for(const file of fs.readdirSync(path.join(base,jit,'passes_dump')).sort()) {
  const rel=`${jit}/passes_dump/${file}`;
  result.passes.push({file:rel,name:file.replace(/^\d+_(after_)?/,'').replace('.py',''),index:Number(file.slice(0,2))});
  if([0,9,25,39,40,48].includes(Number(file.slice(0,2)))) {
    for(const key of ['a2a','token']) {
      const needle= key==='a2a' ? 'o_group_a2a_wait' : 'cp_token_allgather_payload_wait';
      result.sources[`${key}Pass${Number(file.slice(0,2))}`]=snippet(rel,needle,1,13);
    }
  }
}
fs.writeFileSync(path.join(__dirname,'data.js'), `// Generated by build-data.cjs; do not hand-edit.\nwindow.INVESTIGATION_DATA = ${JSON.stringify(result)};\n`);
console.log(`Extracted 2 cases, 2 ranks, ${result.passes.length} snapshots. All source anchors resolved.`);
