// Kernel Function: csa_cache_writeback
// Generated by PyPTO IR Compiler (PTO backend)

#include <cstdint>

#ifndef __gm__
#define __gm__
#endif

#ifndef __aicore__
#if defined(__CPU_SIM)
#define __aicore__
#else
#define __aicore__ [aicore]
#endif
#endif

#include <pto/pto-inst.hpp>
#include "tensor.h"

#include "intrinsic.h"


using namespace pto;


// --- ptoas-generated code ---

template <typename Tensor>
static __aicore__ inline auto PTOAS__GLOBAL_TENSOR_DATA(Tensor &tensor)
    -> decltype(tensor.data()) {
  return tensor.data();
}


enum class PTOAutoSyncTailMode : int {
  kBarrierAll = 0,
  kSetWaitMte3ToSEvent0 = 1,
};

static __aicore__ inline void ptoas_auto_sync_tail(
    PTOAutoSyncTailMode mode = PTOAutoSyncTailMode::kBarrierAll) {
  switch (mode) {
  case PTOAutoSyncTailMode::kSetWaitMte3ToSEvent0:
    set_flag(PIPE_MTE3, PIPE_S, EVENT_ID0);
    wait_flag(PIPE_MTE3, PIPE_S, EVENT_ID0);
    break;
  case PTOAutoSyncTailMode::kBarrierAll:
  default:
    pipe_barrier(PIPE_ALL);
    break;
  }
}

template <typename Ptr>
static __aicore__ inline void PTOAS__DCCI_SINGLE_CACHE_LINE(Ptr ptr) {
  dcci((__gm__ void*)ptr, cache_line_t::SINGLE_CACHE_LINE);
}

static __aicore__ void csa_cache_writeback(__gm__ bfloat16_t* v1, __gm__ int64_t* v2, __gm__ bfloat16_t* v3, int64_t v4, int64_t v5, int64_t v6, int32_t v7, int32_t v8) {
  const int64_t v9 = 8;
  const int64_t v10 = 1;
  const int64_t v11 = 512;
  const int64_t v12 = 0;
  using T = float;

  #if defined(__DAV_VEC__)
  set_mask_norm();
  set_vector_mask(-1, -1);
  set_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID0);
  for (int64_t i13 = v12; i13 < v9; i13 += v10) {
    // pto: %wb_blk_inline1315__ssa_v0, %0, %1
    int64_t v14 = (int64_t) ((uint64_t) ((int64_t) ((uint64_t) ((int64_t) v7) * (uint64_t) v9)) + (uint64_t) i13);
    // pto: %write_row_i64_inline1319__tile
    int64_t v15 = (v2)[v14];
    // pto: %3
    if (v15 >= v12) {
      // pto: %t__tile
      Tile<TileType::Vec, bfloat16_t, 1, 512, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v16 = Tile<TileType::Vec, bfloat16_t, 1, 512, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v10, v11);
      // pto: %t__tile
      uint64_t v17 = (uint64_t) v12;
      TASSIGN(v16, v17);
      // pto: %kv_full_inline1265__ssa_v0_pview
      pto::Shape<1, 1, 1, 1, 512> v18 = pto::Shape<1, 1, 1, 1, 512>();
      // pto: %kv_full_inline1265__ssa_v0_pview
      pto::Stride<512, 512, 512, 512, 1> v19 = pto::Stride<512, 512, 512, 512, 1>();
      // pto: %5, %kv_full_inline1265__ssa_v0_pview
      GlobalTensor<bfloat16_t, pto::Shape<1, 1, 1, 1, 512>, pto::Stride<512, 512, 512, 512, 1>, pto::Layout::ND> v20 = GlobalTensor<bfloat16_t, pto::Shape<1, 1, 1, 1, 512>, pto::Stride<512, 512, 512, 512, 1>, pto::Layout::ND>(v3 + (v12 + (v14 < v12 ? v12 : v14) * v11), v18, v19);
      wait_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID0);
      TLOAD(v16, v20);
      set_flag(PIPE_MTE2, PIPE_MTE3, EVENT_ID0);
      // pto: %kv_cache_flat_inline1312__iter_v1_pview
      pto::Shape<1, 1, 1, 1, 512> v21 = pto::Shape<1, 1, 1, 1, 512>();
      // pto: %kv_cache_flat_inline1312__iter_v1_pview
      pto::Stride<512, 512, 512, 512, 1> v22 = pto::Stride<512, 512, 512, 512, 1>();
      // pto: %6, %kv_cache_flat_inline1312__iter_v1_pview
      GlobalTensor<bfloat16_t, pto::Shape<1, 1, 1, 1, 512>, pto::Stride<512, 512, 512, 512, 1>, pto::Layout::ND> v23 = GlobalTensor<bfloat16_t, pto::Shape<1, 1, 1, 1, 512>, pto::Stride<512, 512, 512, 512, 1>, pto::Layout::ND>(v1 + (v12 + (v15 < v12 ? v12 : v15) * v11), v21, v22);
      wait_flag(PIPE_MTE2, PIPE_MTE3, EVENT_ID0);
      TSTORE(v23, v16);
      set_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID0);
    }
  }
  wait_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID0);
  #endif // __DAV_VEC__

  ptoas_auto_sync_tail(PTOAutoSyncTailMode::kBarrierAll);
  return;
}
// --- Kernel entry point ---
extern "C" __aicore__ __attribute__((always_inline)) void kernel_entry(__gm__ int64_t* args)
{
#if !defined(__CPU_SIM) && !defined(__COSTMODEL)
    // Reset AI Core atomic mode inherited from a prior kernel.
    set_atomic_none();
#endif

    // Read logical SPMD block identity from runtime dispatch payload
    int32_t __pypto_spmd_block_idx = get_block_idx(args);
    int32_t __pypto_spmd_block_num = get_block_num(args);

    // Unpack tensor: kv_cache_flat_inline1312__ssa_v0
    __gm__ Tensor* kv_cache_flat_inline1312__ssa_v0_tensor = reinterpret_cast<__gm__ Tensor*>(args[0]);
    __gm__ bfloat16_t* kv_cache_flat_inline1312__ssa_v0 = reinterpret_cast<__gm__ bfloat16_t*>(kv_cache_flat_inline1312__ssa_v0_tensor->buffer.addr) + kv_cache_flat_inline1312__ssa_v0_tensor->start_offset;

    // Unpack tensor: ori_slot_mapping__ssa_v0
    __gm__ Tensor* ori_slot_mapping__ssa_v0_tensor = reinterpret_cast<__gm__ Tensor*>(args[1]);
    __gm__ int64_t* ori_slot_mapping__ssa_v0 = reinterpret_cast<__gm__ int64_t*>(ori_slot_mapping__ssa_v0_tensor->buffer.addr) + ori_slot_mapping__ssa_v0_tensor->start_offset;

    // Unpack tensor: kv_full_inline1265__ssa_v0
    __gm__ Tensor* kv_full_inline1265__ssa_v0_tensor = reinterpret_cast<__gm__ Tensor*>(args[2]);
    __gm__ bfloat16_t* kv_full_inline1265__ssa_v0 = reinterpret_cast<__gm__ bfloat16_t*>(kv_full_inline1265__ssa_v0_tensor->buffer.addr) + kv_full_inline1265__ssa_v0_tensor->start_offset;

    // Extract dynamic dim: ori_block_num_inline1291__ssa_v0
    int64_t ori_block_num_inline1291__ssa_v0 = (static_cast<int64_t>(kv_cache_flat_inline1312__ssa_v0_tensor->shapes[0]) / 32);

    // Extract dynamic dim: KV_T_DYN
    int64_t KV_T_DYN = static_cast<int64_t>(ori_slot_mapping__ssa_v0_tensor->shapes[0]);

    // Extract dynamic dim: kv_dim_inline1261__ssa_v0
    int64_t kv_dim_inline1261__ssa_v0 = static_cast<int64_t>(kv_full_inline1265__ssa_v0_tensor->shapes[0]);

    // Forward to ptoas-generated function
    csa_cache_writeback(kv_cache_flat_inline1312__ssa_v0, ori_slot_mapping__ssa_v0, kv_full_inline1265__ssa_v0, ori_block_num_inline1291__ssa_v0, KV_T_DYN, kv_dim_inline1261__ssa_v0, __pypto_spmd_block_idx, __pypto_spmd_block_num);
}
