// Kernel Function: kv_touch
// Generated by PyPTO IR Compiler (PTO backend)

#include <cstdint>

#ifndef __gm__
#define __gm__
#endif

#ifndef __aicore__
#if defined(__CPU_SIM)
#define __aicore__
#else
#define __aicore__ [aicore]
#endif
#endif

#include <pto/pto-inst.hpp>
#include "tensor.h"



using namespace pto;


// --- ptoas-generated code ---

template <typename Tensor>
static __aicore__ inline auto PTOAS__GLOBAL_TENSOR_DATA(Tensor &tensor)
    -> decltype(tensor.data()) {
  return tensor.data();
}


enum class PTOAutoSyncTailMode : int {
  kBarrierAll = 0,
  kSetWaitMte3ToSEvent0 = 1,
};

static __aicore__ inline void ptoas_auto_sync_tail(
    PTOAutoSyncTailMode mode = PTOAutoSyncTailMode::kBarrierAll) {
  switch (mode) {
  case PTOAutoSyncTailMode::kSetWaitMte3ToSEvent0:
    set_flag(PIPE_MTE3, PIPE_S, EVENT_ID0);
    wait_flag(PIPE_MTE3, PIPE_S, EVENT_ID0);
    break;
  case PTOAutoSyncTailMode::kBarrierAll:
  default:
    pipe_barrier(PIPE_ALL);
    break;
  }
}

template <typename Ptr>
static __aicore__ inline void PTOAS__DCCI_SINGLE_CACHE_LINE(Ptr ptr) {
  dcci((__gm__ void*)ptr, cache_line_t::SINGLE_CACHE_LINE);
}

static __aicore__ void kv_touch(__gm__ bfloat16_t* v1, int64_t v2) {
  const int64_t v3 = 1;
  const int64_t v4 = 512;
  const int64_t v5 = 0;
  using T = float;

  #if defined(__DAV_VEC__)
  set_mask_norm();
  set_vector_mask(-1, -1);
  // pto: %t__tile
  Tile<TileType::Vec, bfloat16_t, 1, 512, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v6 = Tile<TileType::Vec, bfloat16_t, 1, 512, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v3, v4);
  // pto: %t__tile
  uint64_t v7 = (uint64_t) v5;
  TASSIGN(v6, v7);
  // pto: %ori_kv_flat_inline2344__ssa_v0_pview
  pto::Shape<1, 1, 1, 1, 512> v8 = pto::Shape<1, 1, 1, 1, 512>();
  // pto: %ori_kv_flat_inline2344__ssa_v0_pview
  pto::Stride<512, 512, 512, 512, 1> v9 = pto::Stride<512, 512, 512, 512, 1>();
  // pto: %ori_kv_flat_inline2344__ssa_v0_pview
  GlobalTensor<bfloat16_t, pto::Shape<1, 1, 1, 1, 512>, pto::Stride<512, 512, 512, 512, 1>, pto::Layout::ND> v10 = GlobalTensor<bfloat16_t, pto::Shape<1, 1, 1, 1, 512>, pto::Stride<512, 512, 512, 512, 1>, pto::Layout::ND>(v1, v8, v9);
  TLOAD(v6, v10);
  set_flag(PIPE_MTE2, PIPE_MTE3, EVENT_ID0);
  wait_flag(PIPE_MTE2, PIPE_MTE3, EVENT_ID0);
  TSTORE(v10, v6);
  #endif // __DAV_VEC__

  ptoas_auto_sync_tail(PTOAutoSyncTailMode::kBarrierAll);
  return;
}
// --- Kernel entry point ---
extern "C" __aicore__ __attribute__((always_inline)) void kernel_entry(__gm__ int64_t* args)
{
#if !defined(__CPU_SIM) && !defined(__COSTMODEL)
    // Reset AI Core atomic mode inherited from a prior kernel.
    set_atomic_none();
#endif

    // Unpack tensor: ori_kv_flat_inline2344__ssa_v0
    __gm__ Tensor* ori_kv_flat_inline2344__ssa_v0_tensor = reinterpret_cast<__gm__ Tensor*>(args[0]);
    __gm__ bfloat16_t* ori_kv_flat_inline2344__ssa_v0 = reinterpret_cast<__gm__ bfloat16_t*>(ori_kv_flat_inline2344__ssa_v0_tensor->buffer.addr) + ori_kv_flat_inline2344__ssa_v0_tensor->start_offset;

    // Extract dynamic dim: ori_block_num_inline2362__ssa_v0
    int64_t ori_block_num_inline2362__ssa_v0 = (static_cast<int64_t>(ori_kv_flat_inline2344__ssa_v0_tensor->shapes[0]) / 32);

    // Forward to ptoas-generated function
    kv_touch(ori_kv_flat_inline2344__ssa_v0, ori_block_num_inline2362__ssa_v0);
}
