// Kernel Function: q_rope_prepare
// Generated by PyPTO IR Compiler (PTO backend)

#include <cstdint>

#ifndef __gm__
#define __gm__
#endif

#ifndef __aicore__
#if defined(__CPU_SIM)
#define __aicore__
#else
#define __aicore__ [aicore]
#endif
#endif

#include <pto/pto-inst.hpp>
#include "tensor.h"

#include "intrinsic.h"


using namespace pto;


// --- ptoas-generated code ---

template <typename Tensor>
static __aicore__ inline auto PTOAS__GLOBAL_TENSOR_DATA(Tensor &tensor)
    -> decltype(tensor.data()) {
  return tensor.data();
}


enum class PTOAutoSyncTailMode : int {
  kBarrierAll = 0,
  kSetWaitMte3ToSEvent0 = 1,
};

static __aicore__ inline void ptoas_auto_sync_tail(
    PTOAutoSyncTailMode mode = PTOAutoSyncTailMode::kBarrierAll) {
  switch (mode) {
  case PTOAutoSyncTailMode::kSetWaitMte3ToSEvent0:
    set_flag(PIPE_MTE3, PIPE_S, EVENT_ID0);
    wait_flag(PIPE_MTE3, PIPE_S, EVENT_ID0);
    break;
  case PTOAutoSyncTailMode::kBarrierAll:
  default:
    pipe_barrier(PIPE_ALL);
    break;
  }
}

template <typename Ptr>
static __aicore__ inline void PTOAS__DCCI_SINGLE_CACHE_LINE(Ptr ptr) {
  dcci((__gm__ void*)ptr, cache_line_t::SINGLE_CACHE_LINE);
}

static __aicore__ void q_rope_prepare(__gm__ bfloat16_t* v1, __gm__ bfloat16_t* v2, __gm__ float* v3, __gm__ float* v4, __gm__ int32_t* v5, int64_t v6, int64_t v7, int32_t v8, int32_t v9) {
  RoundMode v10 = RoundMode::CAST_TRUNC;
  SaturationMode v11 = SaturationMode::OFF;
  RoundMode v12 = RoundMode::CAST_ROUND;
  const float v13 = 64.0f;
  const float v14 = 2.0f;
  const float v15 = 0.5f;
  const int32_t v16 = 0;
  const float v17 = 1.0f;
  const int64_t v18 = 8;
  const int64_t v19 = 1;
  const int64_t v20 = 64;
  const int64_t v21 = 8192;
  const int64_t v22 = 11264;
  const int64_t v23 = 6144;
  const int64_t v24 = 4096;
  const int64_t v25 = 2048;
  const int64_t v26 = 0;
  const int64_t v27 = 13312;
  const int64_t v28 = 9216;
  const int64_t v29 = 256;
  using T = float;

  #if defined(__DAV_VEC__)
  set_mask_norm();
  set_vector_mask(-1, -1);
  // pto: %rope_cos_view_inline1679__ssa_v0_view
  int64_t v30 = v7 * v20;
  // pto: %rope_cos_view_inline1679__ssa_v0_view
  int64_t v31 = v19 * v30;
  // pto: %rope_cos_view_inline1679__ssa_v0_view
  pto::Shape<1, 1, 1, -1, -1> v32 = pto::Shape<1, 1, 1, -1, -1>(v19, v19, v19, v7, v20);
  // pto: %rope_cos_view_inline1679__ssa_v0_view
  pto::Stride<-1, -1, -1, -1, -1> v33 = pto::Stride<-1, -1, -1, -1, -1>(v19 * v31, v31, v30, v20, v19);
  // pto: %rope_cos_view_inline1679__ssa_v0_view
  GlobalTensor<bfloat16_t, pto::Shape<1, 1, 1, -1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND> v34 = GlobalTensor<bfloat16_t, pto::Shape<1, 1, 1, -1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND>(v1, v32, v33);
  // pto: %rope_sin_view_inline1674__ssa_v0_view
  int64_t v35 = v7 * v20;
  // pto: %rope_sin_view_inline1674__ssa_v0_view
  int64_t v36 = v19 * v35;
  // pto: %rope_sin_view_inline1674__ssa_v0_view
  pto::Shape<1, 1, 1, -1, -1> v37 = pto::Shape<1, 1, 1, -1, -1>(v19, v19, v19, v7, v20);
  // pto: %rope_sin_view_inline1674__ssa_v0_view
  pto::Stride<-1, -1, -1, -1, -1> v38 = pto::Stride<-1, -1, -1, -1, -1>(v19 * v36, v36, v35, v20, v19);
  // pto: %rope_sin_view_inline1674__ssa_v0_view
  GlobalTensor<bfloat16_t, pto::Shape<1, 1, 1, -1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND> v39 = GlobalTensor<bfloat16_t, pto::Shape<1, 1, 1, -1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND>(v2, v37, v38);
  // pto: %rope_cos_il_view_inline1670__ssa_v0_view
  int64_t v40 = v7 * v20;
  // pto: %rope_cos_il_view_inline1670__ssa_v0_view
  int64_t v41 = v19 * v40;
  // pto: %rope_cos_il_view_inline1670__ssa_v0_view
  pto::Shape<1, 1, 1, -1, -1> v42 = pto::Shape<1, 1, 1, -1, -1>(v19, v19, v19, v7, v20);
  // pto: %rope_cos_il_view_inline1670__ssa_v0_view
  pto::Stride<-1, -1, -1, -1, -1> v43 = pto::Stride<-1, -1, -1, -1, -1>(v19 * v41, v41, v40, v20, v19);
  // pto: %rope_cos_il_view_inline1670__ssa_v0_view
  GlobalTensor<float, pto::Shape<1, 1, 1, -1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND> v44 = GlobalTensor<float, pto::Shape<1, 1, 1, -1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND>(v3, v42, v43);
  // pto: %rope_sin_signed_view_inline1668__ssa_v0_view
  int64_t v45 = v7 * v20;
  // pto: %rope_sin_signed_view_inline1668__ssa_v0_view
  int64_t v46 = v19 * v45;
  // pto: %rope_sin_signed_view_inline1668__ssa_v0_view
  pto::Shape<1, 1, 1, -1, -1> v47 = pto::Shape<1, 1, 1, -1, -1>(v19, v19, v19, v7, v20);
  // pto: %rope_sin_signed_view_inline1668__ssa_v0_view
  pto::Stride<-1, -1, -1, -1, -1> v48 = pto::Stride<-1, -1, -1, -1, -1>(v19 * v46, v46, v45, v20, v19);
  // pto: %rope_sin_signed_view_inline1668__ssa_v0_view
  GlobalTensor<float, pto::Shape<1, 1, 1, -1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND> v49 = GlobalTensor<float, pto::Shape<1, 1, 1, -1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND>(v4, v47, v48);
  // pto: %rope_swap_idx_view_inline1694__ssa_v0_view
  int64_t v50 = v7 * v20;
  // pto: %rope_swap_idx_view_inline1694__ssa_v0_view
  int64_t v51 = v19 * v50;
  // pto: %rope_swap_idx_view_inline1694__ssa_v0_view
  pto::Shape<1, 1, 1, -1, -1> v52 = pto::Shape<1, 1, 1, -1, -1>(v19, v19, v19, v7, v20);
  // pto: %rope_swap_idx_view_inline1694__ssa_v0_view
  pto::Stride<-1, -1, -1, -1, -1> v53 = pto::Stride<-1, -1, -1, -1, -1>(v19 * v51, v51, v50, v20, v19);
  // pto: %rope_swap_idx_view_inline1694__ssa_v0_view
  GlobalTensor<int32_t, pto::Shape<1, 1, 1, -1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND> v54 = GlobalTensor<int32_t, pto::Shape<1, 1, 1, -1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND>(v5, v52, v53);
  // pto: %qrp_idx_inline1681__ssa_v0, %7
  int64_t v55 = (int64_t) ((uint64_t) ((int64_t) v8) * (uint64_t) v18);
  // pto: %8
  int64_t v56 = (int64_t) ((uint64_t) v7 - (uint64_t) v55);
  // pto: %9
  int64_t v57 = v56 < v18 ? v56 : v18;
  // pto: %qrp_ones_inline1686__tile
  Tile<TileType::Vec, float, 8, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v58 = Tile<TileType::Vec, float, 8, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v18, v20);
  // pto: %qrp_ones_inline1686__tile
  uint64_t v59 = (uint64_t) v28;
  TASSIGN(v58, v59);
  TEXPANDS(v58, v17);
  // pto: %qrp_idx_i32_inline1666__tile
  Tile<TileType::Vec, int32_t, 1, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v60 = Tile<TileType::Vec, int32_t, 1, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v19, v20);
  // pto: %qrp_idx_i32_inline1666__tile
  uint64_t v61 = (uint64_t) v27;
  TASSIGN(v60, v61);
  TCI<Tile<TileType::Vec, int32_t, 1, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>, int32_t, 0>(v60, v16);
  set_flag(PIPE_S, PIPE_V, EVENT_ID0);
  // pto: %qrp_idx_fp32_inline1661__tile
  Tile<TileType::Vec, float, 1, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v62 = Tile<TileType::Vec, float, 1, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v19, v20);
  // pto: %qrp_idx_fp32_inline1661__tile
  uint64_t v63 = (uint64_t) v27;
  TASSIGN(v62, v63);
  wait_flag(PIPE_S, PIPE_V, EVENT_ID0);
  TCVT(v62, v60, v12, v11);
  // pto: %qrp_col_inline1675__tile
  Tile<TileType::Vec, float, 8, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v64 = Tile<TileType::Vec, float, 8, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v18, v20);
  // pto: %qrp_col_inline1675__tile
  uint64_t v65 = (uint64_t) v28;
  TASSIGN(v64, v65);
  pipe_barrier(PIPE_V);
  TCOLEXPANDMUL(v64, v58, v62);
  // pto: %qrp_half_inline1683__tile
  Tile<TileType::Vec, float, 8, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v66 = Tile<TileType::Vec, float, 8, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v18, v20);
  // pto: %qrp_half_inline1683__tile
  uint64_t v67 = (uint64_t) v27;
  TASSIGN(v66, v67);
  pipe_barrier(PIPE_V);
  TMULS(v66, v64, v15);
  // pto: %qrp_dup_i32_inline1685__tile
  Tile<TileType::Vec, int32_t, 8, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v68 = Tile<TileType::Vec, int32_t, 8, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v18, v20);
  // pto: %qrp_dup_i32_inline1685__tile
  uint64_t v69 = (uint64_t) v27;
  TASSIGN(v68, v69);
  pipe_barrier(PIPE_V);
  TCVT(v68, v66, v10, v11);
  // pto: %qrp_dup_f_inline1663__tile
  Tile<TileType::Vec, float, 8, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v70 = Tile<TileType::Vec, float, 8, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v18, v20);
  // pto: %qrp_dup_f_inline1663__tile
  uint64_t v71 = (uint64_t) v27;
  TASSIGN(v70, v71);
  pipe_barrier(PIPE_V);
  TCVT(v70, v68, v12, v11);
  // pto: %qrp_dup_idx_inline1680__tile
  Tile<TileType::Vec, int32_t, 8, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v72 = Tile<TileType::Vec, int32_t, 8, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v18, v20);
  // pto: %qrp_dup_idx_inline1680__tile
  uint64_t v73 = (uint64_t) v26;
  TASSIGN(v72, v73);
  pipe_barrier(PIPE_V);
  TCVT(v72, v70, v12, v11);
  // pto: %t__tile
  Tile<TileType::Vec, float, 8, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v74 = Tile<TileType::Vec, float, 8, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v18, v20);
  // pto: %t__tile
  uint64_t v75 = (uint64_t) v27;
  TASSIGN(v74, v75);
  pipe_barrier(PIPE_V);
  TMULS(v74, v70, v14);
  // pto: %qrp_lane_inline1678__tile
  Tile<TileType::Vec, float, 8, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v76 = Tile<TileType::Vec, float, 8, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v18, v20);
  // pto: %qrp_lane_inline1678__tile
  uint64_t v77 = (uint64_t) v27;
  TASSIGN(v76, v77);
  pipe_barrier(PIPE_V);
  TSUB(v76, v64, v74);
  // pto: %qrp_next_col_inline1689__tile
  Tile<TileType::Vec, float, 8, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v78 = Tile<TileType::Vec, float, 8, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v18, v20);
  // pto: %qrp_next_col_inline1689__tile
  uint64_t v79 = (uint64_t) v28;
  TASSIGN(v78, v79);
  pipe_barrier(PIPE_V);
  TADDS(v78, v64, v17);
  // pto: %qrp_lane_offset_inline1692__tile
  Tile<TileType::Vec, float, 8, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v80 = Tile<TileType::Vec, float, 8, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v18, v20);
  // pto: %qrp_lane_offset_inline1692__tile
  uint64_t v81 = (uint64_t) v25;
  TASSIGN(v80, v81);
  TMULS(v80, v76, v14);
  // pto: %qrp_swap_f_inline1690__tile
  Tile<TileType::Vec, float, 8, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v82 = Tile<TileType::Vec, float, 8, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v18, v20);
  // pto: %qrp_swap_f_inline1690__tile
  uint64_t v83 = (uint64_t) v28;
  TASSIGN(v82, v83);
  pipe_barrier(PIPE_V);
  TSUB(v82, v78, v80);
  // pto: %qrp_swap_idx_inline1695__tile
  Tile<TileType::Vec, int32_t, 8, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v84 = Tile<TileType::Vec, int32_t, 8, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v18, v20);
  // pto: %qrp_swap_idx_inline1695__tile
  uint64_t v85 = (uint64_t) v28;
  TASSIGN(v84, v85);
  pipe_barrier(PIPE_V);
  TCVT(v84, v82, v12, v11);
  // pto: %0
  Tile<TileType::Vec, float, 8, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v86 = Tile<TileType::Vec, float, 8, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v18, v20);
  // pto: %0
  uint64_t v87 = (uint64_t) v27;
  TASSIGN(v86, v87);
  TMULS(v86, v76, v14);
  // pto: %qrp_sign_inline1687__tile
  Tile<TileType::Vec, float, 8, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v88 = Tile<TileType::Vec, float, 8, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v18, v20);
  // pto: %qrp_sign_inline1687__tile
  uint64_t v89 = (uint64_t) v27;
  TASSIGN(v88, v89);
  pipe_barrier(PIPE_V);
  TSUBS(v88, v86, v17);
  set_flag(PIPE_V, PIPE_S, EVENT_ID0);
  // pto: %10
  wait_flag(PIPE_V, PIPE_S, EVENT_ID0);
  if (v57 == v18) {
    // pto: %qrp_cos_rows_full_inline1693__tile
    Tile<TileType::Vec, bfloat16_t, 8, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v90 = Tile<TileType::Vec, bfloat16_t, 8, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v18, v20);
    // pto: %qrp_cos_rows_full_inline1693__tile
    uint64_t v91 = (uint64_t) v24;
    TASSIGN(v90, v91);
    // pto: %11
    int64_t v92 = v55 < v26 ? v26 : v55;
    // pto: %rope_cos_view_inline1679__ssa_v0_pview
    pto::Shape<1, 1, 1, 8, 64> v93 = pto::Shape<1, 1, 1, 8, 64>();
    // pto: %rope_cos_view_inline1679__ssa_v0_pview
    pto::Stride<512, 512, 512, 64, 1> v94 = pto::Stride<512, 512, 512, 64, 1>();
    // pto: %rope_cos_view_inline1679__ssa_v0_pview
    GlobalTensor<bfloat16_t, pto::Shape<1, 1, 1, 8, 64>, pto::Stride<512, 512, 512, 64, 1>, pto::Layout::ND> v95 = GlobalTensor<bfloat16_t, pto::Shape<1, 1, 1, 8, 64>, pto::Stride<512, 512, 512, 64, 1>, pto::Layout::ND>(v1 + (v26 + v92 * v20), v93, v94);
    TLOAD(v90, v95);
    set_flag(PIPE_MTE2, PIPE_V, EVENT_ID0);
    // pto: %qrp_sin_rows_full_inline1696__tile
    Tile<TileType::Vec, bfloat16_t, 8, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v96 = Tile<TileType::Vec, bfloat16_t, 8, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v18, v20);
    // pto: %qrp_sin_rows_full_inline1696__tile
    uint64_t v97 = (uint64_t) v23;
    TASSIGN(v96, v97);
    // pto: %rope_sin_view_inline1674__ssa_v0_pview
    pto::Shape<1, 1, 1, 8, 64> v98 = pto::Shape<1, 1, 1, 8, 64>();
    // pto: %rope_sin_view_inline1674__ssa_v0_pview
    pto::Stride<512, 512, 512, 64, 1> v99 = pto::Stride<512, 512, 512, 64, 1>();
    // pto: %rope_sin_view_inline1674__ssa_v0_pview
    GlobalTensor<bfloat16_t, pto::Shape<1, 1, 1, 8, 64>, pto::Stride<512, 512, 512, 64, 1>, pto::Layout::ND> v100 = GlobalTensor<bfloat16_t, pto::Shape<1, 1, 1, 8, 64>, pto::Stride<512, 512, 512, 64, 1>, pto::Layout::ND>(v2 + (v26 + v92 * v20), v98, v99);
    TLOAD(v96, v100);
    set_flag(PIPE_MTE2, PIPE_MTE3, EVENT_ID0);
    set_flag(PIPE_MTE2, PIPE_V, EVENT_ID1);
    // pto: %qrp_cos_full_inline1676__tile
    Tile<TileType::Vec, float, 8, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v101 = Tile<TileType::Vec, float, 8, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v18, v20);
    // pto: %qrp_cos_full_inline1676__tile
    uint64_t v102 = (uint64_t) v25;
    TASSIGN(v101, v102);
    wait_flag(PIPE_MTE2, PIPE_V, EVENT_ID0);
    TCVT(v101, v90, v12, v11);
    // pto: %qrp_sin_full_inline1669__tile
    Tile<TileType::Vec, float, 8, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v103 = Tile<TileType::Vec, float, 8, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v18, v20);
    // pto: %qrp_sin_full_inline1669__tile
    uint64_t v104 = (uint64_t) v24;
    TASSIGN(v103, v104);
    pipe_barrier(PIPE_V);
    wait_flag(PIPE_MTE2, PIPE_V, EVENT_ID1);
    TCVT(v103, v96, v12, v11);
    // pto: %gather_acc_init
    Tile<TileType::Vec, float, 8, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v105 = Tile<TileType::Vec, float, 8, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v18, v20);
    // pto: %gather_acc_init
    uint64_t v106 = (uint64_t) v23;
    TASSIGN(v105, v106);
    for (int64_t i107 = v26; i107 < v18; i107 += v19) {
      // pto: %gather_inp_row
      Tile<TileType::Vec, float, 1, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v108 = Tile<TileType::Vec, float, 1, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v19, v20);
      // pto: %gather_inp_row
      uint64_t v109 = (uint64_t) v25;
      TASSIGN(v108, v109);
      // pto: %slice_view
      int64_t v110 = (int64_t) ((uint64_t) i107 * (uint64_t) v29);
      // pto: %slice_view
      Tile<TileType::Vec, float, 1, 64, BLayout::RowMajor, 1, 64, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v111;
      // pto: %slice_view
      Tile<TileType::Vec, float, 1, 64, BLayout::RowMajor, 1, 64, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v112 = v111;
      // pto: %slice_view
      uint64_t v113 = (uint64_t) ((int64_t) ((uint64_t) v110 + (uint64_t) v25));
      TASSIGN(v112, v113);
      // pto: %gather_idx_row
      Tile<TileType::Vec, int32_t, 1, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v114 = Tile<TileType::Vec, int32_t, 1, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v19, v20);
      // pto: %gather_idx_row
      uint64_t v115 = (uint64_t) v26;
      TASSIGN(v114, v115);
      // pto: %13
      Tile<TileType::Vec, int32_t, 1, 64, BLayout::RowMajor, 1, 64, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v116;
      // pto: %13
      Tile<TileType::Vec, int32_t, 1, 64, BLayout::RowMajor, 1, 64, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v117 = v116;
      // pto: %13
      uint64_t v118 = (uint64_t) v110;
      TASSIGN(v117, v118);
      // pto: %gather_row_tmp
      Tile<TileType::Vec, int32_t, 1, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v119 = Tile<TileType::Vec, int32_t, 1, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v19, v20);
      // pto: %gather_row_tmp
      uint64_t v120 = (uint64_t) v22;
      TASSIGN(v119, v120);
      // pto: %gather_row
      Tile<TileType::Vec, float, 1, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v121 = Tile<TileType::Vec, float, 1, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v19, v20);
      // pto: %gather_row
      uint64_t v122 = (uint64_t) v21;
      TASSIGN(v121, v122);
      pipe_barrier(PIPE_V);
      TGATHER(v121, v112, v117, v119);
      // pto: %assemble_view
      Tile<TileType::Vec, float, 1, 64, BLayout::RowMajor, 1, 64, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v123;
      // pto: %assemble_view
      Tile<TileType::Vec, float, 1, 64, BLayout::RowMajor, 1, 64, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v124 = v123;
      // pto: %assemble_view
      uint64_t v125 = (uint64_t) ((int64_t) ((uint64_t) v110 + (uint64_t) v23));
      TASSIGN(v124, v125);
      pipe_barrier(PIPE_V);
      TMOV(v124, v121);
    }
    set_flag(PIPE_V, PIPE_MTE3, EVENT_ID0);
    // pto: %qrp_cos_il_full_inline1697__tile
    Tile<TileType::Vec, float, 8, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v126 = Tile<TileType::Vec, float, 8, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v18, v20);
    // pto: %qrp_cos_il_full_inline1697__tile
    uint64_t v127 = (uint64_t) v23;
    TASSIGN(v126, v127);
    // pto: %1
    Tile<TileType::Vec, float, 8, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v128 = Tile<TileType::Vec, float, 8, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v18, v20);
    // pto: %1
    uint64_t v129 = (uint64_t) v25;
    TASSIGN(v128, v129);
    for (int64_t i130 = v26; i130 < v18; i130 += v19) {
      // pto: %2
      Tile<TileType::Vec, float, 1, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v131 = Tile<TileType::Vec, float, 1, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v19, v20);
      // pto: %2
      uint64_t v132 = (uint64_t) v24;
      TASSIGN(v131, v132);
      // pto: %15
      int64_t v133 = (int64_t) ((uint64_t) i130 * (uint64_t) v29);
      // pto: %15
      Tile<TileType::Vec, float, 1, 64, BLayout::RowMajor, 1, 64, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v134;
      // pto: %15
      Tile<TileType::Vec, float, 1, 64, BLayout::RowMajor, 1, 64, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v135 = v134;
      // pto: %15
      uint64_t v136 = (uint64_t) ((int64_t) ((uint64_t) v133 + (uint64_t) v24));
      TASSIGN(v135, v136);
      // pto: %3
      Tile<TileType::Vec, int32_t, 1, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v137 = Tile<TileType::Vec, int32_t, 1, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v19, v20);
      // pto: %3
      uint64_t v138 = (uint64_t) v26;
      TASSIGN(v137, v138);
      // pto: %16
      Tile<TileType::Vec, int32_t, 1, 64, BLayout::RowMajor, 1, 64, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v139;
      // pto: %16
      Tile<TileType::Vec, int32_t, 1, 64, BLayout::RowMajor, 1, 64, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v140 = v139;
      // pto: %16
      uint64_t v141 = (uint64_t) v133;
      TASSIGN(v140, v141);
      // pto: %4
      Tile<TileType::Vec, int32_t, 1, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v142 = Tile<TileType::Vec, int32_t, 1, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v19, v20);
      // pto: %4
      uint64_t v143 = (uint64_t) v22;
      TASSIGN(v142, v143);
      // pto: %5
      Tile<TileType::Vec, float, 1, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v144 = Tile<TileType::Vec, float, 1, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v19, v20);
      // pto: %5
      uint64_t v145 = (uint64_t) v21;
      TASSIGN(v144, v145);
      pipe_barrier(PIPE_V);
      TGATHER(v144, v135, v140, v142);
      // pto: %17
      Tile<TileType::Vec, float, 1, 64, BLayout::RowMajor, 1, 64, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v146;
      // pto: %17
      Tile<TileType::Vec, float, 1, 64, BLayout::RowMajor, 1, 64, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v147 = v146;
      // pto: %17
      uint64_t v148 = (uint64_t) ((int64_t) ((uint64_t) v133 + (uint64_t) v25));
      TASSIGN(v147, v148);
      pipe_barrier(PIPE_V);
      TMOV(v147, v144);
    }
    // pto: %qrp_sin_il_full_inline1671__tile
    Tile<TileType::Vec, float, 8, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v149 = Tile<TileType::Vec, float, 8, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v18, v20);
    // pto: %qrp_sin_il_full_inline1671__tile
    uint64_t v150 = (uint64_t) v25;
    TASSIGN(v149, v150);
    // pto: %qrp_sin_signed_full_inline1691__tile
    Tile<TileType::Vec, float, 8, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v151 = Tile<TileType::Vec, float, 8, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v18, v20);
    // pto: %qrp_sin_signed_full_inline1691__tile
    uint64_t v152 = (uint64_t) v27;
    TASSIGN(v151, v152);
    pipe_barrier(PIPE_V);
    TMUL(v151, v149, v88);
    set_flag(PIPE_V, PIPE_MTE3, EVENT_ID1);
    // pto: %rope_cos_il_view_inline1670__ssa_v0_pview
    pto::Shape<1, 1, 1, 8, 64> v153 = pto::Shape<1, 1, 1, 8, 64>();
    // pto: %rope_cos_il_view_inline1670__ssa_v0_pview
    pto::Stride<512, 512, 512, 64, 1> v154 = pto::Stride<512, 512, 512, 64, 1>();
    // pto: %rope_cos_il_view_inline1670__ssa_v0_pview
    GlobalTensor<float, pto::Shape<1, 1, 1, 8, 64>, pto::Stride<512, 512, 512, 64, 1>, pto::Layout::ND> v155 = GlobalTensor<float, pto::Shape<1, 1, 1, 8, 64>, pto::Stride<512, 512, 512, 64, 1>, pto::Layout::ND>(v3 + (v26 + v92 * v20), v153, v154);
    wait_flag(PIPE_V, PIPE_MTE3, EVENT_ID0);
    wait_flag(PIPE_MTE2, PIPE_MTE3, EVENT_ID0);
    TSTORE(v155, v126);
    // pto: %rope_sin_signed_view_inline1668__ssa_v0_pview
    pto::Shape<1, 1, 1, 8, 64> v156 = pto::Shape<1, 1, 1, 8, 64>();
    // pto: %rope_sin_signed_view_inline1668__ssa_v0_pview
    pto::Stride<512, 512, 512, 64, 1> v157 = pto::Stride<512, 512, 512, 64, 1>();
    // pto: %rope_sin_signed_view_inline1668__ssa_v0_pview
    GlobalTensor<float, pto::Shape<1, 1, 1, 8, 64>, pto::Stride<512, 512, 512, 64, 1>, pto::Layout::ND> v158 = GlobalTensor<float, pto::Shape<1, 1, 1, 8, 64>, pto::Stride<512, 512, 512, 64, 1>, pto::Layout::ND>(v4 + (v26 + v92 * v20), v156, v157);
    wait_flag(PIPE_V, PIPE_MTE3, EVENT_ID1);
    TSTORE(v158, v151);
    // pto: %rope_swap_idx_view_inline1694__ssa_v0_pview
    pto::Shape<1, 1, 1, 8, 64> v159 = pto::Shape<1, 1, 1, 8, 64>();
    // pto: %rope_swap_idx_view_inline1694__ssa_v0_pview
    pto::Stride<512, 512, 512, 64, 1> v160 = pto::Stride<512, 512, 512, 64, 1>();
    // pto: %rope_swap_idx_view_inline1694__ssa_v0_pview
    GlobalTensor<int32_t, pto::Shape<1, 1, 1, 8, 64>, pto::Stride<512, 512, 512, 64, 1>, pto::Layout::ND> v161 = GlobalTensor<int32_t, pto::Shape<1, 1, 1, 8, 64>, pto::Stride<512, 512, 512, 64, 1>, pto::Layout::ND>(v5 + (v26 + v92 * v20), v159, v160);
    TSTORE(v161, v84);
  } else {
    // pto: %qrp_cos_rows_tail_inline1684__ssa_v0
    Tile<TileType::Vec, bfloat16_t, 8, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v162 = Tile<TileType::Vec, bfloat16_t, 8, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v57, v20);
    // pto: %qrp_cos_rows_tail_inline1684__ssa_v0
    uint64_t v163 = (uint64_t) v22;
    TASSIGN(v162, v163);
    // pto: %21
    int64_t v164 = v55 < v26 ? v26 : v55;
    // pto: %22
    __gm__ bfloat16_t* v165 = PTOAS__GLOBAL_TENSOR_DATA(v34);
    // pto: %22
    int64_t v166 = v57 * v20;
    // pto: %22
    int64_t v167 = v19 * v166;
    // pto: %22
    pto::Shape<1, 1, 1, -1, 64> v168 = pto::Shape<1, 1, 1, -1, 64>(v19, v19, v19, v57, v20);
    // pto: %22
    pto::Stride<-1, -1, -1, -1, -1> v169 = pto::Stride<-1, -1, -1, -1, -1>(v19 * v167, v167, v166, v20, v19);
    // pto: %22
    GlobalTensor<bfloat16_t, pto::Shape<1, 1, 1, -1, 64>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND> v170 = GlobalTensor<bfloat16_t, pto::Shape<1, 1, 1, -1, 64>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND>(v165 + ((v26 + v164 * v20) + v26 * v19), v168, v169);
    TLOAD(v162, v170);
    set_flag(PIPE_MTE2, PIPE_V, EVENT_ID2);
    // pto: %qrp_sin_rows_tail_inline1660__ssa_v0
    Tile<TileType::Vec, bfloat16_t, 8, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v171 = Tile<TileType::Vec, bfloat16_t, 8, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v57, v20);
    // pto: %qrp_sin_rows_tail_inline1660__ssa_v0
    uint64_t v172 = (uint64_t) v21;
    TASSIGN(v171, v172);
    // pto: %24
    __gm__ bfloat16_t* v173 = PTOAS__GLOBAL_TENSOR_DATA(v39);
    // pto: %24
    int64_t v174 = v57 * v20;
    // pto: %24
    int64_t v175 = v19 * v174;
    // pto: %24
    pto::Shape<1, 1, 1, -1, 64> v176 = pto::Shape<1, 1, 1, -1, 64>(v19, v19, v19, v57, v20);
    // pto: %24
    pto::Stride<-1, -1, -1, -1, -1> v177 = pto::Stride<-1, -1, -1, -1, -1>(v19 * v175, v175, v174, v20, v19);
    // pto: %24
    GlobalTensor<bfloat16_t, pto::Shape<1, 1, 1, -1, 64>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND> v178 = GlobalTensor<bfloat16_t, pto::Shape<1, 1, 1, -1, 64>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND>(v173 + ((v26 + v164 * v20) + v26 * v19), v176, v177);
    TLOAD(v171, v178);
    set_flag(PIPE_MTE2, PIPE_V, EVENT_ID3);
    // pto: %t__tmp_v89
    Tile<TileType::Vec, float, 8, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v179 = Tile<TileType::Vec, float, 8, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v18, v20);
    // pto: %t__tmp_v89
    uint64_t v180 = (uint64_t) v28;
    TASSIGN(v179, v180);
    TEXPANDS(v179, v17);
    // pto: %t__tmp_v90
    Tile<TileType::Vec, int32_t, 1, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v181 = Tile<TileType::Vec, int32_t, 1, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v19, v20);
    // pto: %t__tmp_v90
    uint64_t v182 = (uint64_t) v27;
    TASSIGN(v181, v182);
    TCI<Tile<TileType::Vec, int32_t, 1, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>, int32_t, 0>(v181, v16);
    set_flag(PIPE_S, PIPE_V, EVENT_ID1);
    // pto: %t__tmp_v91
    Tile<TileType::Vec, float, 1, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v183 = Tile<TileType::Vec, float, 1, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v19, v20);
    // pto: %t__tmp_v91
    uint64_t v184 = (uint64_t) v27;
    TASSIGN(v183, v184);
    wait_flag(PIPE_S, PIPE_V, EVENT_ID1);
    TCVT(v183, v181, v12, v11);
    // pto: %qrp_tail_col_inline1659__ssa_v0
    Tile<TileType::Vec, float, 8, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v185 = Tile<TileType::Vec, float, 8, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v18, v20);
    // pto: %qrp_tail_col_inline1659__ssa_v0
    uint64_t v186 = (uint64_t) v28;
    TASSIGN(v185, v186);
    pipe_barrier(PIPE_V);
    TCOLEXPANDMUL(v185, v179, v183);
    // pto: %t__tmp_v92
    Tile<TileType::Vec, float, 8, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v187 = Tile<TileType::Vec, float, 8, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v18, v20);
    // pto: %t__tmp_v92
    uint64_t v188 = (uint64_t) v27;
    TASSIGN(v187, v188);
    pipe_barrier(PIPE_V);
    TMULS(v187, v185, v15);
    // pto: %t__tmp_v93
    Tile<TileType::Vec, int32_t, 8, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v189 = Tile<TileType::Vec, int32_t, 8, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v18, v20);
    // pto: %t__tmp_v93
    uint64_t v190 = (uint64_t) v27;
    TASSIGN(v189, v190);
    pipe_barrier(PIPE_V);
    TCVT(v189, v187, v10, v11);
    // pto: %qrp_tail_dup_f_inline1657__ssa_v0
    Tile<TileType::Vec, float, 8, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v191 = Tile<TileType::Vec, float, 8, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v18, v20);
    // pto: %qrp_tail_dup_f_inline1657__ssa_v0
    uint64_t v192 = (uint64_t) v27;
    TASSIGN(v191, v192);
    pipe_barrier(PIPE_V);
    TCVT(v191, v189, v12, v11);
    // pto: %t__tmp_v94
    Tile<TileType::Vec, float, 8, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v193 = Tile<TileType::Vec, float, 8, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v18, v20);
    // pto: %t__tmp_v94
    uint64_t v194 = (uint64_t) v26;
    TASSIGN(v193, v194);
    pipe_barrier(PIPE_V);
    TMULS(v193, v191, v14);
    // pto: %qrp_tail_lane_inline1662__ssa_v0
    Tile<TileType::Vec, float, 8, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v195 = Tile<TileType::Vec, float, 8, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v18, v20);
    // pto: %qrp_tail_lane_inline1662__ssa_v0
    uint64_t v196 = (uint64_t) v26;
    TASSIGN(v195, v196);
    pipe_barrier(PIPE_V);
    TSUB(v195, v185, v193);
    // pto: %t__tmp_v95
    Tile<TileType::Vec, float, 8, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v197 = Tile<TileType::Vec, float, 8, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v18, v20);
    // pto: %t__tmp_v95
    uint64_t v198 = (uint64_t) v28;
    TASSIGN(v197, v198);
    pipe_barrier(PIPE_V);
    TADDS(v197, v185, v17);
    // pto: %t__tmp_v96
    Tile<TileType::Vec, float, 8, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v199 = Tile<TileType::Vec, float, 8, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v18, v20);
    // pto: %t__tmp_v96
    uint64_t v200 = (uint64_t) v25;
    TASSIGN(v199, v200);
    TMULS(v199, v195, v14);
    // pto: %qrp_tail_swap_f_inline1665__ssa_v0
    Tile<TileType::Vec, float, 8, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v201 = Tile<TileType::Vec, float, 8, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v18, v20);
    // pto: %qrp_tail_swap_f_inline1665__ssa_v0
    uint64_t v202 = (uint64_t) v28;
    TASSIGN(v201, v202);
    pipe_barrier(PIPE_V);
    TSUB(v201, v197, v199);
    set_flag(PIPE_V, PIPE_S, EVENT_ID1);
    // pto: %t__tmp_v97
    Tile<TileType::Vec, int32_t, 1, 8, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v203 = Tile<TileType::Vec, int32_t, 1, 8, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v19, v18);
    // pto: %t__tmp_v97
    uint64_t v204 = (uint64_t) v25;
    TASSIGN(v203, v204);
    wait_flag(PIPE_V, PIPE_S, EVENT_ID1);
    TCI<Tile<TileType::Vec, int32_t, 1, 8, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>, int32_t, 0>(v203, v16);
    set_flag(PIPE_S, PIPE_V, EVENT_ID2);
    // pto: %t__tmp_v98
    Tile<TileType::Vec, float, 1, 8, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v205 = Tile<TileType::Vec, float, 1, 8, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v19, v18);
    // pto: %t__tmp_v98
    uint64_t v206 = (uint64_t) v25;
    TASSIGN(v205, v206);
    wait_flag(PIPE_S, PIPE_V, EVENT_ID2);
    TCVT(v205, v203, v12, v11);
    // pto: %qrp_row_seed_inline1664__ssa_v0
    Tile<TileType::Vec, float, 1, 8, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v207 = Tile<TileType::Vec, float, 1, 8, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v19, v18);
    // pto: %qrp_row_seed_inline1664__ssa_v0
    uint64_t v208 = (uint64_t) v24;
    TASSIGN(v207, v208);
    pipe_barrier(PIPE_V);
    TMULS(v207, v205, v13);
    // pto: %t__tmp_v99
    Tile<TileType::Vec, float, 64, 8, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v209 = Tile<TileType::Vec, float, 64, 8, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v20, v18);
    // pto: %t__tmp_v99
    uint64_t v210 = (uint64_t) v25;
    TASSIGN(v209, v210);
    pipe_barrier(PIPE_V);
    TEXPANDS(v209, v17);
    // pto: %qrp_row_grid_inline1656__ssa_v0
    Tile<TileType::Vec, float, 64, 8, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v211 = Tile<TileType::Vec, float, 64, 8, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v20, v18);
    // pto: %qrp_row_grid_inline1656__ssa_v0
    uint64_t v212 = (uint64_t) v25;
    TASSIGN(v211, v212);
    pipe_barrier(PIPE_V);
    TCOLEXPANDMUL(v211, v209, v207);
    // pto: %transpose_tmp
    Tile<TileType::Vec, float, 64, 8, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v213 = Tile<TileType::Vec, float, 64, 8, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v20, v18);
    // pto: %transpose_tmp
    uint64_t v214 = (uint64_t) v24;
    TASSIGN(v213, v214);
    // pto: %qrp_row_offset_inline1655__ssa_v0
    Tile<TileType::Vec, float, 8, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v215 = Tile<TileType::Vec, float, 8, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v18, v20);
    // pto: %qrp_row_offset_inline1655__ssa_v0
    uint64_t v216 = (uint64_t) v23;
    TASSIGN(v215, v216);
    pipe_barrier(PIPE_V);
    TTRANS(v215, v211, v213);
    // pto: %t__tmp_v100
    Tile<TileType::Vec, float, 8, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v217 = Tile<TileType::Vec, float, 8, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v18, v20);
    // pto: %t__tmp_v100
    uint64_t v218 = (uint64_t) v27;
    TASSIGN(v217, v218);
    pipe_barrier(PIPE_V);
    TADD(v217, v191, v215);
    // pto: %qrp_dup_idx_tail_inline1658__ssa_v0
    Tile<TileType::Vec, int32_t, 8, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v219 = Tile<TileType::Vec, int32_t, 8, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v18, v20);
    // pto: %qrp_dup_idx_tail_inline1658__ssa_v0
    uint64_t v220 = (uint64_t) v27;
    TASSIGN(v219, v220);
    pipe_barrier(PIPE_V);
    TCVT(v219, v217, v12, v11);
    // pto: %qrp_gather_tmp_inline1653__ssa_v0
    Tile<TileType::Vec, int32_t, 8, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v221 = Tile<TileType::Vec, int32_t, 8, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v18, v20);
    // pto: %qrp_gather_tmp_inline1653__ssa_v0
    uint64_t v222 = (uint64_t) v25;
    TASSIGN(v221, v222);
    // pto: %t__tmp_v101
    Tile<TileType::Vec, float, 8, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v223 = Tile<TileType::Vec, float, 8, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v57, v20);
    // pto: %t__tmp_v101
    uint64_t v224 = (uint64_t) v24;
    TASSIGN(v223, v224);
    wait_flag(PIPE_MTE2, PIPE_V, EVENT_ID2);
    TCVT(v223, v162, v12, v11);
    // pto: %qrp_cos_il_tail_inline1652__ssa_v0
    Tile<TileType::Vec, float, 8, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v225 = Tile<TileType::Vec, float, 8, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v18, v20);
    // pto: %qrp_cos_il_tail_inline1652__ssa_v0
    uint64_t v226 = (uint64_t) v23;
    TASSIGN(v225, v226);
    pipe_barrier(PIPE_V);
    TGATHER(v225, v223, v219, v221);
    set_flag(PIPE_V, PIPE_MTE3, EVENT_ID2);
    // pto: %t__tmp_v102
    Tile<TileType::Vec, float, 8, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v227 = Tile<TileType::Vec, float, 8, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v57, v20);
    // pto: %t__tmp_v102
    uint64_t v228 = (uint64_t) v24;
    TASSIGN(v227, v228);
    pipe_barrier(PIPE_V);
    wait_flag(PIPE_MTE2, PIPE_V, EVENT_ID3);
    TCVT(v227, v171, v12, v11);
    // pto: %qrp_sin_il_tail_inline1654__ssa_v0
    Tile<TileType::Vec, float, 8, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v229 = Tile<TileType::Vec, float, 8, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v18, v20);
    // pto: %qrp_sin_il_tail_inline1654__ssa_v0
    uint64_t v230 = (uint64_t) v22;
    TASSIGN(v229, v230);
    pipe_barrier(PIPE_V);
    TGATHER(v229, v227, v219, v221);
    // pto: %t__tmp_v103
    Tile<TileType::Vec, float, 8, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v231 = Tile<TileType::Vec, float, 8, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v18, v20);
    // pto: %t__tmp_v103
    uint64_t v232 = (uint64_t) v27;
    TASSIGN(v231, v232);
    pipe_barrier(PIPE_V);
    TMULS(v231, v195, v14);
    // pto: %qrp_tail_sign_inline1677__ssa_v0
    Tile<TileType::Vec, float, 8, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v233 = Tile<TileType::Vec, float, 8, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v18, v20);
    // pto: %qrp_tail_sign_inline1677__ssa_v0
    uint64_t v234 = (uint64_t) v27;
    TASSIGN(v233, v234);
    pipe_barrier(PIPE_V);
    TSUBS(v233, v231, v17);
    // pto: %qrp_sin_signed_tail_inline1688__ssa_v0
    Tile<TileType::Vec, float, 8, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v235 = Tile<TileType::Vec, float, 8, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v18, v20);
    // pto: %qrp_sin_signed_tail_inline1688__ssa_v0
    uint64_t v236 = (uint64_t) v27;
    TASSIGN(v235, v236);
    pipe_barrier(PIPE_V);
    TMUL(v235, v229, v233);
    set_flag(PIPE_V, PIPE_MTE3, EVENT_ID3);
    v225.SetValidShape(v57, v20);
    // pto: %26
    __gm__ float* v237 = PTOAS__GLOBAL_TENSOR_DATA(v44);
    // pto: %26
    int64_t v238 = v57 * v20;
    // pto: %26
    int64_t v239 = v19 * v238;
    // pto: %26
    pto::Shape<1, 1, 1, -1, 64> v240 = pto::Shape<1, 1, 1, -1, 64>(v19, v19, v19, v57, v20);
    // pto: %26
    pto::Stride<-1, -1, -1, -1, -1> v241 = pto::Stride<-1, -1, -1, -1, -1>(v19 * v239, v239, v238, v20, v19);
    // pto: %26
    GlobalTensor<float, pto::Shape<1, 1, 1, -1, 64>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND> v242 = GlobalTensor<float, pto::Shape<1, 1, 1, -1, 64>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND>(v237 + ((v26 + v164 * v20) + v26 * v19), v240, v241);
    wait_flag(PIPE_V, PIPE_MTE3, EVENT_ID2);
    TSTORE(v242, v225);
    v235.SetValidShape(v57, v20);
    // pto: %28
    __gm__ float* v243 = PTOAS__GLOBAL_TENSOR_DATA(v49);
    // pto: %28
    int64_t v244 = v57 * v20;
    // pto: %28
    int64_t v245 = v19 * v244;
    // pto: %28
    pto::Shape<1, 1, 1, -1, 64> v246 = pto::Shape<1, 1, 1, -1, 64>(v19, v19, v19, v57, v20);
    // pto: %28
    pto::Stride<-1, -1, -1, -1, -1> v247 = pto::Stride<-1, -1, -1, -1, -1>(v19 * v245, v245, v244, v20, v19);
    // pto: %28
    GlobalTensor<float, pto::Shape<1, 1, 1, -1, 64>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND> v248 = GlobalTensor<float, pto::Shape<1, 1, 1, -1, 64>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND>(v243 + ((v26 + v164 * v20) + v26 * v19), v246, v247);
    wait_flag(PIPE_V, PIPE_MTE3, EVENT_ID3);
    TSTORE(v248, v235);
    // pto: %t__tmp_v106
    Tile<TileType::Vec, int32_t, 8, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v249 = Tile<TileType::Vec, int32_t, 8, 64, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v18, v20);
    // pto: %t__tmp_v106
    uint64_t v250 = (uint64_t) v28;
    TASSIGN(v249, v250);
    TCVT(v249, v201, v12, v11);
    set_flag(PIPE_V, PIPE_MTE3, EVENT_ID4);
    v249.SetValidShape(v57, v20);
    // pto: %30
    __gm__ int32_t* v251 = PTOAS__GLOBAL_TENSOR_DATA(v54);
    // pto: %30
    int64_t v252 = v57 * v20;
    // pto: %30
    int64_t v253 = v19 * v252;
    // pto: %30
    pto::Shape<1, 1, 1, -1, 64> v254 = pto::Shape<1, 1, 1, -1, 64>(v19, v19, v19, v57, v20);
    // pto: %30
    pto::Stride<-1, -1, -1, -1, -1> v255 = pto::Stride<-1, -1, -1, -1, -1>(v19 * v253, v253, v252, v20, v19);
    // pto: %30
    GlobalTensor<int32_t, pto::Shape<1, 1, 1, -1, 64>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND> v256 = GlobalTensor<int32_t, pto::Shape<1, 1, 1, -1, 64>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND>(v251 + ((v26 + v164 * v20) + v26 * v19), v254, v255);
    wait_flag(PIPE_V, PIPE_MTE3, EVENT_ID4);
    TSTORE(v256, v249);
  }
  #endif // __DAV_VEC__

  ptoas_auto_sync_tail(PTOAutoSyncTailMode::kBarrierAll);
  return;
}
// --- Kernel entry point ---
extern "C" __aicore__ __attribute__((always_inline)) void kernel_entry(__gm__ int64_t* args)
{
#if !defined(__CPU_SIM) && !defined(__COSTMODEL)
    // Reset AI Core atomic mode inherited from a prior kernel.
    set_atomic_none();
#endif

    // Read logical SPMD block identity from runtime dispatch payload
    int32_t __pypto_spmd_block_idx = get_block_idx(args);
    int32_t __pypto_spmd_block_num = get_block_num(args);

    // Unpack tensor: rope_cos_view_inline1679__ssa_v0
    __gm__ Tensor* rope_cos_view_inline1679__ssa_v0_tensor = reinterpret_cast<__gm__ Tensor*>(args[0]);
    __gm__ bfloat16_t* rope_cos_view_inline1679__ssa_v0 = reinterpret_cast<__gm__ bfloat16_t*>(rope_cos_view_inline1679__ssa_v0_tensor->buffer.addr) + rope_cos_view_inline1679__ssa_v0_tensor->start_offset;

    // Unpack tensor: rope_sin_view_inline1674__ssa_v0
    __gm__ Tensor* rope_sin_view_inline1674__ssa_v0_tensor = reinterpret_cast<__gm__ Tensor*>(args[1]);
    __gm__ bfloat16_t* rope_sin_view_inline1674__ssa_v0 = reinterpret_cast<__gm__ bfloat16_t*>(rope_sin_view_inline1674__ssa_v0_tensor->buffer.addr) + rope_sin_view_inline1674__ssa_v0_tensor->start_offset;

    // Unpack tensor: rope_cos_il_view_inline1670__ssa_v0
    __gm__ Tensor* rope_cos_il_view_inline1670__ssa_v0_tensor = reinterpret_cast<__gm__ Tensor*>(args[2]);
    __gm__ float* rope_cos_il_view_inline1670__ssa_v0 = reinterpret_cast<__gm__ float*>(rope_cos_il_view_inline1670__ssa_v0_tensor->buffer.addr) + rope_cos_il_view_inline1670__ssa_v0_tensor->start_offset;

    // Unpack tensor: rope_sin_signed_view_inline1668__ssa_v0
    __gm__ Tensor* rope_sin_signed_view_inline1668__ssa_v0_tensor = reinterpret_cast<__gm__ Tensor*>(args[3]);
    __gm__ float* rope_sin_signed_view_inline1668__ssa_v0 = reinterpret_cast<__gm__ float*>(rope_sin_signed_view_inline1668__ssa_v0_tensor->buffer.addr) + rope_sin_signed_view_inline1668__ssa_v0_tensor->start_offset;

    // Unpack tensor: rope_swap_idx_view_inline1694__ssa_v0
    __gm__ Tensor* rope_swap_idx_view_inline1694__ssa_v0_tensor = reinterpret_cast<__gm__ Tensor*>(args[4]);
    __gm__ int32_t* rope_swap_idx_view_inline1694__ssa_v0 = reinterpret_cast<__gm__ int32_t*>(rope_swap_idx_view_inline1694__ssa_v0_tensor->buffer.addr) + rope_swap_idx_view_inline1694__ssa_v0_tensor->start_offset;

    // Unpack scalar: t_dim_inline1682__ssa_v0
    union { uint64_t u64; int64_t val; } t_dim_inline1682__ssa_v0_conv;
    t_dim_inline1682__ssa_v0_conv.u64 = args[5];
    int64_t t_dim_inline1682__ssa_v0 = t_dim_inline1682__ssa_v0_conv.val;

    // Extract dynamic dim: t_dim_inline1682__ssa_v0_1
    int64_t t_dim_inline1682__ssa_v0_1 = static_cast<int64_t>(rope_cos_view_inline1679__ssa_v0_tensor->shapes[0]);

    // Forward to ptoas-generated function
    q_rope_prepare(rope_cos_view_inline1679__ssa_v0, rope_sin_view_inline1674__ssa_v0, rope_cos_il_view_inline1670__ssa_v0, rope_sin_signed_view_inline1668__ssa_v0, rope_swap_idx_view_inline1694__ssa_v0, t_dim_inline1682__ssa_v0, t_dim_inline1682__ssa_v0_1, __pypto_spmd_block_idx, __pypto_spmd_block_num);
}
