// Kernel Function: split_pre_post
// Generated by PyPTO IR Compiler (PTO backend)

#include <cstdint>

#ifndef __gm__
#define __gm__
#endif

#ifndef __aicore__
#if defined(__CPU_SIM)
#define __aicore__
#else
#define __aicore__ [aicore]
#endif
#endif

#include <pto/pto-inst.hpp>
#include "tensor.h"

#include "intrinsic.h"


using namespace pto;


// --- ptoas-generated code ---

template <typename Tensor>
static __aicore__ inline auto PTOAS__GLOBAL_TENSOR_DATA(Tensor &tensor)
    -> decltype(tensor.data()) {
  return tensor.data();
}


enum class PTOAutoSyncTailMode : int {
  kBarrierAll = 0,
  kSetWaitMte3ToSEvent0 = 1,
};

static __aicore__ inline void ptoas_auto_sync_tail(
    PTOAutoSyncTailMode mode = PTOAutoSyncTailMode::kBarrierAll) {
  switch (mode) {
  case PTOAutoSyncTailMode::kSetWaitMte3ToSEvent0:
    set_flag(PIPE_MTE3, PIPE_S, EVENT_ID0);
    wait_flag(PIPE_MTE3, PIPE_S, EVENT_ID0);
    break;
  case PTOAutoSyncTailMode::kBarrierAll:
  default:
    pipe_barrier(PIPE_ALL);
    break;
  }
}

template <typename Ptr>
static __aicore__ inline void PTOAS__DCCI_SINGLE_CACHE_LINE(Ptr ptr) {
  dcci((__gm__ void*)ptr, cache_line_t::SINGLE_CACHE_LINE);
}

static __aicore__ void split_pre_post(__gm__ float* v1, __gm__ float* v2, __gm__ float* v3, __gm__ float* v4, __gm__ float* v5, __gm__ float* v6, int64_t v7, float v8, float v9, int64_t v10, int64_t v11, int32_t v12, int32_t v13) {
  unsigned v14 = 4;
  const int64_t v15 = 32;
  const float v16 = 2.0f;
  const float v17 = 9.99999997E-7f;
  const float v18 = 1.0f;
  const int64_t v19 = 4;
  const int64_t v20 = 8;
  const int64_t v21 = 1;
  const int64_t v22 = 0;
  const int64_t v23 = 320;
  const int64_t v24 = 288;
  const int64_t v25 = 256;
  using T = float;

  #if defined(__DAV_VEC__)
  set_mask_norm();
  set_vector_mask(-1, -1);
  // pto: %inv_rms_inline1463__ssa_v1_view
  int64_t v26 = v10 * v21;
  // pto: %inv_rms_inline1463__ssa_v1_view
  int64_t v27 = v21 * v26;
  // pto: %inv_rms_inline1463__ssa_v1_view
  pto::Shape<1, 1, 1, -1, -1> v28 = pto::Shape<1, 1, 1, -1, -1>(v21, v21, v21, v10, v21);
  // pto: %inv_rms_inline1463__ssa_v1_view
  pto::Stride<-1, -1, -1, -1, -1> v29 = pto::Stride<-1, -1, -1, -1, -1>(v21 * v27, v27, v26, v21, v10);
  // pto: %inv_rms_inline1463__ssa_v1_view
  GlobalTensor<float, pto::Shape<1, 1, 1, -1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::DN> v30 = GlobalTensor<float, pto::Shape<1, 1, 1, -1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::DN>(v1, v28, v29);
  // pto: %post_t_inline1277__ssa_v0_view
  int64_t v31 = v11 * v19;
  // pto: %post_t_inline1277__ssa_v0_view
  int64_t v32 = v21 * v31;
  // pto: %post_t_inline1277__ssa_v0_view
  pto::Shape<1, 1, 1, -1, -1> v33 = pto::Shape<1, 1, 1, -1, -1>(v21, v21, v21, v11, v19);
  // pto: %post_t_inline1277__ssa_v0_view
  pto::Stride<-1, -1, -1, -1, -1> v34 = pto::Stride<-1, -1, -1, -1, -1>(v21 * v32, v32, v31, v19, v21);
  // pto: %post_t_inline1277__ssa_v0_view
  GlobalTensor<float, pto::Shape<1, 1, 1, -1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND> v35 = GlobalTensor<float, pto::Shape<1, 1, 1, -1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND>(v5, v33, v34);
  // pto: %post_tail_store_inline1544__ssa_v0_view
  int64_t v36 = v20 * v20;
  // pto: %post_tail_store_inline1544__ssa_v0_view
  int64_t v37 = v21 * v36;
  // pto: %post_tail_store_inline1544__ssa_v0_view
  pto::Shape<1, 1, 1, -1, -1> v38 = pto::Shape<1, 1, 1, -1, -1>(v21, v21, v21, v20, v20);
  // pto: %post_tail_store_inline1544__ssa_v0_view
  pto::Stride<-1, -1, -1, -1, -1> v39 = pto::Stride<-1, -1, -1, -1, -1>(v21 * v37, v37, v36, v20, v21);
  // pto: %post_tail_store_inline1544__ssa_v0_view
  GlobalTensor<float, pto::Shape<1, 1, 1, -1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND> v40 = GlobalTensor<float, pto::Shape<1, 1, 1, -1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND>(v6, v38, v39);
  // pto: %ob_inline1554__ssa_v0, %14
  int64_t v41 = (int64_t) ((uint64_t) ((int64_t) v12) * (uint64_t) v20);
  // pto: %15
  int64_t v42 = (int64_t) ((uint64_t) v7 - (uint64_t) v41);
  // pto: %16
  int64_t v43 = v42 < v20 ? v42 : v20;
  // pto: %inv_col_inline1450__tile
  Tile<TileType::Vec, float, 8, 1, BLayout::ColMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v44 = Tile<TileType::Vec, float, 8, 1, BLayout::ColMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v20, v21);
  // pto: %inv_col_inline1450__tile
  uint64_t v45 = (uint64_t) v25;
  TASSIGN(v44, v45);
  // pto: %17
  int64_t v46 = v41 < v22 ? v22 : v41;
  // pto: %inv_rms_inline1463__ssa_v1_pview
  __gm__ float* v47 = PTOAS__GLOBAL_TENSOR_DATA(v30);
  // pto: %inv_rms_inline1463__ssa_v1_pview
  int64_t v48 = v20 * v21;
  // pto: %inv_rms_inline1463__ssa_v1_pview
  int64_t v49 = v21 * v48;
  // pto: %inv_rms_inline1463__ssa_v1_pview
  pto::Shape<1, 1, 1, 8, 1> v50 = pto::Shape<1, 1, 1, 8, 1>(v21, v21, v21, v20, v21);
  // pto: %inv_rms_inline1463__ssa_v1_pview
  pto::Stride<-1, -1, -1, -1, -1> v51 = pto::Stride<-1, -1, -1, -1, -1>(v21 * v49, v49, v48, v21, v10);
  // pto: %inv_rms_inline1463__ssa_v1_pview
  GlobalTensor<float, pto::Shape<1, 1, 1, 8, 1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::DN> v52 = GlobalTensor<float, pto::Shape<1, 1, 1, 8, 1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::DN>(v47 + ((v22 + v46 * v21) + v22 * v10), v50, v51);
  TLOAD(v44, v52);
  // pto: %t__tile
  Tile<TileType::Vec, float, 1, 8, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v53 = Tile<TileType::Vec, float, 1, 8, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v21, v20);
  // pto: %t__tile
  uint64_t v54 = (uint64_t) v24;
  TASSIGN(v53, v54);
  // pto: %hc_attn_base__ssa_v0_pview
  pto::Shape<1, 1, 1, 1, 8> v55 = pto::Shape<1, 1, 1, 1, 8>();
  // pto: %hc_attn_base__ssa_v0_pview
  pto::Stride<8, 8, 8, 8, 1> v56 = pto::Stride<8, 8, 8, 8, 1>();
  // pto: %hc_attn_base__ssa_v0_pview
  GlobalTensor<float, pto::Shape<1, 1, 1, 1, 8>, pto::Stride<8, 8, 8, 8, 1>, pto::Layout::ND> v57 = GlobalTensor<float, pto::Shape<1, 1, 1, 1, 8>, pto::Stride<8, 8, 8, 8, 1>, pto::Layout::ND>(v2, v55, v56);
  TLOAD(v53, v57);
  // pto: %pre_base_inline1470__tile
  Tile<TileType::Vec, float, 1, 8, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v58 = Tile<TileType::Vec, float, 1, 8, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v21, v20);
  // pto: %pre_base_inline1470__tile
  uint64_t v59 = (uint64_t) v24;
  TASSIGN(v58, v59);
  // pto: %0
  Tile<TileType::Vec, float, 8, 8, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v60 = Tile<TileType::Vec, float, 8, 8, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v20, v20);
  // pto: %0
  uint64_t v61 = (uint64_t) v23;
  TASSIGN(v60, v61);
  // pto: %mixes_raw_inline1505__ssa_v1_pview
  pto::Shape<1, 1, 1, 8, 8> v62 = pto::Shape<1, 1, 1, 8, 8>();
  // pto: %mixes_raw_inline1505__ssa_v1_pview
  pto::Stride<256, 256, 256, 32, 1> v63 = pto::Stride<256, 256, 256, 32, 1>();
  // pto: %mixes_raw_inline1505__ssa_v1_pview
  GlobalTensor<float, pto::Shape<1, 1, 1, 8, 8>, pto::Stride<256, 256, 256, 32, 1>, pto::Layout::ND> v64 = GlobalTensor<float, pto::Shape<1, 1, 1, 8, 8>, pto::Stride<256, 256, 256, 32, 1>, pto::Layout::ND>(v3 + (v22 + v46 * v15), v62, v63);
  TLOAD(v60, v64);
  set_flag(PIPE_MTE2, PIPE_V, EVENT_ID0);
  // pto: %1
  Tile<TileType::Vec, float, 8, 8, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v65 = Tile<TileType::Vec, float, 8, 8, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v20, v20);
  // pto: %1
  uint64_t v66 = (uint64_t) v23;
  TASSIGN(v65, v66);
  wait_flag(PIPE_MTE2, PIPE_V, EVENT_ID0);
  TROWEXPANDMUL(v65, v60, v44);
  // pto: %pre_scaled_inline1447__tile
  Tile<TileType::Vec, float, 8, 8, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v67 = Tile<TileType::Vec, float, 8, 8, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v20, v20);
  // pto: %pre_scaled_inline1447__tile
  uint64_t v68 = (uint64_t) v23;
  TASSIGN(v67, v68);
  pipe_barrier(PIPE_V);
  TMULS(v67, v65, v8);
  // pto: %2
  Tile<TileType::Vec, float, 8, 8, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v69 = Tile<TileType::Vec, float, 8, 8, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v20, v20);
  // pto: %2
  uint64_t v70 = (uint64_t) v22;
  TASSIGN(v69, v70);
  TCOLEXPAND(v69, v58);
  set_flag(PIPE_V, PIPE_MTE2, EVENT_ID0);
  // pto: %pre_logits_inline1455__tile
  Tile<TileType::Vec, float, 8, 8, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v71 = Tile<TileType::Vec, float, 8, 8, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v20, v20);
  // pto: %pre_logits_inline1455__tile
  uint64_t v72 = (uint64_t) v23;
  TASSIGN(v71, v72);
  pipe_barrier(PIPE_V);
  TADD(v71, v67, v69);
  // pto: %3
  Tile<TileType::Vec, float, 8, 8, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v73 = Tile<TileType::Vec, float, 8, 8, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v20, v20);
  // pto: %3
  uint64_t v74 = (uint64_t) v23;
  TASSIGN(v73, v74);
  pipe_barrier(PIPE_V);
  TNEG(v73, v71);
  // pto: %4
  Tile<TileType::Vec, float, 8, 8, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v75 = Tile<TileType::Vec, float, 8, 8, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v20, v20);
  // pto: %4
  uint64_t v76 = (uint64_t) v23;
  TASSIGN(v75, v76);
  pipe_barrier(PIPE_V);
  TEXP(v75, v73);
  // pto: %5
  Tile<TileType::Vec, float, 8, 8, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v77 = Tile<TileType::Vec, float, 8, 8, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v20, v20);
  // pto: %5
  uint64_t v78 = (uint64_t) v23;
  TASSIGN(v77, v78);
  pipe_barrier(PIPE_V);
  TADDS(v77, v75, v18);
  // pto: %pre_sig_inline1452__tile
  Tile<TileType::Vec, float, 8, 8, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v79 = Tile<TileType::Vec, float, 8, 8, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v20, v20);
  // pto: %pre_sig_inline1452__tile
  uint64_t v80 = (uint64_t) v22;
  TASSIGN(v79, v80);
  pipe_barrier(PIPE_V);
  TRECIP(v79, v77);
  // pto: %pre_val_inline1448__tile
  Tile<TileType::Vec, float, 8, 8, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v81 = Tile<TileType::Vec, float, 8, 8, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v20, v20);
  // pto: %pre_val_inline1448__tile
  uint64_t v82 = (uint64_t) v23;
  TASSIGN(v81, v82);
  pipe_barrier(PIPE_V);
  TADDS(v81, v79, v17);
  set_flag(PIPE_V, PIPE_MTE3, EVENT_ID0);
  // pto: %pre_val_store_inline1529__ssa_v0_pview
  pto::Shape<1, 1, 1, 8, 8> v83 = pto::Shape<1, 1, 1, 8, 8>();
  // pto: %pre_val_store_inline1529__ssa_v0_pview
  pto::Stride<64, 64, 64, 8, 1> v84 = pto::Stride<64, 64, 64, 8, 1>();
  // pto: %pre_val_store_inline1529__ssa_v0_pview
  GlobalTensor<float, pto::Shape<1, 1, 1, 8, 8>, pto::Stride<64, 64, 64, 8, 1>, pto::Layout::ND> v85 = GlobalTensor<float, pto::Shape<1, 1, 1, 8, 8>, pto::Stride<64, 64, 64, 8, 1>, pto::Layout::ND>(v4 + (v22 + v46 * v20), v83, v84);
  wait_flag(PIPE_V, PIPE_MTE3, EVENT_ID0);
  TSTORE(v85, v81);
  set_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID0);
  // pto: %6
  Tile<TileType::Vec, float, 1, 8, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v86 = Tile<TileType::Vec, float, 1, 8, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v21, v20);
  // pto: %6
  uint64_t v87 = (uint64_t) v24;
  TASSIGN(v86, v87);
  // pto: %20
  pto::Shape<1, 1, 1, 1, 8> v88 = pto::Shape<1, 1, 1, 1, 8>();
  // pto: %20
  pto::Stride<8, 8, 8, 8, 1> v89 = pto::Stride<8, 8, 8, 8, 1>();
  // pto: %20
  GlobalTensor<float, pto::Shape<1, 1, 1, 1, 8>, pto::Stride<8, 8, 8, 8, 1>, pto::Layout::ND> v90 = GlobalTensor<float, pto::Shape<1, 1, 1, 1, 8>, pto::Stride<8, 8, 8, 8, 1>, pto::Layout::ND>(v2 + v14, v88, v89);
  wait_flag(PIPE_V, PIPE_MTE2, EVENT_ID0);
  TLOAD(v86, v90);
  // pto: %post_base_inline1472__tile
  Tile<TileType::Vec, float, 1, 8, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v91 = Tile<TileType::Vec, float, 1, 8, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v21, v20);
  // pto: %post_base_inline1472__tile
  uint64_t v92 = (uint64_t) v24;
  TASSIGN(v91, v92);
  // pto: %7
  Tile<TileType::Vec, float, 8, 8, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v93 = Tile<TileType::Vec, float, 8, 8, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v20, v20);
  // pto: %7
  uint64_t v94 = (uint64_t) v23;
  TASSIGN(v93, v94);
  // pto: %22
  pto::Shape<1, 1, 1, 8, 8> v95 = pto::Shape<1, 1, 1, 8, 8>();
  // pto: %22
  pto::Stride<256, 256, 256, 32, 1> v96 = pto::Stride<256, 256, 256, 32, 1>();
  // pto: %22
  GlobalTensor<float, pto::Shape<1, 1, 1, 8, 8>, pto::Stride<256, 256, 256, 32, 1>, pto::Layout::ND> v97 = GlobalTensor<float, pto::Shape<1, 1, 1, 8, 8>, pto::Stride<256, 256, 256, 32, 1>, pto::Layout::ND>(v3 + (v19 + v46 * v15), v95, v96);
  wait_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID0);
  TLOAD(v93, v97);
  set_flag(PIPE_MTE2, PIPE_V, EVENT_ID1);
  // pto: %8
  Tile<TileType::Vec, float, 8, 8, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v98 = Tile<TileType::Vec, float, 8, 8, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v20, v20);
  // pto: %8
  uint64_t v99 = (uint64_t) v23;
  TASSIGN(v98, v99);
  wait_flag(PIPE_MTE2, PIPE_V, EVENT_ID1);
  TROWEXPANDMUL(v98, v93, v44);
  // pto: %post_scaled_inline1461__tile
  Tile<TileType::Vec, float, 8, 8, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v100 = Tile<TileType::Vec, float, 8, 8, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v20, v20);
  // pto: %post_scaled_inline1461__tile
  uint64_t v101 = (uint64_t) v23;
  TASSIGN(v100, v101);
  pipe_barrier(PIPE_V);
  TMULS(v100, v98, v9);
  // pto: %9
  Tile<TileType::Vec, float, 8, 8, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v102 = Tile<TileType::Vec, float, 8, 8, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v20, v20);
  // pto: %9
  uint64_t v103 = (uint64_t) v22;
  TASSIGN(v102, v103);
  TCOLEXPAND(v102, v91);
  // pto: %post_logits_inline1506__tile
  Tile<TileType::Vec, float, 8, 8, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v104 = Tile<TileType::Vec, float, 8, 8, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v20, v20);
  // pto: %post_logits_inline1506__tile
  uint64_t v105 = (uint64_t) v23;
  TASSIGN(v104, v105);
  pipe_barrier(PIPE_V);
  TADD(v104, v100, v102);
  // pto: %10
  Tile<TileType::Vec, float, 8, 8, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v106 = Tile<TileType::Vec, float, 8, 8, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v20, v20);
  // pto: %10
  uint64_t v107 = (uint64_t) v23;
  TASSIGN(v106, v107);
  pipe_barrier(PIPE_V);
  TNEG(v106, v104);
  // pto: %11
  Tile<TileType::Vec, float, 8, 8, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v108 = Tile<TileType::Vec, float, 8, 8, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v20, v20);
  // pto: %11
  uint64_t v109 = (uint64_t) v23;
  TASSIGN(v108, v109);
  pipe_barrier(PIPE_V);
  TEXP(v108, v106);
  // pto: %12
  Tile<TileType::Vec, float, 8, 8, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v110 = Tile<TileType::Vec, float, 8, 8, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v20, v20);
  // pto: %12
  uint64_t v111 = (uint64_t) v23;
  TASSIGN(v110, v111);
  pipe_barrier(PIPE_V);
  TADDS(v110, v108, v18);
  // pto: %post_sig_inline1444__tile
  Tile<TileType::Vec, float, 8, 8, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v112 = Tile<TileType::Vec, float, 8, 8, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v20, v20);
  // pto: %post_sig_inline1444__tile
  uint64_t v113 = (uint64_t) v22;
  TASSIGN(v112, v113);
  pipe_barrier(PIPE_V);
  TRECIP(v112, v110);
  // pto: %post_pad_inline1489__tile
  Tile<TileType::Vec, float, 8, 8, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v114 = Tile<TileType::Vec, float, 8, 8, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v20, v20);
  // pto: %post_pad_inline1489__tile
  uint64_t v115 = (uint64_t) v23;
  TASSIGN(v114, v115);
  pipe_barrier(PIPE_V);
  TMULS(v114, v112, v16);
  set_flag(PIPE_V, PIPE_MTE3, EVENT_ID1);
  // pto: %23
  wait_flag(PIPE_V, PIPE_MTE3, EVENT_ID1);
  if (v43 == v20) {
    // pto: %13
    Tile<TileType::Vec, float, 8, 8, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v116 = Tile<TileType::Vec, float, 8, 8, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v20, v19);
    // pto: %13
    uint64_t v117 = (uint64_t) v23;
    TASSIGN(v116, v117);
    // pto: %slice_view
    Tile<TileType::Vec, float, 8, 8, BLayout::RowMajor, 8, 4, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v118;
    // pto: %slice_view
    Tile<TileType::Vec, float, 8, 8, BLayout::RowMajor, 8, 4, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v119 = v118;
    // pto: %slice_view
    uint64_t v120 = (uint64_t) v23;
    TASSIGN(v119, v120);
    // pto: %post_t_inline1277__ssa_v0_pview
    pto::Shape<1, 1, 1, 8, 4> v121 = pto::Shape<1, 1, 1, 8, 4>();
    // pto: %post_t_inline1277__ssa_v0_pview
    pto::Stride<32, 32, 32, 4, 1> v122 = pto::Stride<32, 32, 32, 4, 1>();
    // pto: %post_t_inline1277__ssa_v0_pview
    GlobalTensor<float, pto::Shape<1, 1, 1, 8, 4>, pto::Stride<32, 32, 32, 4, 1>, pto::Layout::ND> v123 = GlobalTensor<float, pto::Shape<1, 1, 1, 8, 4>, pto::Stride<32, 32, 32, 4, 1>, pto::Layout::ND>(v5 + (v22 + v46 * v19), v121, v122);
    TSTORE(v123, v119);
  } else {
    // pto: %post_tail_store_inline1544__ssa_v0_pview
    pto::Shape<1, 1, 1, 8, 8> v124 = pto::Shape<1, 1, 1, 8, 8>();
    // pto: %post_tail_store_inline1544__ssa_v0_pview
    pto::Stride<64, 64, 64, 8, 1> v125 = pto::Stride<64, 64, 64, 8, 1>();
    // pto: %post_tail_store_inline1544__ssa_v0_pview
    GlobalTensor<float, pto::Shape<1, 1, 1, 8, 8>, pto::Stride<64, 64, 64, 8, 1>, pto::Layout::ND> v126 = GlobalTensor<float, pto::Shape<1, 1, 1, 8, 8>, pto::Stride<64, 64, 64, 8, 1>, pto::Layout::ND>(v6, v124, v125);
    TSTORE(v126, v114);
    set_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID1);
    // pto: %post_tile_inline1483__ssa_v0
    Tile<TileType::Vec, float, 8, 8, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v127 = Tile<TileType::Vec, float, 8, 8, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v43, v19);
    // pto: %post_tile_inline1483__ssa_v0
    uint64_t v128 = (uint64_t) v23;
    TASSIGN(v127, v128);
    // pto: %post_tail_store_inline1544__tile_pview
    __gm__ float* v129 = PTOAS__GLOBAL_TENSOR_DATA(v40);
    // pto: %post_tail_store_inline1544__tile_pview
    int64_t v130 = v43 * v20;
    // pto: %post_tail_store_inline1544__tile_pview
    int64_t v131 = v21 * v130;
    // pto: %post_tail_store_inline1544__tile_pview
    pto::Shape<1, 1, 1, -1, 4> v132 = pto::Shape<1, 1, 1, -1, 4>(v21, v21, v21, v43, v19);
    // pto: %post_tail_store_inline1544__tile_pview
    pto::Stride<-1, -1, -1, -1, -1> v133 = pto::Stride<-1, -1, -1, -1, -1>(v21 * v131, v131, v130, v20, v21);
    // pto: %post_tail_store_inline1544__tile_pview
    GlobalTensor<float, pto::Shape<1, 1, 1, -1, 4>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND> v134 = GlobalTensor<float, pto::Shape<1, 1, 1, -1, 4>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND>(v129 + ((v22 + v22 * v20) + v22 * v21), v132, v133);
    wait_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID1);
    TLOAD(v127, v134);
    set_flag(PIPE_MTE2, PIPE_MTE3, EVENT_ID0);
    // pto: %26
    __gm__ float* v135 = PTOAS__GLOBAL_TENSOR_DATA(v35);
    // pto: %26
    int64_t v136 = v43 * v19;
    // pto: %26
    int64_t v137 = v21 * v136;
    // pto: %26
    pto::Shape<1, 1, 1, -1, 4> v138 = pto::Shape<1, 1, 1, -1, 4>(v21, v21, v21, v43, v19);
    // pto: %26
    pto::Stride<-1, -1, -1, -1, -1> v139 = pto::Stride<-1, -1, -1, -1, -1>(v21 * v137, v137, v136, v19, v21);
    // pto: %26
    GlobalTensor<float, pto::Shape<1, 1, 1, -1, 4>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND> v140 = GlobalTensor<float, pto::Shape<1, 1, 1, -1, 4>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND>(v135 + ((v22 + v46 * v19) + v22 * v21), v138, v139);
    wait_flag(PIPE_MTE2, PIPE_MTE3, EVENT_ID0);
    TSTORE(v140, v127);
  }
  #endif // __DAV_VEC__

  ptoas_auto_sync_tail(PTOAutoSyncTailMode::kBarrierAll);
  return;
}
// --- Kernel entry point ---
extern "C" __aicore__ __attribute__((always_inline)) void kernel_entry(__gm__ int64_t* args)
{
#if !defined(__CPU_SIM) && !defined(__COSTMODEL)
    // Reset AI Core atomic mode inherited from a prior kernel.
    set_atomic_none();
#endif

    // Read logical SPMD block identity from runtime dispatch payload
    int32_t __pypto_spmd_block_idx = get_block_idx(args);
    int32_t __pypto_spmd_block_num = get_block_num(args);

    // Unpack tensor: inv_rms_inline1463__ssa_v1
    __gm__ Tensor* inv_rms_inline1463__ssa_v1_tensor = reinterpret_cast<__gm__ Tensor*>(args[0]);
    __gm__ float* inv_rms_inline1463__ssa_v1 = reinterpret_cast<__gm__ float*>(inv_rms_inline1463__ssa_v1_tensor->buffer.addr) + inv_rms_inline1463__ssa_v1_tensor->start_offset;

    // Unpack tensor: hc_attn_base__ssa_v0
    __gm__ Tensor* hc_attn_base__ssa_v0_tensor = reinterpret_cast<__gm__ Tensor*>(args[1]);
    __gm__ float* hc_attn_base__ssa_v0 = reinterpret_cast<__gm__ float*>(hc_attn_base__ssa_v0_tensor->buffer.addr) + hc_attn_base__ssa_v0_tensor->start_offset;

    // Unpack tensor: mixes_raw_inline1505__ssa_v1
    __gm__ Tensor* mixes_raw_inline1505__ssa_v1_tensor = reinterpret_cast<__gm__ Tensor*>(args[2]);
    __gm__ float* mixes_raw_inline1505__ssa_v1 = reinterpret_cast<__gm__ float*>(mixes_raw_inline1505__ssa_v1_tensor->buffer.addr) + mixes_raw_inline1505__ssa_v1_tensor->start_offset;

    // Unpack tensor: pre_val_store_inline1529__ssa_v0
    __gm__ Tensor* pre_val_store_inline1529__ssa_v0_tensor = reinterpret_cast<__gm__ Tensor*>(args[3]);
    __gm__ float* pre_val_store_inline1529__ssa_v0 = reinterpret_cast<__gm__ float*>(pre_val_store_inline1529__ssa_v0_tensor->buffer.addr) + pre_val_store_inline1529__ssa_v0_tensor->start_offset;

    // Unpack tensor: post_t_inline1277__ssa_v0
    __gm__ Tensor* post_t_inline1277__ssa_v0_tensor = reinterpret_cast<__gm__ Tensor*>(args[4]);
    __gm__ float* post_t_inline1277__ssa_v0 = reinterpret_cast<__gm__ float*>(post_t_inline1277__ssa_v0_tensor->buffer.addr) + post_t_inline1277__ssa_v0_tensor->start_offset;

    // Unpack tensor: post_tail_store_inline1544__ssa_v0
    __gm__ Tensor* post_tail_store_inline1544__ssa_v0_tensor = reinterpret_cast<__gm__ Tensor*>(args[5]);
    __gm__ float* post_tail_store_inline1544__ssa_v0 = reinterpret_cast<__gm__ float*>(post_tail_store_inline1544__ssa_v0_tensor->buffer.addr) + post_tail_store_inline1544__ssa_v0_tensor->start_offset;

    // Unpack scalar: t_dim_inline1568__ssa_v0
    union { uint64_t u64; int64_t val; } t_dim_inline1568__ssa_v0_conv;
    t_dim_inline1568__ssa_v0_conv.u64 = args[6];
    int64_t t_dim_inline1568__ssa_v0 = t_dim_inline1568__ssa_v0_conv.val;

    // Unpack scalar: scale0_inline1499__ssa_v0
    union { uint64_t u64; float val; } scale0_inline1499__ssa_v0_conv;
    scale0_inline1499__ssa_v0_conv.u64 = args[7];
    float scale0_inline1499__ssa_v0 = scale0_inline1499__ssa_v0_conv.val;

    // Unpack scalar: scale1_inline1530__ssa_v0
    union { uint64_t u64; float val; } scale1_inline1530__ssa_v0_conv;
    scale1_inline1530__ssa_v0_conv.u64 = args[8];
    float scale1_inline1530__ssa_v0 = scale1_inline1530__ssa_v0_conv.val;

    // Extract dynamic dim: t_linear_inline1486__ssa_v0
    int64_t t_linear_inline1486__ssa_v0 = static_cast<int64_t>(inv_rms_inline1463__ssa_v1_tensor->shapes[0]);

    // Extract dynamic dim: t_dim_inline1251__ssa_v0
    int64_t t_dim_inline1251__ssa_v0 = static_cast<int64_t>(post_t_inline1277__ssa_v0_tensor->shapes[0]);

    // Forward to ptoas-generated function
    split_pre_post(inv_rms_inline1463__ssa_v1, hc_attn_base__ssa_v0, mixes_raw_inline1505__ssa_v1, pre_val_store_inline1529__ssa_v0, post_t_inline1277__ssa_v0, post_tail_store_inline1544__ssa_v0, t_dim_inline1568__ssa_v0, scale0_inline1499__ssa_v0, scale1_inline1530__ssa_v0, t_linear_inline1486__ssa_v0, t_dim_inline1251__ssa_v0, __pypto_spmd_block_idx, __pypto_spmd_block_num);
}
