# Copyright (c) PyPTO Contributors.
# This program is free software, you can redistribute it and/or modify it under the terms and conditions of
# CANN Open Software License Agreement Version 2.0 (the "License").
# Please refer to the License for details. You may not use this file except in compliance with the License.
# THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
# INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
# See LICENSE in the root of the software repository for the full text of the License.
# -----------------------------------------------------------------------------------------------------------

"""Tests for distributed intrinsic Call nodes (Step 06).

Distributed primitives are represented as Call nodes with 'dist.*' op names.
These are primarily generated by the lowering pass (Step 07), not user-written.
"""

import pytest
from pypto.pypto_core import DataType, ir


def _span():
    return ir.Span("test", 1, 0)


def _make_var(name):
    return ir.Var(name, ir.ScalarType(DataType.INT32), _span())


# ─── dist.* Call node creation ────────────────────────────────────────────


def test_dist_make_tensor_call():
    """dist.make_tensor Call node can be created."""
    op = ir.Op("dist.make_tensor")
    rt_var = _make_var("rt")
    count = ir.ConstInt(1024, DataType.INT32, _span())
    call = ir.Call(op, [rt_var, count], _span())
    assert call.op.name == "dist.make_tensor"
    assert len(call.args) == 2


def test_dist_tree_reduce_call():
    """dist.tree_reduce Call node can be created."""
    op = ir.Op("dist.tree_reduce")
    rt_var = _make_var("rt")
    leaves_var = _make_var("leaves")
    call = ir.Call(op, [rt_var, leaves_var], _span())
    assert call.op.name == "dist.tree_reduce"
    assert len(call.args) == 2


def test_dist_submit_worker_call():
    """dist.submit_worker Call node can be created."""
    op = ir.Op("dist.submit_worker")
    rt_var = _make_var("rt")
    call = ir.Call(op, [rt_var], _span())
    assert call.op.name == "dist.submit_worker"


def test_dist_submit_orchestrator_call():
    """dist.submit_orchestrator Call node can be created."""
    op = ir.Op("dist.submit_orchestrator")
    rt_var = _make_var("rt")
    call = ir.Call(op, [rt_var], _span())
    assert call.op.name == "dist.submit_orchestrator"


def test_dist_future_get_call():
    """dist.future_get Call node can be created."""
    op = ir.Op("dist.future_get")
    future_var = _make_var("future")
    call = ir.Call(op, [future_var], _span())
    assert call.op.name == "dist.future_get"
    assert len(call.args) == 1


# ─── structural_equal with dist.* calls ──────────────────────────────────


def test_dist_call_structural_equal():
    """Two dist.* Call nodes with same op are structurally equal (no args)."""
    op1 = ir.Op("dist.tree_reduce")
    op2 = ir.Op("dist.tree_reduce")
    c1 = ir.Call(op1, [], _span())
    c2 = ir.Call(op2, [], _span())
    ir.assert_structural_equal(c1, c2)


def test_dist_call_different_op_not_equal():
    """Two dist.* Call nodes with different ops are not equal."""
    op1 = ir.Op("dist.tree_reduce")
    op2 = ir.Op("dist.submit_worker")
    c1 = ir.Call(op1, [], _span())
    c2 = ir.Call(op2, [], _span())
    with pytest.raises(ValueError):
        ir.assert_structural_equal(c1, c2)


if __name__ == "__main__":
    pytest.main([__file__, "-v"])
