(function(){'use strict';
const domains=[{id:'spec',icon:'i-cube',label:'SpecDomain',count:3,meta:'OperatorSpec · Tensor · Shape'},{id:'kernel',icon:'i-flow',label:'KernelDomain',count:5,meta:'GraphNode · Tile · ComputeOp'},{id:'verify',icon:'i-check',label:'VerifyDomain',count:3,meta:'TestCase · CheckResult · Issue'},{id:'profile',icon:'i-history',label:'ProfileDomain',count:4,meta:'Run · Timeline · Metric'},{id:'knowledge',icon:'i-code',label:'KnowledgeDomain',count:2,meta:'Pattern · Recommendation'}];
const objects={matmul:{type:'ComputeOp',id:'compute_op_003',name:'tile.matmul',symbol:'ƒ',status:'designed',props:[['API','tile.matmul'],['operation','matmul'],['inputs','tile_001 · tile_002'],['output','accumulator_01'],['source_ref','kernel.py:42']],constraints:['A、B 的 K 维必须相等','输入 Tile dtype 必须为 FP16','Accumulator 初始化值为 0'],evidence:[['compile_pass','Pass 18 · LowerToTile'],['shape_check','Run 003 · passed'],['profile_run','待采集']],actions:['inspect','analyze_precision','change_layout','profile']},tile_a:{type:'Tile',id:'tile_001',name:'lhs_tile',symbol:'▦',status:'validated',props:[['shape','[32, 128]'],['valid_shape','[32, 100]'],['dtype','FP16'],['memory_space','UB'],['source_ref','kernel.py:38']],constraints:['N 维按 16 对齐','UB capacity 足够','valid region 由 mask 处理'],evidence:[['compile_pass','Pass 32 · AllocateMemoryAddr'],['capacity_check','92% · warning'],['profile_run','Run 003 · 12.4 μs']],actions:['change_tile_shape','check_capacity','profile']},tensor_a:{type:'Tensor',id:'tensor_a',name:'A',symbol:'T',status:'specified',props:[['shape','[4096, 4096]'],['dtype','FP16'],['device','GM'],['layout','row_major'],['source_ref','op_spec_001']],constraints:['shape 必须为 2D','dtype 与输出保持一致'],evidence:[['shape_check','Run 003 · passed'],['graph_link','consumed by tile.load']],actions:['inspect','infer_shape','analyze_memory']},tensor_b:{type:'Tensor',id:'tensor_b',name:'B',symbol:'T',status:'specified',props:[['shape','[4096, 4096]'],['dtype','FP16'],['device','GM'],['layout','col_major'],['source_ref','op_spec_001']],constraints:['K 维与 A 相等'],evidence:[['shape_check','Run 003 · passed']],actions:['inspect','infer_shape']},tile_c:{type:'Tile',id:'tile_004',name:'output_tile',symbol:'▦',status:'implemented',props:[['shape','[32, 128]'],['valid_shape','[32, 100]'],['dtype','FP16'],['memory_space','UB'],['source_ref','kernel.py:51']],constraints:['store 前必须完成 barrier'],evidence:[['compile_pass','Pass 41 · RuntimeScopes'],['sync_check','barrier_02 · passed']],actions:['inspect','insert_sync','profile']},move_load_a:{type:'DataMovement',id:'move_001',name:'tile.load A',symbol:'↘',status:'implemented',props:[['direction','GM → UB'],['bytes','1.0 MB'],['source_ref','kernel.py:38'],['parent_id','region_01']],constraints:['GM 地址按 32B 对齐'],evidence:[['compile_pass','Pass 27 · LowerDataMovement']],actions:['inspect','analyze_memory']},move_store:{type:'DataMovement',id:'move_004',name:'tile.store O',symbol:'↗',status:'implemented',props:[['direction','UB → GM'],['bytes','512 KB'],['source_ref','kernel.py:51'],['parent_id','region_01']],constraints:['store 必须在 compute 完成后'],evidence:[['compile_pass','Pass 41 · RuntimeScopes']],actions:['inspect','insert_sync']}};
const defaultObject=objects.matmul;const state={object:'matmul',view:'graph',zoom:100};const $=s=>document.querySelector(s);const $$=s=>Array.from(document.querySelectorAll(s));
function esc(v){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function renderDomains(){ $('#domainList').innerHTML=domains.map(d=>`<button class="domain-item${d.id==='kernel'?' active':''}" data-domain="${d.id}"><svg><use href="#${d.icon}"/></svg><span><strong>${d.label}</strong><small>${d.meta}</small></span><small>${d.count}</small></button>`).join('') }
function renderInspector(key){const o=objects[key]||defaultObject;state.object=key;$('#inspectorTitle').textContent=o.name;$('#inspectorId').textContent=o.id;$('#inspectorBody').innerHTML=`<section class="inspector-section"><div class="object-hero"><span class="object-symbol">${esc(o.symbol)}</span><div><strong>${esc(o.type)}</strong><small>${esc(o.status)} · version 3</small></div></div></section><section class="inspector-section"><h3>Properties</h3><dl class="kv-list">${o.props.map(p=>`<dt>${esc(p[0])}</dt><dd>${esc(p[1])}</dd>`).join('')}</dl></section><section class="inspector-section"><h3>Constraints <span class="micro-status">${o.constraints.length} rules</span></h3>${o.constraints.map(c=>`<div class="constraint"><svg><use href="#i-check"/></svg><span>${esc(c)}</span></div>`).join('')}</section><section class="inspector-section"><h3>Evidence</h3>${o.evidence.map(e=>`<div class="evidence-row"><span><svg><use href="#i-check"/></svg>${esc(e[0])}</span><code>${esc(e[1])}</code></div>`).join('')}</section><section class="inspector-section"><h3>Agent actions</h3><div class="action-list">${o.actions.map(a=>`<span class="action-tag">${esc(a)}</span>`).join('')}</div></section>`;$$('.graph-node').forEach(n=>n.classList.toggle('selected',n.dataset.object===key));}
function renderMemory(){const rows=[['GM','Global Memory','1.0 GB','68%','#7897ff'],['L2','Cache','256 MB','54%','#9b8bd7'],['UB','Unified Buffer','192 KB','92%','#f0b35b'],['L0C','Matrix Buffer','64 KB','46%','#4bd092']];$('#memoryStack').innerHTML=rows.map(r=>`<div class="memory-row"><div><strong>${r[0]}</strong><small>${r[1]}</small></div><div class="memory-bar"><i style="width:${r[3]};background:${r[4]}"></i></div><em>${r[3]}</em></div>`).join('');$('#matrixGrid').innerHTML=Array.from({length:128},(_,i)=>`<i title="cell ${i+1}"></i>`).join('')}
function renderPipeline(){const rows=[['Load A','load',5,22],['Load B','load',19,22],['Compute','compute',32,43],['Store O','store',77,16]];$('#pipelineLane').innerHTML=rows.map(r=>`<div class="pipeline-row"><label>${r[0]}</label><div class="track"><span class="bar ${r[1]}" style="left:${r[2]}%;width:${r[3]}%">${r[0]}</span>${r[0]==='Compute'?'<i class="sync-mark" style="left:74%"></i>':''}</div></div>`).join('')}
function renderValidation(){$('#checkList').innerHTML=[['Shape constraints','12 / 12 passed','check'],['DType & layout','8 / 8 passed','check'],['Memory capacity','3 / 4 passed','warn'],['Golden precision','max error 0.00098','check']].map(r=>`<div class="check-item"><span class="check-icon ${r[2]==='warn'?'warn':''}"><svg><use href="#i-${r[2]==='warn'?'alert':'check'}"/></svg></span><div><strong>${r[0]}</strong><small>${r[1]}</small></div></div>`).join('')}
function renderEvidence(){const items=[['OperatorSpec','op_spec_001 · 需求规格','specified'],['GraphNode','node_03 · Graph IR','designed'],['ComputeOp','compute_op_003 · kernel.py:42','implemented'],['Run','run_003 · compile + test','validated'],['Metric','metric_003 · latency 12.4 μs','profiled']];$('#evidenceFlow').innerHTML=items.map((r,i)=>`<div class="evidence-node"><span class="evidence-number">0${i+1}</span><div><strong>${r[0]}</strong><small>${r[1]}</small></div><em>${r[2]}</em></div>`).join('')}
function showToast(message){const t=$('#toast');t.textContent=message;t.classList.add('show');clearTimeout(showToast.timer);showToast.timer=setTimeout(()=>t.classList.remove('show'),2200)}
function switchView(view){state.view=view;$$('.view-tab').forEach(b=>{const a=b.dataset.view===view;b.classList.toggle('active',a);b.setAttribute('aria-selected',a)});$$('.view').forEach(v=>v.classList.toggle('active',v.dataset.panel===view));if(view==='memory')renderMemory();if(view==='pipeline')renderPipeline();if(view==='validation')renderValidation();if(view==='evidence')renderEvidence()}
renderDomains();renderInspector('matmul');
$$('.view-tab').forEach(b=>b.addEventListener('click',()=>switchView(b.dataset.view)));
$$('.graph-node').forEach(n=>n.addEventListener('click',()=>renderInspector(n.dataset.object)));
$('#domainList').addEventListener('click',e=>{const b=e.target.closest('[data-domain]');if(b){$$('.domain-item').forEach(x=>x.classList.remove('active'));b.classList.add('active');showToast(`${b.dataset.domain} 已激活 · 可视化视图保持联动`)}});
$('#checkButton').addEventListener('click',()=>showToast(`约束检查完成 · ${objects[state.object].constraints.length} 条规则通过`));$('#profileButton').addEventListener('click',()=>showToast('Profile 已加入队列 · Run 004'));
$('#runButton').addEventListener('click',()=>showToast('验证任务已启动 · 正在生成 Run 004'));$('#rerunButton').addEventListener('click',()=>showToast('正在重新验证 4 个质量门禁'));
$$('[data-select-object]').forEach(b=>b.addEventListener('click',()=>{renderInspector(b.dataset.selectObject);switchView('graph')}));
$('#historyButton').addEventListener('click',()=>{switchView('evidence');showToast('已打开对象变更历史')});
$('#objectSearch').addEventListener('input',e=>{const q=e.target.value.toLowerCase();const match=Object.entries(objects).find(([,o])=>`${o.name} ${o.id} ${o.type}`.toLowerCase().includes(q));if(match)renderInspector(match[0])});
$('#zoomIn').addEventListener('click',()=>{state.zoom=Math.min(130,state.zoom+10);$('#zoomValue').textContent=state.zoom+'%';$('.graph-card').style.setProperty('--zoom',state.zoom/100)});$('#zoomOut').addEventListener('click',()=>{state.zoom=Math.max(80,state.zoom-10);$('#zoomValue').textContent=state.zoom+'%';$('.graph-card').style.setProperty('--zoom',state.zoom/100)});$('#fitGraph').addEventListener('click',()=>{state.zoom=100;$('#zoomValue').textContent='100%';showToast('已适配当前画布')});
})();
