// Kernel Function: kv_hadamard
// Generated by PyPTO IR Compiler (PTO backend)

#include <cstdint>

#ifndef __gm__
#define __gm__
#endif

#ifndef __aicore__
#if defined(__CPU_SIM)
#define __aicore__
#else
#define __aicore__ [aicore]
#endif
#endif

#include <pto/pto-inst.hpp>
#include "tensor.h"

#include "intrinsic.h"


using namespace pto;


// --- ptoas-generated code ---

template <typename Tensor>
static __aicore__ inline auto PTOAS__GLOBAL_TENSOR_DATA(Tensor &tensor)
    -> decltype(tensor.data()) {
  return tensor.data();
}


enum class PTOAutoSyncTailMode : int {
  kBarrierAll = 0,
  kSetWaitMte3ToSEvent0 = 1,
};

static __aicore__ inline void ptoas_auto_sync_tail(
    PTOAutoSyncTailMode mode = PTOAutoSyncTailMode::kBarrierAll) {
  switch (mode) {
  case PTOAutoSyncTailMode::kSetWaitMte3ToSEvent0:
    set_flag(PIPE_MTE3, PIPE_S, EVENT_ID0);
    wait_flag(PIPE_MTE3, PIPE_S, EVENT_ID0);
    break;
  case PTOAutoSyncTailMode::kBarrierAll:
  default:
    pipe_barrier(PIPE_ALL);
    break;
  }
}

template <typename Ptr>
static __aicore__ inline void PTOAS__DCCI_SINGLE_CACHE_LINE(Ptr ptr) {
  dcci((__gm__ void*)ptr, cache_line_t::SINGLE_CACHE_LINE);
}

static __aicore__ void kv_hadamard(__gm__ bfloat16_t* v1, __gm__ float* v2, __gm__ bfloat16_t* v3, int32_t v4, int32_t v5) {
  const int64_t v6 = 64;
  const int64_t v7 = 16;
  const int64_t v8 = 128;
  const int64_t v9 = 4096;
  const int64_t v10 = 0;
  using T = float;

  #if defined(__DAV_CUBE__)
  // pto: %had_blk_inline2088__ssa_v0, %0
  int64_t v11 = (int64_t) ((uint64_t) ((int64_t) v4) * (uint64_t) v7);
  // pto: %kv_proj_tile_inline2072__tile
  Tile<TileType::Mat, bfloat16_t, 16, 128, BLayout::ColMajor, -1, -1, SLayout::RowMajor, 512, PadValue::Null, CompactMode::Null> v12 = Tile<TileType::Mat, bfloat16_t, 16, 128, BLayout::ColMajor, -1, -1, SLayout::RowMajor, 512, PadValue::Null, CompactMode::Null>(v7, v8);
  // pto: %kv_proj_tile_inline2072__tile
  uint64_t v13 = (uint64_t) v10;
  TASSIGN(v12, v13);
  // pto: %1
  int64_t v14 = v11 < v10 ? v10 : v11;
  // pto: %normed_kv_inline2164__ssa_v4_pview
  pto::Shape<1, 1, 1, 16, 128> v15 = pto::Shape<1, 1, 1, 16, 128>();
  // pto: %normed_kv_inline2164__ssa_v4_pview
  pto::Stride<2048, 2048, 2048, 128, 1> v16 = pto::Stride<2048, 2048, 2048, 128, 1>();
  // pto: %normed_kv_inline2164__ssa_v4_pview
  GlobalTensor<bfloat16_t, pto::Shape<1, 1, 1, 16, 128>, pto::Stride<2048, 2048, 2048, 128, 1>, pto::Layout::ND> v17 = GlobalTensor<bfloat16_t, pto::Shape<1, 1, 1, 16, 128>, pto::Stride<2048, 2048, 2048, 128, 1>, pto::Layout::ND>(v1 + (v10 + v14 * v8), v15, v16);
  set_flag(PIPE_MTE1, PIPE_MTE2, EVENT_ID0);
  set_flag(PIPE_M, PIPE_MTE1, EVENT_ID0);
  set_flag(PIPE_FIX, PIPE_M, EVENT_ID0);
  TLOAD(v12, v17);
  set_flag(PIPE_MTE2, PIPE_MTE1, EVENT_ID0);
  wait_flag(PIPE_MTE2, PIPE_MTE1, EVENT_ID0);
  for (int64_t i18 = v10; i18 < v8; i18 += v6) {
    // pto: %hadamard_tile_inline2134__tile
    Tile<TileType::Mat, bfloat16_t, 128, 64, BLayout::ColMajor, -1, -1, SLayout::RowMajor, 512, PadValue::Null, CompactMode::Null> v19 = Tile<TileType::Mat, bfloat16_t, 128, 64, BLayout::ColMajor, -1, -1, SLayout::RowMajor, 512, PadValue::Null, CompactMode::Null>(v8, v6);
    // pto: %hadamard_tile_inline2134__tile
    uint64_t v20 = (uint64_t) v9;
    TASSIGN(v19, v20);
    // pto: %2
    int64_t v21 = i18 < v10 ? v10 : i18;
    // pto: %hadamard_idx__ssa_v0_pview
    pto::Shape<1, 1, 1, 128, 64> v22 = pto::Shape<1, 1, 1, 128, 64>();
    // pto: %hadamard_idx__ssa_v0_pview
    pto::Stride<16384, 16384, 16384, 128, 1> v23 = pto::Stride<16384, 16384, 16384, 128, 1>();
    // pto: %hadamard_idx__ssa_v0_pview
    GlobalTensor<bfloat16_t, pto::Shape<1, 1, 1, 128, 64>, pto::Stride<16384, 16384, 16384, 128, 1>, pto::Layout::ND> v24 = GlobalTensor<bfloat16_t, pto::Shape<1, 1, 1, 128, 64>, pto::Stride<16384, 16384, 16384, 128, 1>, pto::Layout::ND>(v3 + (v10 + v21), v22, v23);
    wait_flag(PIPE_MTE1, PIPE_MTE2, EVENT_ID0);
    TLOAD(v19, v24);
    set_flag(PIPE_MTE2, PIPE_MTE1, EVENT_ID1);
    // pto: %kv_proj_tile_inline2072__tile_Left
    Tile<TileType::Left, bfloat16_t, 16, 128, BLayout::RowMajor, -1, -1, SLayout::RowMajor, 512, PadValue::Null, CompactMode::Null> v25 = Tile<TileType::Left, bfloat16_t, 16, 128, BLayout::RowMajor, -1, -1, SLayout::RowMajor, 512, PadValue::Null, CompactMode::Null>(v7, v8);
    // pto: %kv_proj_tile_inline2072__tile_Left
    uint64_t v26 = (uint64_t) v10;
    TASSIGN(v25, v26);
    wait_flag(PIPE_M, PIPE_MTE1, EVENT_ID0);
    TMOV(v25, v12);
    // pto: %hadamard_tile_inline2134__tile_Right
    Tile<TileType::Right, bfloat16_t, 128, 64, BLayout::RowMajor, -1, -1, SLayout::ColMajor, 512, PadValue::Null, CompactMode::Null> v27 = Tile<TileType::Right, bfloat16_t, 128, 64, BLayout::RowMajor, -1, -1, SLayout::ColMajor, 512, PadValue::Null, CompactMode::Null>(v8, v6);
    // pto: %hadamard_tile_inline2134__tile_Right
    uint64_t v28 = (uint64_t) v10;
    TASSIGN(v27, v28);
    wait_flag(PIPE_MTE2, PIPE_MTE1, EVENT_ID1);
    TMOV(v27, v19);
    set_flag(PIPE_MTE1, PIPE_MTE2, EVENT_ID0);
    set_flag(PIPE_MTE1, PIPE_M, EVENT_ID0);
    // pto: %kv_hadamard_acc_inline2151__tile
    Tile<TileType::Acc, float, 16, 64, BLayout::ColMajor, -1, -1, SLayout::RowMajor, 1024, PadValue::Null, CompactMode::Null> v29 = Tile<TileType::Acc, float, 16, 64, BLayout::ColMajor, -1, -1, SLayout::RowMajor, 1024, PadValue::Null, CompactMode::Null>(v7, v6);
    // pto: %kv_hadamard_acc_inline2151__tile
    uint64_t v30 = (uint64_t) v10;
    TASSIGN(v29, v30);
    wait_flag(PIPE_MTE1, PIPE_M, EVENT_ID0);
    wait_flag(PIPE_FIX, PIPE_M, EVENT_ID0);
    TMATMUL(v29, v25, v27);
    set_flag(PIPE_M, PIPE_MTE1, EVENT_ID0);
    set_flag(PIPE_M, PIPE_FIX, EVENT_ID0);
    // pto: %kv_final_inline2118__iter_v1_pview
    pto::Shape<1, 1, 1, 16, 64> v31 = pto::Shape<1, 1, 1, 16, 64>();
    // pto: %kv_final_inline2118__iter_v1_pview
    pto::Stride<2048, 2048, 2048, 128, 1> v32 = pto::Stride<2048, 2048, 2048, 128, 1>();
    // pto: %kv_final_inline2118__iter_v1_pview
    GlobalTensor<float, pto::Shape<1, 1, 1, 16, 64>, pto::Stride<2048, 2048, 2048, 128, 1>, pto::Layout::ND> v33 = GlobalTensor<float, pto::Shape<1, 1, 1, 16, 64>, pto::Stride<2048, 2048, 2048, 128, 1>, pto::Layout::ND>(v2 + ((v10 + v14 * v8) + v21), v31, v32);
    wait_flag(PIPE_M, PIPE_FIX, EVENT_ID0);
    TSTORE(v33, v29);
    set_flag(PIPE_FIX, PIPE_M, EVENT_ID0);
  }
  wait_flag(PIPE_MTE1, PIPE_MTE2, EVENT_ID0);
  wait_flag(PIPE_M, PIPE_MTE1, EVENT_ID0);
  wait_flag(PIPE_FIX, PIPE_M, EVENT_ID0);
  #endif // __DAV_CUBE__

  ptoas_auto_sync_tail(PTOAutoSyncTailMode::kBarrierAll);
  return;
}
// --- Kernel entry point ---
extern "C" __aicore__ __attribute__((always_inline)) void kernel_entry(__gm__ int64_t* args)
{
#if !defined(__CPU_SIM) && !defined(__COSTMODEL)
    // Reset AI Core atomic mode inherited from a prior kernel.
    set_atomic_none();
#endif

    // Read logical SPMD block identity from runtime dispatch payload
    int32_t __pypto_spmd_block_idx = get_block_idx(args);
    int32_t __pypto_spmd_block_num = get_block_num(args);

    // Unpack tensor: normed_kv_inline2164__ssa_v4
    __gm__ Tensor* normed_kv_inline2164__ssa_v4_tensor = reinterpret_cast<__gm__ Tensor*>(args[0]);
    __gm__ bfloat16_t* normed_kv_inline2164__ssa_v4 = reinterpret_cast<__gm__ bfloat16_t*>(normed_kv_inline2164__ssa_v4_tensor->buffer.addr) + normed_kv_inline2164__ssa_v4_tensor->start_offset;

    // Unpack tensor: kv_final_inline2118__ssa_v0
    __gm__ Tensor* kv_final_inline2118__ssa_v0_tensor = reinterpret_cast<__gm__ Tensor*>(args[1]);
    __gm__ float* kv_final_inline2118__ssa_v0 = reinterpret_cast<__gm__ float*>(kv_final_inline2118__ssa_v0_tensor->buffer.addr) + kv_final_inline2118__ssa_v0_tensor->start_offset;

    // Unpack tensor: hadamard_idx__ssa_v0
    __gm__ Tensor* hadamard_idx__ssa_v0_tensor = reinterpret_cast<__gm__ Tensor*>(args[2]);
    __gm__ bfloat16_t* hadamard_idx__ssa_v0 = reinterpret_cast<__gm__ bfloat16_t*>(hadamard_idx__ssa_v0_tensor->buffer.addr) + hadamard_idx__ssa_v0_tensor->start_offset;

    // Forward to ptoas-generated function
    kv_hadamard(normed_kv_inline2164__ssa_v4, kv_final_inline2118__ssa_v0, hadamard_idx__ssa_v0, __pypto_spmd_block_idx, __pypto_spmd_block_num);
}
