// Kernel Function: qk_pv_aic
// Generated by PyPTO IR Compiler (PTO backend)

#include <cstdint>

#ifndef __gm__
#define __gm__
#endif

#ifndef __aicore__
#if defined(__CPU_SIM)
#define __aicore__
#else
#define __aicore__ [aicore]
#endif
#endif

#include <pto/pto-inst.hpp>
#include "tensor.h"

#include "intrinsic.h"


using namespace pto;


// --- ptoas-generated code ---

template <typename Tensor>
static __aicore__ inline auto PTOAS__GLOBAL_TENSOR_DATA(Tensor &tensor)
    -> decltype(tensor.data()) {
  return tensor.data();
}


enum class PTOAutoSyncTailMode : int {
  kBarrierAll = 0,
  kSetWaitMte3ToSEvent0 = 1,
};

static __aicore__ inline void ptoas_auto_sync_tail(
    PTOAutoSyncTailMode mode = PTOAutoSyncTailMode::kBarrierAll) {
  switch (mode) {
  case PTOAutoSyncTailMode::kSetWaitMte3ToSEvent0:
    set_flag(PIPE_MTE3, PIPE_S, EVENT_ID0);
    wait_flag(PIPE_MTE3, PIPE_S, EVENT_ID0);
    break;
  case PTOAutoSyncTailMode::kBarrierAll:
  default:
    pipe_barrier(PIPE_ALL);
    break;
  }
}

template <typename Ptr>
static __aicore__ inline void PTOAS__DCCI_SINGLE_CACHE_LINE(Ptr ptr) {
  dcci((__gm__ void*)ptr, cache_line_t::SINGLE_CACHE_LINE);
}

static __aicore__ void qk_pv_aic(__gm__ float* v1, __gm__ float* v2, __gm__ float* v3, __gm__ int32_t* v4, __gm__ float* v5, __gm__ int32_t* v6, __gm__ int32_t* v7, __gm__ int32_t* v8, __gm__ bfloat16_t* v9, __gm__ int32_t* v10, __gm__ int32_t* v11, __gm__ bfloat16_t* v12, __gm__ bfloat16_t* v13, __gm__ float* v14, int64_t v15, int64_t v16, int64_t v17, int64_t v18, int64_t v19, int64_t v20, int64_t v21, int64_t v22, int64_t v23, int32_t v24, int32_t v25) {
  const int32_t v26 = 128;
  const int32_t v27 = 32;
  const int64_t v28 = 16;
  const int64_t v29 = -32;
  const int64_t v30 = -128;
  const int64_t v31 = 256;
  const int64_t v32 = 96;
  const int64_t v33 = 64;
  const int64_t v34 = 320;
  const int64_t v35 = 8;
  const int64_t v36 = 24;
  const int64_t v37 = 23;
  const int64_t v38 = 128;
  const int64_t v39 = 5;
  const int64_t v40 = 512;
  const int64_t v41 = 1;
  const int64_t v42 = 8192;
  const int64_t v43 = 0;
  const int64_t v44 = 163840;
  const int64_t v45 = 32768;
  const int64_t v46 = 80;
  const int64_t v47 = 160;
  const int64_t v48 = 240;
  const int32_t v49 = 0;
  const int64_t v50 = 32;
  const int64_t v51 = 1024;
  using T = float;

  #if defined(__DAV_CUBE__)
  // pto: %216
  int64_t v52 = (int64_t) ((uint64_t) v20 * (uint64_t) v50);
  // pto: %ori_kv_flat_inline2344__ssa_v1_view
  int64_t v53 = v52 * v40;
  // pto: %ori_kv_flat_inline2344__ssa_v1_view
  int64_t v54 = v41 * v53;
  // pto: %ori_kv_flat_inline2344__ssa_v1_view
  pto::Shape<1, 1, 1, -1, -1> v55 = pto::Shape<1, 1, 1, -1, -1>(v41, v41, v41, v52, v40);
  // pto: %ori_kv_flat_inline2344__ssa_v1_view
  pto::Stride<-1, -1, -1, -1, -1> v56 = pto::Stride<-1, -1, -1, -1, -1>(v41 * v54, v54, v53, v40, v41);
  // pto: %ori_kv_flat_inline2344__ssa_v1_view
  GlobalTensor<bfloat16_t, pto::Shape<1, 1, 1, -1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND> v57 = GlobalTensor<bfloat16_t, pto::Shape<1, 1, 1, -1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND>(v9, v55, v56);
  // pto: %qk_kv_inline2415__phi_v13
  Tile<TileType::Mat, bfloat16_t, 128, 512, BLayout::ColMajor, -1, -1, SLayout::RowMajor, 512, PadValue::Null, CompactMode::Null> v58 = Tile<TileType::Mat, bfloat16_t, 128, 512, BLayout::ColMajor, -1, -1, SLayout::RowMajor, 512, PadValue::Null, CompactMode::Null>(v38, v40);
  // pto: %qk_kv_inline2415__phi_v13
  uint64_t v59 = (uint64_t) v45;
  TASSIGN(v58, v59);
  // pto: %qk_kv_inline2415__phi_v2
  Tile<TileType::Mat, bfloat16_t, 128, 512, BLayout::ColMajor, -1, -1, SLayout::RowMajor, 512, PadValue::Null, CompactMode::Null> v60 = Tile<TileType::Mat, bfloat16_t, 128, 512, BLayout::ColMajor, -1, -1, SLayout::RowMajor, 512, PadValue::Null, CompactMode::Null>(v38, v40);
  // pto: %qk_kv_inline2415__phi_v2
  uint64_t v61 = (uint64_t) v45;
  TASSIGN(v60, v61);
  // pto: %qk_kv_inline2415__phi_v4
  Tile<TileType::Mat, bfloat16_t, 128, 512, BLayout::ColMajor, -1, -1, SLayout::RowMajor, 512, PadValue::Null, CompactMode::Null> v62 = Tile<TileType::Mat, bfloat16_t, 128, 512, BLayout::ColMajor, -1, -1, SLayout::RowMajor, 512, PadValue::Null, CompactMode::Null>(v38, v40);
  // pto: %qk_kv_inline2415__phi_v4
  uint64_t v63 = (uint64_t) v45;
  TASSIGN(v62, v63);
  // pto: %qk_kv_inline2415__phi_v6
  Tile<TileType::Mat, bfloat16_t, 128, 512, BLayout::ColMajor, -1, -1, SLayout::RowMajor, 512, PadValue::Null, CompactMode::Null> v64 = Tile<TileType::Mat, bfloat16_t, 128, 512, BLayout::ColMajor, -1, -1, SLayout::RowMajor, 512, PadValue::Null, CompactMode::Null>(v38, v40);
  // pto: %qk_kv_inline2415__phi_v6
  uint64_t v65 = (uint64_t) v45;
  TASSIGN(v64, v65);
  // pto: %qk_kv_inline2415__phi_v8
  Tile<TileType::Mat, bfloat16_t, 128, 512, BLayout::ColMajor, -1, -1, SLayout::RowMajor, 512, PadValue::Null, CompactMode::Null> v66 = Tile<TileType::Mat, bfloat16_t, 128, 512, BLayout::ColMajor, -1, -1, SLayout::RowMajor, 512, PadValue::Null, CompactMode::Null>(v38, v40);
  // pto: %qk_kv_inline2415__phi_v8
  uint64_t v67 = (uint64_t) v45;
  TASSIGN(v66, v67);
  // pto: %qk_kv_inline2415__phi_v10
  Tile<TileType::Mat, bfloat16_t, 128, 512, BLayout::ColMajor, -1, -1, SLayout::RowMajor, 512, PadValue::Null, CompactMode::Null> v68 = Tile<TileType::Mat, bfloat16_t, 128, 512, BLayout::ColMajor, -1, -1, SLayout::RowMajor, 512, PadValue::Null, CompactMode::Null>(v38, v40);
  // pto: %qk_kv_inline2415__phi_v10
  uint64_t v69 = (uint64_t) v45;
  TASSIGN(v68, v69);
  // pto: %qk_kv_inline2415__phi_v12
  Tile<TileType::Mat, bfloat16_t, 128, 512, BLayout::ColMajor, -1, -1, SLayout::RowMajor, 512, PadValue::Null, CompactMode::Null> v70 = Tile<TileType::Mat, bfloat16_t, 128, 512, BLayout::ColMajor, -1, -1, SLayout::RowMajor, 512, PadValue::Null, CompactMode::Null>(v38, v40);
  // pto: %qk_kv_inline2415__phi_v12
  uint64_t v71 = (uint64_t) v45;
  TASSIGN(v70, v71);
  // pto: %qk_kv_inline2415__phi_v20
  Tile<TileType::Mat, bfloat16_t, 128, 512, BLayout::ColMajor, -1, -1, SLayout::RowMajor, 512, PadValue::Null, CompactMode::Null> v72 = Tile<TileType::Mat, bfloat16_t, 128, 512, BLayout::ColMajor, -1, -1, SLayout::RowMajor, 512, PadValue::Null, CompactMode::Null>(v38, v40);
  // pto: %qk_kv_inline2415__phi_v20
  uint64_t v73 = (uint64_t) v45;
  TASSIGN(v72, v73);
  // pto: %qk_kv_inline2415__phi_v18
  Tile<TileType::Mat, bfloat16_t, 128, 512, BLayout::ColMajor, -1, -1, SLayout::RowMajor, 512, PadValue::Null, CompactMode::Null> v74 = Tile<TileType::Mat, bfloat16_t, 128, 512, BLayout::ColMajor, -1, -1, SLayout::RowMajor, 512, PadValue::Null, CompactMode::Null>(v38, v40);
  // pto: %qk_kv_inline2415__phi_v18
  uint64_t v75 = (uint64_t) v45;
  TASSIGN(v74, v75);
  auto v76 = TPipe<0, Direction::DIR_BOTH, 16384, 2, 2, true>(v14, v49, v49);
  // pto: %qk_core_inline2368__ssa_v0
  int64_t v77 = (int64_t) v24;
  // pto: %34, %35, %36
  set_flag(PIPE_MTE1, PIPE_MTE2, EVENT_ID0);
  set_flag(PIPE_FIX, PIPE_M, EVENT_ID0);
  set_flag(PIPE_M, PIPE_MTE1, EVENT_ID0);
  for (int64_t i78 = v43; i78 < ((int64_t) ((uint64_t) ((int64_t) ((uint64_t) v15 - (uint64_t) v77)) + (uint64_t) v37) / v36); i78 += v41) {
    // pto: %38, %37, %39
    int32_t v79 = (v4)[(int64_t) ((uint64_t) v77 + (uint64_t) ((int64_t) ((uint64_t) i78 * (uint64_t) v36)))];
    // pto: %40
    int64_t v80 = (int64_t) v79;
    // pto: %41
    int64_t v81 = v80 / v39;
    // pto: %43, %42
    int64_t v82 = (int64_t) ((uint64_t) v80 - (uint64_t) ((int64_t) ((uint64_t) v81 * (uint64_t) v39)));
    // pto: %45
    int64_t v83 = (int64_t) ((uint64_t) v81 * (uint64_t) v34);
    // pto: %46
    int64_t v84 = (int64_t) ((uint64_t) v82 * (uint64_t) v38);
    // pto: %qk_block_valid_inline2422__tile
    int32_t v85 = (v6)[v80];
    // pto: %47, %48
    if ((int64_t) v85 > v43) {
      // pto: %qk_kv_inline2415__tile
      Tile<TileType::Mat, bfloat16_t, 128, 512, BLayout::ColMajor, -1, -1, SLayout::RowMajor, 512, PadValue::Null, CompactMode::Null> v86 = Tile<TileType::Mat, bfloat16_t, 128, 512, BLayout::ColMajor, -1, -1, SLayout::RowMajor, 512, PadValue::Null, CompactMode::Null>(v38, v40);
      // pto: %qk_kv_inline2415__tile
      uint64_t v87 = (uint64_t) v45;
      TASSIGN(v86, v87);
      // pto: %49
      int64_t v88 = (int64_t) ((uint64_t) v38 - (uint64_t) v84);
      // pto: %50
      int64_t v89 = v88 < v43 ? v43 : v88;
      // pto: %51
      int64_t v90 = v89 < v38 ? v89 : v38;
      // pto: %52
      wait_flag(PIPE_MTE1, PIPE_MTE2, EVENT_ID0);
      if (v90 > v43) {
        // pto: %53
        int32_t v91 = (v7)[v81];
        // pto: %56
        int64_t v92 = (int64_t) v91;
        // pto: %57
        int64_t v93 = (int64_t) ((uint64_t) v92 + (uint64_t) v41);
        // pto: %58
        int64_t v94 = v93 < v38 ? v93 : v38;
        // pto: %61
        int64_t v95 = (int64_t) ((uint64_t) v94 - (uint64_t) v84);
        // pto: %62
        int64_t v96 = v95 < v43 ? v43 : v95;
        // pto: %63
        int64_t v97 = v96 < v90 ? v96 : v90;
        // pto: %59, %60, %64, %65
        int64_t v98 = (int64_t) ((uint64_t) ((int64_t) ((uint64_t) ((int64_t) ((uint64_t) v92 - (uint64_t) v94)) + (uint64_t) v41)) + (uint64_t) v84) % v50;
        // pto: %66
        int64_t v99 = (int64_t) ((uint64_t) v50 - (uint64_t) v98);
        // pto: %67
        int64_t v100 = v99 < v97 ? v99 : v97;
        // pto: %68
        if (v100 > v43) {
          // pto: %70, %71, %qk_run_raw_inline2357__tile
          int32_t v101 = (v8)[(int64_t) ((uint64_t) ((int64_t) ((uint64_t) v81 * (uint64_t) v38)) + (uint64_t) v84)];
          // pto: %72
          int64_t v102 = (int64_t) v101;
          // pto: %73
          int64_t v103 = v102 < v43 ? v43 : v102;
          // pto: %gather_row_view
          Tile<TileType::Mat, bfloat16_t, 128, 512, BLayout::ColMajor, -1, 512, SLayout::RowMajor, 512, PadValue::Null, CompactMode::Null> v104 = Tile<TileType::Mat, bfloat16_t, 128, 512, BLayout::ColMajor, -1, 512, SLayout::RowMajor, 512, PadValue::Null, CompactMode::Null>(v100);
          // pto: %gather_row_view
          uint64_t v105 = (uint64_t) v45;
          TASSIGN(v104, v105);
          // pto: %ori_kv_flat_inline2344__ssa_v1_pview
          __gm__ bfloat16_t* v106 = PTOAS__GLOBAL_TENSOR_DATA(v57);
          // pto: %ori_kv_flat_inline2344__ssa_v1_pview
          int64_t v107 = v100 * v40;
          // pto: %ori_kv_flat_inline2344__ssa_v1_pview
          int64_t v108 = v41 * v107;
          // pto: %ori_kv_flat_inline2344__ssa_v1_pview
          pto::Shape<1, 1, 1, -1, 512> v109 = pto::Shape<1, 1, 1, -1, 512>(v41, v41, v41, v100, v40);
          // pto: %ori_kv_flat_inline2344__ssa_v1_pview
          pto::Stride<-1, -1, -1, -1, -1> v110 = pto::Stride<-1, -1, -1, -1, -1>(v41 * v108, v108, v107, v40, v41);
          // pto: %76, %ori_kv_flat_inline2344__ssa_v1_pview
          GlobalTensor<bfloat16_t, pto::Shape<1, 1, 1, -1, 512>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND> v111 = GlobalTensor<bfloat16_t, pto::Shape<1, 1, 1, -1, 512>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND>(v106 + ((v43 + (v103 < v43 ? v43 : v103) * v40) + v43 * v41), v109, v110);
          TLOAD(v104, v111);
        }
        // pto: %78
        int64_t v112 = (int64_t) ((uint64_t) v33 - (uint64_t) v98);
        // pto: %79
        int64_t v113 = v112 < v97 ? v112 : v97;
        // pto: %80
        if (v99 < v113) {
          // pto: %83, %84, %82, %81
          int32_t v114 = (v8)[(int64_t) ((uint64_t) ((int64_t) ((uint64_t) v81 * (uint64_t) v38)) + (uint64_t) ((int64_t) ((uint64_t) v84 + (uint64_t) v99)))];
          // pto: %85
          int64_t v115 = (int64_t) v114;
          // pto: %86
          int64_t v116 = v115 < v43 ? v43 : v115;
          // pto: %88
          int64_t v117 = (int64_t) ((uint64_t) v113 - (uint64_t) v99);
          // pto: %89
          Tile<TileType::Mat, bfloat16_t, 128, 512, BLayout::ColMajor, -1, 512, SLayout::RowMajor, 512, PadValue::Null, CompactMode::Null> v118 = Tile<TileType::Mat, bfloat16_t, 128, 512, BLayout::ColMajor, -1, 512, SLayout::RowMajor, 512, PadValue::Null, CompactMode::Null>(v117);
          // pto: %89
          uint64_t v119 = (uint64_t) ((int64_t) ((uint64_t) ((int64_t) ((uint64_t) v99 * (uint64_t) v50)) + (uint64_t) v45));
          TASSIGN(v118, v119);
          // pto: %91
          __gm__ bfloat16_t* v120 = PTOAS__GLOBAL_TENSOR_DATA(v57);
          // pto: %91
          int64_t v121 = v117 * v40;
          // pto: %91
          int64_t v122 = v41 * v121;
          // pto: %91
          pto::Shape<1, 1, 1, -1, 512> v123 = pto::Shape<1, 1, 1, -1, 512>(v41, v41, v41, v117, v40);
          // pto: %91
          pto::Stride<-1, -1, -1, -1, -1> v124 = pto::Stride<-1, -1, -1, -1, -1>(v41 * v122, v122, v121, v40, v41);
          // pto: %90, %91
          GlobalTensor<bfloat16_t, pto::Shape<1, 1, 1, -1, 512>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND> v125 = GlobalTensor<bfloat16_t, pto::Shape<1, 1, 1, -1, 512>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND>(v120 + ((v43 + (v116 < v43 ? v43 : v116) * v40) + v43 * v41), v123, v124);
          TLOAD(v118, v125);
        }
        // pto: %93
        int64_t v126 = (int64_t) ((uint64_t) v32 - (uint64_t) v98);
        // pto: %94
        int64_t v127 = v126 < v97 ? v126 : v97;
        // pto: %95
        if (v112 < v127) {
          // pto: %98, %99, %97, %96
          int32_t v128 = (v8)[(int64_t) ((uint64_t) ((int64_t) ((uint64_t) v81 * (uint64_t) v38)) + (uint64_t) ((int64_t) ((uint64_t) v84 + (uint64_t) v112)))];
          // pto: %100
          int64_t v129 = (int64_t) v128;
          // pto: %101
          int64_t v130 = v129 < v43 ? v43 : v129;
          // pto: %103
          int64_t v131 = (int64_t) ((uint64_t) v127 - (uint64_t) v112);
          // pto: %104
          Tile<TileType::Mat, bfloat16_t, 128, 512, BLayout::ColMajor, -1, 512, SLayout::RowMajor, 512, PadValue::Null, CompactMode::Null> v132 = Tile<TileType::Mat, bfloat16_t, 128, 512, BLayout::ColMajor, -1, 512, SLayout::RowMajor, 512, PadValue::Null, CompactMode::Null>(v131);
          // pto: %104
          uint64_t v133 = (uint64_t) ((int64_t) ((uint64_t) ((int64_t) ((uint64_t) v112 * (uint64_t) v50)) + (uint64_t) v45));
          TASSIGN(v132, v133);
          // pto: %106
          __gm__ bfloat16_t* v134 = PTOAS__GLOBAL_TENSOR_DATA(v57);
          // pto: %106
          int64_t v135 = v131 * v40;
          // pto: %106
          int64_t v136 = v41 * v135;
          // pto: %106
          pto::Shape<1, 1, 1, -1, 512> v137 = pto::Shape<1, 1, 1, -1, 512>(v41, v41, v41, v131, v40);
          // pto: %106
          pto::Stride<-1, -1, -1, -1, -1> v138 = pto::Stride<-1, -1, -1, -1, -1>(v41 * v136, v136, v135, v40, v41);
          // pto: %105, %106
          GlobalTensor<bfloat16_t, pto::Shape<1, 1, 1, -1, 512>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND> v139 = GlobalTensor<bfloat16_t, pto::Shape<1, 1, 1, -1, 512>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND>(v134 + ((v43 + (v130 < v43 ? v43 : v130) * v40) + v43 * v41), v137, v138);
          TLOAD(v132, v139);
        }
        // pto: %108
        int64_t v140 = (int64_t) ((uint64_t) v38 - (uint64_t) v98);
        // pto: %109
        int64_t v141 = v140 < v97 ? v140 : v97;
        // pto: %110
        if (v126 < v141) {
          // pto: %113, %114, %112, %111
          int32_t v142 = (v8)[(int64_t) ((uint64_t) ((int64_t) ((uint64_t) v81 * (uint64_t) v38)) + (uint64_t) ((int64_t) ((uint64_t) v84 + (uint64_t) v126)))];
          // pto: %115
          int64_t v143 = (int64_t) v142;
          // pto: %116
          int64_t v144 = v143 < v43 ? v43 : v143;
          // pto: %118
          int64_t v145 = (int64_t) ((uint64_t) v141 - (uint64_t) v126);
          // pto: %119
          Tile<TileType::Mat, bfloat16_t, 128, 512, BLayout::ColMajor, -1, 512, SLayout::RowMajor, 512, PadValue::Null, CompactMode::Null> v146 = Tile<TileType::Mat, bfloat16_t, 128, 512, BLayout::ColMajor, -1, 512, SLayout::RowMajor, 512, PadValue::Null, CompactMode::Null>(v145);
          // pto: %119
          uint64_t v147 = (uint64_t) ((int64_t) ((uint64_t) ((int64_t) ((uint64_t) v126 * (uint64_t) v50)) + (uint64_t) v45));
          TASSIGN(v146, v147);
          // pto: %121
          __gm__ bfloat16_t* v148 = PTOAS__GLOBAL_TENSOR_DATA(v57);
          // pto: %121
          int64_t v149 = v145 * v40;
          // pto: %121
          int64_t v150 = v41 * v149;
          // pto: %121
          pto::Shape<1, 1, 1, -1, 512> v151 = pto::Shape<1, 1, 1, -1, 512>(v41, v41, v41, v145, v40);
          // pto: %121
          pto::Stride<-1, -1, -1, -1, -1> v152 = pto::Stride<-1, -1, -1, -1, -1>(v41 * v150, v150, v149, v40, v41);
          // pto: %120, %121
          GlobalTensor<bfloat16_t, pto::Shape<1, 1, 1, -1, 512>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND> v153 = GlobalTensor<bfloat16_t, pto::Shape<1, 1, 1, -1, 512>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND>(v148 + ((v43 + (v144 < v43 ? v43 : v144) * v40) + v43 * v41), v151, v152);
          TLOAD(v146, v153);
        }
        // pto: %123
        if (v140 < v97) {
          // pto: %126, %127, %125, %124
          int32_t v154 = (v8)[(int64_t) ((uint64_t) ((int64_t) ((uint64_t) v81 * (uint64_t) v38)) + (uint64_t) ((int64_t) ((uint64_t) v84 + (uint64_t) v140)))];
          // pto: %128
          int64_t v155 = (int64_t) v154;
          // pto: %129
          int64_t v156 = v155 < v43 ? v43 : v155;
          // pto: %131
          int64_t v157 = (int64_t) ((uint64_t) v97 - (uint64_t) v140);
          // pto: %132
          Tile<TileType::Mat, bfloat16_t, 128, 512, BLayout::ColMajor, -1, 512, SLayout::RowMajor, 512, PadValue::Null, CompactMode::Null> v158 = Tile<TileType::Mat, bfloat16_t, 128, 512, BLayout::ColMajor, -1, 512, SLayout::RowMajor, 512, PadValue::Null, CompactMode::Null>(v157);
          // pto: %132
          uint64_t v159 = (uint64_t) ((int64_t) ((uint64_t) ((int64_t) ((uint64_t) v140 * (uint64_t) v50)) + (uint64_t) v45));
          TASSIGN(v158, v159);
          // pto: %134
          __gm__ bfloat16_t* v160 = PTOAS__GLOBAL_TENSOR_DATA(v57);
          // pto: %134
          int64_t v161 = v157 * v40;
          // pto: %134
          int64_t v162 = v41 * v161;
          // pto: %134
          pto::Shape<1, 1, 1, -1, 512> v163 = pto::Shape<1, 1, 1, -1, 512>(v41, v41, v41, v157, v40);
          // pto: %134
          pto::Stride<-1, -1, -1, -1, -1> v164 = pto::Stride<-1, -1, -1, -1, -1>(v41 * v162, v162, v161, v40, v41);
          // pto: %133, %134
          GlobalTensor<bfloat16_t, pto::Shape<1, 1, 1, -1, 512>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND> v165 = GlobalTensor<bfloat16_t, pto::Shape<1, 1, 1, -1, 512>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND>(v160 + ((v43 + (v156 < v43 ? v43 : v156) * v40) + v43 * v41), v163, v164);
          TLOAD(v158, v165);
        }
        // pto: %135
        int64_t v166 = (int64_t) ((uint64_t) v90 - (uint64_t) v97);
        // pto: %136
        if (v166 > v43) {
          // pto: %137
          Tile<TileType::Mat, bfloat16_t, 128, 512, BLayout::ColMajor, -1, 512, SLayout::RowMajor, 512, PadValue::Null, CompactMode::Null> v167 = Tile<TileType::Mat, bfloat16_t, 128, 512, BLayout::ColMajor, -1, 512, SLayout::RowMajor, 512, PadValue::Null, CompactMode::Null>(v166);
          // pto: %137
          uint64_t v168 = (uint64_t) ((int64_t) ((uint64_t) ((int64_t) ((uint64_t) v97 * (uint64_t) v50)) + (uint64_t) v45));
          TASSIGN(v167, v168);
          // pto: %138
          __gm__ bfloat16_t* v169 = PTOAS__GLOBAL_TENSOR_DATA(v57);
          // pto: %138
          int64_t v170 = v166 * v40;
          // pto: %138
          int64_t v171 = v41 * v170;
          // pto: %138
          pto::Shape<1, 1, 1, -1, 512> v172 = pto::Shape<1, 1, 1, -1, 512>(v41, v41, v41, v166, v40);
          // pto: %138
          pto::Stride<-1, -1, -1, -1, -1> v173 = pto::Stride<-1, -1, -1, -1, -1>(v41 * v171, v171, v170, v40, v41);
          // pto: %138
          GlobalTensor<bfloat16_t, pto::Shape<1, 1, 1, -1, 512>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND> v174 = GlobalTensor<bfloat16_t, pto::Shape<1, 1, 1, -1, 512>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::ND>(v169 + ((v43 + v43 * v40) + v43 * v41), v172, v173);
          TLOAD(v167, v174);
        }
      }
      for (int64_t j175 = v90; j175 < v38; j175 += v41) {
        // pto: %139, %140
        int64_t v176 = (int64_t) ((uint64_t) ((int64_t) ((uint64_t) v84 + (uint64_t) j175)) - (uint64_t) v38);
        // pto: %141
        if (v176 < v40) {
          // pto: %142, %143, %qk_ridx_inline2377__tile
          int32_t v177 = (v10)[(int64_t) ((uint64_t) ((int64_t) ((uint64_t) v81 * (uint64_t) v40)) + (uint64_t) v176)];
          // pto: %144
          int64_t v178 = (int64_t) v177;
          // pto: %145
          if (v178 >= v43) {
            // pto: %44, %149, %150, %148, %146
            int32_t v179 = (v11)[(int64_t) ((uint64_t) ((int64_t) ((uint64_t) (v81 / v35) * (uint64_t) v42)) + (uint64_t) (v178 / v50))];
            // pto: %151, %152, %155, %154
            int64_t v180 = (int64_t) ((uint64_t) ((int64_t) ((uint64_t) ((int64_t) v179) * (uint64_t) v50)) + (uint64_t) (v178 % v50));
            // pto: %156
            Tile<TileType::Mat, bfloat16_t, 128, 512, BLayout::ColMajor, 1, 512, SLayout::RowMajor, 512, PadValue::Null, CompactMode::Null> v181;
            // pto: %156
            Tile<TileType::Mat, bfloat16_t, 128, 512, BLayout::ColMajor, 1, 512, SLayout::RowMajor, 512, PadValue::Null, CompactMode::Null> v182 = v181;
            // pto: %156
            uint64_t v183 = (uint64_t) ((int64_t) ((uint64_t) ((int64_t) ((uint64_t) j175 * (uint64_t) v50)) + (uint64_t) v45));
            TASSIGN(v182, v183);
            // pto: %cmp_kv_flat_inline2401__ssa_v0_pview
            pto::Shape<1, 1, 1, 1, 512> v184 = pto::Shape<1, 1, 1, 1, 512>();
            // pto: %cmp_kv_flat_inline2401__ssa_v0_pview
            pto::Stride<512, 512, 512, 512, 1> v185 = pto::Stride<512, 512, 512, 512, 1>();
            // pto: %157, %cmp_kv_flat_inline2401__ssa_v0_pview
            GlobalTensor<bfloat16_t, pto::Shape<1, 1, 1, 1, 512>, pto::Stride<512, 512, 512, 512, 1>, pto::Layout::ND> v186 = GlobalTensor<bfloat16_t, pto::Shape<1, 1, 1, 1, 512>, pto::Stride<512, 512, 512, 512, 1>, pto::Layout::ND>(v12 + (v43 + (v180 < v43 ? v43 : v180) * v40), v184, v185);
            TLOAD(v182, v186);
          } else {
            // pto: %158
            Tile<TileType::Mat, bfloat16_t, 128, 512, BLayout::ColMajor, 1, 512, SLayout::RowMajor, 512, PadValue::Null, CompactMode::Null> v187;
            // pto: %158
            Tile<TileType::Mat, bfloat16_t, 128, 512, BLayout::ColMajor, 1, 512, SLayout::RowMajor, 512, PadValue::Null, CompactMode::Null> v188 = v187;
            // pto: %158
            uint64_t v189 = (uint64_t) ((int64_t) ((uint64_t) ((int64_t) ((uint64_t) j175 * (uint64_t) v50)) + (uint64_t) v45));
            TASSIGN(v188, v189);
            // pto: %159
            pto::Shape<1, 1, 1, 1, 512> v190 = pto::Shape<1, 1, 1, 1, 512>();
            // pto: %159
            pto::Stride<512, 512, 512, 512, 1> v191 = pto::Stride<512, 512, 512, 512, 1>();
            // pto: %159
            GlobalTensor<bfloat16_t, pto::Shape<1, 1, 1, 1, 512>, pto::Stride<512, 512, 512, 512, 1>, pto::Layout::ND> v192 = GlobalTensor<bfloat16_t, pto::Shape<1, 1, 1, 1, 512>, pto::Stride<512, 512, 512, 512, 1>, pto::Layout::ND>(v9, v190, v191);
            TLOAD(v188, v192);
          }
        } else {
          // pto: %160
          Tile<TileType::Mat, bfloat16_t, 128, 512, BLayout::ColMajor, 1, 512, SLayout::RowMajor, 512, PadValue::Null, CompactMode::Null> v193;
          // pto: %160
          Tile<TileType::Mat, bfloat16_t, 128, 512, BLayout::ColMajor, 1, 512, SLayout::RowMajor, 512, PadValue::Null, CompactMode::Null> v194 = v193;
          // pto: %160
          uint64_t v195 = (uint64_t) ((int64_t) ((uint64_t) ((int64_t) ((uint64_t) j175 * (uint64_t) v50)) + (uint64_t) v45));
          TASSIGN(v194, v195);
          // pto: %161
          pto::Shape<1, 1, 1, 1, 512> v196 = pto::Shape<1, 1, 1, 1, 512>();
          // pto: %161
          pto::Stride<512, 512, 512, 512, 1> v197 = pto::Stride<512, 512, 512, 512, 1>();
          // pto: %161
          GlobalTensor<bfloat16_t, pto::Shape<1, 1, 1, 1, 512>, pto::Stride<512, 512, 512, 512, 1>, pto::Layout::ND> v198 = GlobalTensor<bfloat16_t, pto::Shape<1, 1, 1, 1, 512>, pto::Stride<512, 512, 512, 512, 1>, pto::Layout::ND>(v9, v196, v197);
          TLOAD(v194, v198);
        }
      }
      // pto: %162
      int64_t v199 = (int64_t) ((uint64_t) v81 * (uint64_t) v33);
      // pto: %qk_q_tile_inline2338__tile
      Tile<TileType::Mat, bfloat16_t, 32, 512, BLayout::ColMajor, -1, -1, SLayout::RowMajor, 512, PadValue::Null, CompactMode::Null> v200 = Tile<TileType::Mat, bfloat16_t, 32, 512, BLayout::ColMajor, -1, -1, SLayout::RowMajor, 512, PadValue::Null, CompactMode::Null>(v50, v40);
      // pto: %qk_q_tile_inline2338__tile
      uint64_t v201 = (uint64_t) v44;
      TASSIGN(v200, v201);
      // pto: %q_flat_inline2355__ssa_v0_pview
      pto::Shape<1, 1, 1, 32, 512> v202 = pto::Shape<1, 1, 1, 32, 512>();
      // pto: %q_flat_inline2355__ssa_v0_pview
      pto::Stride<16384, 16384, 16384, 512, 1> v203 = pto::Stride<16384, 16384, 16384, 512, 1>();
      // pto: %164, %q_flat_inline2355__ssa_v0_pview
      GlobalTensor<bfloat16_t, pto::Shape<1, 1, 1, 32, 512>, pto::Stride<16384, 16384, 16384, 512, 1>, pto::Layout::ND> v204 = GlobalTensor<bfloat16_t, pto::Shape<1, 1, 1, 32, 512>, pto::Stride<16384, 16384, 16384, 512, 1>, pto::Layout::ND>(v13 + (v43 + (v199 < v43 ? v43 : v199) * v40), v202, v203);
      TLOAD(v200, v204);
      set_flag(PIPE_MTE2, PIPE_MTE1, EVENT_ID0);
      // pto: %qk_kv_inline2415__rv_v15_t
      Tile<TileType::Mat, bfloat16_t, 512, 128, BLayout::RowMajor, -1, -1, SLayout::ColMajor, 512, PadValue::Null, CompactMode::Null> v205 = Tile<TileType::Mat, bfloat16_t, 512, 128, BLayout::RowMajor, -1, -1, SLayout::ColMajor, 512, PadValue::Null, CompactMode::Null>(v40, v38);
      // pto: %qk_kv_inline2415__rv_v15_t
      uint64_t v206 = (uint64_t) v45;
      TASSIGN(v205, v206);
      // pto: %qk_raw_inline2397__tile_l0_init
      Tile<TileType::Acc, float, 32, 128, BLayout::ColMajor, -1, -1, SLayout::RowMajor, 1024, PadValue::Null, CompactMode::Null> v207 = Tile<TileType::Acc, float, 32, 128, BLayout::ColMajor, -1, -1, SLayout::RowMajor, 1024, PadValue::Null, CompactMode::Null>(v50, v38);
      // pto: %qk_raw_inline2397__tile_l0_init
      uint64_t v208 = (uint64_t) v43;
      TASSIGN(v207, v208);
      wait_flag(PIPE_MTE2, PIPE_MTE1, EVENT_ID0);
      wait_flag(PIPE_M, PIPE_MTE1, EVENT_ID0);
      wait_flag(PIPE_FIX, PIPE_M, EVENT_ID0);
      set_flag(PIPE_M, PIPE_MTE1, EVENT_ID1);
      set_flag(PIPE_M, PIPE_MTE1, EVENT_ID2);
      for (int64_t j209 = v43; j209 < v40; j209 += v31) {
        // pto: %qk_raw_inline2397__tile_l0_a
        Tile<TileType::Left, bfloat16_t, 32, 128, BLayout::RowMajor, -1, -1, SLayout::RowMajor, 512, PadValue::Null, CompactMode::Null> v210 = Tile<TileType::Left, bfloat16_t, 32, 128, BLayout::RowMajor, -1, -1, SLayout::RowMajor, 512, PadValue::Null, CompactMode::Null>(v50, v38);
        // pto: %qk_raw_inline2397__tile_l0_a
        uint64_t v211 = (uint64_t) v43;
        TASSIGN(v210, v211);
        wait_flag(PIPE_M, PIPE_MTE1, EVENT_ID1);
        pipe_barrier(PIPE_MTE1);
        TEXTRACT(v210, v200, v43, j209);
        // pto: %qk_raw_inline2397__tile_l0_b
        Tile<TileType::Right, bfloat16_t, 128, 128, BLayout::RowMajor, -1, -1, SLayout::ColMajor, 512, PadValue::Null, CompactMode::Null> v212 = Tile<TileType::Right, bfloat16_t, 128, 128, BLayout::RowMajor, -1, -1, SLayout::ColMajor, 512, PadValue::Null, CompactMode::Null>(v38, v38);
        // pto: %qk_raw_inline2397__tile_l0_b
        uint64_t v213 = (uint64_t) v43;
        TASSIGN(v212, v213);
        TEXTRACT(v212, v205, j209, v43);
        set_flag(PIPE_MTE1, PIPE_M, EVENT_ID0);
        // pto: %9
        Tile<TileType::Left, bfloat16_t, 32, 128, BLayout::RowMajor, -1, -1, SLayout::RowMajor, 512, PadValue::Null, CompactMode::Null> v214 = Tile<TileType::Left, bfloat16_t, 32, 128, BLayout::RowMajor, -1, -1, SLayout::RowMajor, 512, PadValue::Null, CompactMode::Null>(v50, v38);
        // pto: %9
        uint64_t v215 = (uint64_t) v42;
        TASSIGN(v214, v215);
        // pto: %165
        int64_t v216 = (int64_t) ((uint64_t) j209 + (uint64_t) v38);
        wait_flag(PIPE_M, PIPE_MTE1, EVENT_ID2);
        TEXTRACT(v214, v200, v43, v216);
        // pto: %10
        Tile<TileType::Right, bfloat16_t, 128, 128, BLayout::RowMajor, -1, -1, SLayout::ColMajor, 512, PadValue::Null, CompactMode::Null> v217 = Tile<TileType::Right, bfloat16_t, 128, 128, BLayout::RowMajor, -1, -1, SLayout::ColMajor, 512, PadValue::Null, CompactMode::Null>(v38, v38);
        // pto: %10
        uint64_t v218 = (uint64_t) v45;
        TASSIGN(v217, v218);
        TEXTRACT(v217, v205, v216, v43);
        set_flag(PIPE_MTE1, PIPE_M, EVENT_ID1);
        // pto: %167
        wait_flag(PIPE_MTE1, PIPE_M, EVENT_ID0);
        if (j209 == v43) {
          pipe_barrier(PIPE_M);
          TMATMUL(v207, v210, v212);
        } else {
          pipe_barrier(PIPE_M);
          TMATMUL_ACC(v207, v207, v210, v212);
        }
        set_flag(PIPE_M, PIPE_MTE1, EVENT_ID1);
        // pto: %168
        wait_flag(PIPE_MTE1, PIPE_M, EVENT_ID1);
        if (j209 == v30) {
          pipe_barrier(PIPE_M);
          TMATMUL(v207, v214, v217);
        } else {
          pipe_barrier(PIPE_M);
          TMATMUL_ACC(v207, v207, v214, v217);
        }
        set_flag(PIPE_M, PIPE_MTE1, EVENT_ID2);
      }
      wait_flag(PIPE_M, PIPE_MTE1, EVENT_ID2);
      wait_flag(PIPE_M, PIPE_MTE1, EVENT_ID1);
      set_flag(PIPE_MTE1, PIPE_MTE2, EVENT_ID1);
      set_flag(PIPE_M, PIPE_MTE1, EVENT_ID3);
      set_flag(PIPE_M, PIPE_FIX, EVENT_ID0);
      wait_flag(PIPE_M, PIPE_FIX, EVENT_ID0);
      TPUSH<TPipe<0, Direction::DIR_BOTH, 16384, 2, 2, true>, Tile<TileType::Acc, float, 32, 128, BLayout::ColMajor, -1, -1, SLayout::RowMajor, 1024, PadValue::Null, CompactMode::Null>, TileSplitAxis::TILE_NO_SPLIT>(v76, v207);
      set_flag(PIPE_FIX, PIPE_M, EVENT_ID1);
      // pto: %170
      int64_t v219 = (int64_t) ((uint64_t) v199 + (uint64_t) v50);
      // pto: %12
      Tile<TileType::Mat, bfloat16_t, 32, 512, BLayout::ColMajor, -1, -1, SLayout::RowMajor, 512, PadValue::Null, CompactMode::Null> v220 = Tile<TileType::Mat, bfloat16_t, 32, 512, BLayout::ColMajor, -1, -1, SLayout::RowMajor, 512, PadValue::Null, CompactMode::Null>(v50, v40);
      // pto: %12
      uint64_t v221 = (uint64_t) v44;
      TASSIGN(v220, v221);
      // pto: %172
      pto::Shape<1, 1, 1, 32, 512> v222 = pto::Shape<1, 1, 1, 32, 512>();
      // pto: %172
      pto::Stride<16384, 16384, 16384, 512, 1> v223 = pto::Stride<16384, 16384, 16384, 512, 1>();
      // pto: %171, %172
      GlobalTensor<bfloat16_t, pto::Shape<1, 1, 1, 32, 512>, pto::Stride<16384, 16384, 16384, 512, 1>, pto::Layout::ND> v224 = GlobalTensor<bfloat16_t, pto::Shape<1, 1, 1, 32, 512>, pto::Stride<16384, 16384, 16384, 512, 1>, pto::Layout::ND>(v13 + (v43 + (v219 < v43 ? v43 : v219) * v40), v222, v223);
      wait_flag(PIPE_MTE1, PIPE_MTE2, EVENT_ID1);
      TLOAD(v220, v224);
      set_flag(PIPE_MTE2, PIPE_MTE1, EVENT_ID1);
      // pto: %13
      Tile<TileType::Mat, bfloat16_t, 512, 128, BLayout::RowMajor, -1, -1, SLayout::ColMajor, 512, PadValue::Null, CompactMode::Null> v225 = Tile<TileType::Mat, bfloat16_t, 512, 128, BLayout::RowMajor, -1, -1, SLayout::ColMajor, 512, PadValue::Null, CompactMode::Null>(v40, v38);
      // pto: %13
      uint64_t v226 = (uint64_t) v45;
      TASSIGN(v225, v226);
      // pto: %14
      Tile<TileType::Acc, float, 32, 128, BLayout::ColMajor, -1, -1, SLayout::RowMajor, 1024, PadValue::Null, CompactMode::Null> v227 = Tile<TileType::Acc, float, 32, 128, BLayout::ColMajor, -1, -1, SLayout::RowMajor, 1024, PadValue::Null, CompactMode::Null>(v50, v38);
      // pto: %14
      uint64_t v228 = (uint64_t) v43;
      TASSIGN(v227, v228);
      wait_flag(PIPE_MTE2, PIPE_MTE1, EVENT_ID1);
      wait_flag(PIPE_M, PIPE_MTE1, EVENT_ID3);
      wait_flag(PIPE_FIX, PIPE_M, EVENT_ID1);
      set_flag(PIPE_M, PIPE_MTE1, EVENT_ID5);
      set_flag(PIPE_M, PIPE_MTE1, EVENT_ID4);
      for (int64_t j229 = v43; j229 < v40; j229 += v31) {
        // pto: %15
        Tile<TileType::Left, bfloat16_t, 32, 128, BLayout::RowMajor, -1, -1, SLayout::RowMajor, 512, PadValue::Null, CompactMode::Null> v230 = Tile<TileType::Left, bfloat16_t, 32, 128, BLayout::RowMajor, -1, -1, SLayout::RowMajor, 512, PadValue::Null, CompactMode::Null>(v50, v38);
        // pto: %15
        uint64_t v231 = (uint64_t) v43;
        TASSIGN(v230, v231);
        wait_flag(PIPE_M, PIPE_MTE1, EVENT_ID4);
        TEXTRACT(v230, v220, v43, j229);
        // pto: %16
        Tile<TileType::Right, bfloat16_t, 128, 128, BLayout::RowMajor, -1, -1, SLayout::ColMajor, 512, PadValue::Null, CompactMode::Null> v232 = Tile<TileType::Right, bfloat16_t, 128, 128, BLayout::RowMajor, -1, -1, SLayout::ColMajor, 512, PadValue::Null, CompactMode::Null>(v38, v38);
        // pto: %16
        uint64_t v233 = (uint64_t) v43;
        TASSIGN(v232, v233);
        TEXTRACT(v232, v225, j229, v43);
        set_flag(PIPE_MTE1, PIPE_M, EVENT_ID2);
        // pto: %17
        Tile<TileType::Left, bfloat16_t, 32, 128, BLayout::RowMajor, -1, -1, SLayout::RowMajor, 512, PadValue::Null, CompactMode::Null> v234 = Tile<TileType::Left, bfloat16_t, 32, 128, BLayout::RowMajor, -1, -1, SLayout::RowMajor, 512, PadValue::Null, CompactMode::Null>(v50, v38);
        // pto: %17
        uint64_t v235 = (uint64_t) v42;
        TASSIGN(v234, v235);
        // pto: %174
        int64_t v236 = (int64_t) ((uint64_t) j229 + (uint64_t) v38);
        wait_flag(PIPE_M, PIPE_MTE1, EVENT_ID5);
        TEXTRACT(v234, v220, v43, v236);
        // pto: %18
        Tile<TileType::Right, bfloat16_t, 128, 128, BLayout::RowMajor, -1, -1, SLayout::ColMajor, 512, PadValue::Null, CompactMode::Null> v237 = Tile<TileType::Right, bfloat16_t, 128, 128, BLayout::RowMajor, -1, -1, SLayout::ColMajor, 512, PadValue::Null, CompactMode::Null>(v38, v38);
        // pto: %18
        uint64_t v238 = (uint64_t) v45;
        TASSIGN(v237, v238);
        pipe_barrier(PIPE_MTE1);
        TEXTRACT(v237, v225, v236, v43);
        set_flag(PIPE_MTE1, PIPE_M, EVENT_ID3);
        // pto: %176
        wait_flag(PIPE_MTE1, PIPE_M, EVENT_ID2);
        if (j229 == v43) {
          pipe_barrier(PIPE_M);
          TMATMUL(v227, v230, v232);
        } else {
          pipe_barrier(PIPE_M);
          TMATMUL_ACC(v227, v227, v230, v232);
        }
        set_flag(PIPE_M, PIPE_MTE1, EVENT_ID4);
        // pto: %177
        wait_flag(PIPE_MTE1, PIPE_M, EVENT_ID3);
        if (j229 == v30) {
          pipe_barrier(PIPE_M);
          TMATMUL(v227, v234, v237);
        } else {
          pipe_barrier(PIPE_M);
          TMATMUL_ACC(v227, v227, v234, v237);
        }
        set_flag(PIPE_M, PIPE_MTE1, EVENT_ID5);
      }
      wait_flag(PIPE_M, PIPE_MTE1, EVENT_ID4);
      wait_flag(PIPE_M, PIPE_MTE1, EVENT_ID5);
      set_flag(PIPE_M, PIPE_MTE1, EVENT_ID6);
      set_flag(PIPE_M, PIPE_FIX, EVENT_ID1);
      wait_flag(PIPE_M, PIPE_FIX, EVENT_ID1);
      TPUSH<TPipe<0, Direction::DIR_BOTH, 16384, 2, 2, true>, Tile<TileType::Acc, float, 32, 128, BLayout::ColMajor, -1, -1, SLayout::RowMajor, 1024, PadValue::Null, CompactMode::Null>, TileSplitAxis::TILE_NO_SPLIT>(v76, v227);
      set_flag(PIPE_FIX, PIPE_M, EVENT_ID2);
      // pto: %qk_oi_inline2335__tile_l0_init
      Tile<TileType::Acc, float, 32, 512, BLayout::ColMajor, -1, -1, SLayout::RowMajor, 1024, PadValue::Null, CompactMode::Null> v239 = Tile<TileType::Acc, float, 32, 512, BLayout::ColMajor, -1, -1, SLayout::RowMajor, 1024, PadValue::Null, CompactMode::Null>(v50, v40);
      // pto: %qk_oi_inline2335__tile_l0_init
      uint64_t v240 = (uint64_t) v43;
      TASSIGN(v239, v240);
      // pto: %qk_oi_inline2335__tile_l0_lmat
      Tile<TileType::Mat, bfloat16_t, 32, 128, BLayout::ColMajor, -1, -1, SLayout::RowMajor, 512, PadValue::Null, CompactMode::Null> v241 = Tile<TileType::Mat, bfloat16_t, 32, 128, BLayout::ColMajor, -1, -1, SLayout::RowMajor, 512, PadValue::Null, CompactMode::Null>(v27, v26);
      pipe_barrier(PIPE_MTE2);
      TPOP<TPipe<0, Direction::DIR_BOTH, 16384, 2, 2, true>, Tile<TileType::Mat, bfloat16_t, 32, 128, BLayout::ColMajor, -1, -1, SLayout::RowMajor, 512, PadValue::Null, CompactMode::Null>, TileSplitAxis::TILE_NO_SPLIT>(v76, v241);
      set_flag(PIPE_MTE2, PIPE_MTE1, EVENT_ID2);
      wait_flag(PIPE_MTE2, PIPE_MTE1, EVENT_ID2);
      wait_flag(PIPE_M, PIPE_MTE1, EVENT_ID6);
      wait_flag(PIPE_FIX, PIPE_M, EVENT_ID2);
      set_flag(PIPE_M, PIPE_MTE1, EVENT_ID1);
      set_flag(PIPE_M, PIPE_MTE1, EVENT_ID7);
      for (int64_t j242 = v43; j242 < v38; j242 += v33) {
        // pto: %qk_oi_inline2335__tile_l0_a
        Tile<TileType::Left, bfloat16_t, 32, 32, BLayout::RowMajor, -1, -1, SLayout::RowMajor, 512, PadValue::Null, CompactMode::Null> v243 = Tile<TileType::Left, bfloat16_t, 32, 32, BLayout::RowMajor, -1, -1, SLayout::RowMajor, 512, PadValue::Null, CompactMode::Null>(v50, v50);
        // pto: %qk_oi_inline2335__tile_l0_a
        uint64_t v244 = (uint64_t) v43;
        TASSIGN(v243, v244);
        wait_flag(PIPE_M, PIPE_MTE1, EVENT_ID7);
        TEXTRACT(v243, v241, v43, j242);
        // pto: %qk_oi_inline2335__tile_l0_b
        Tile<TileType::Right, bfloat16_t, 32, 512, BLayout::RowMajor, -1, -1, SLayout::ColMajor, 512, PadValue::Null, CompactMode::Null> v245 = Tile<TileType::Right, bfloat16_t, 32, 512, BLayout::RowMajor, -1, -1, SLayout::ColMajor, 512, PadValue::Null, CompactMode::Null>(v50, v40);
        // pto: %qk_oi_inline2335__tile_l0_b
        uint64_t v246 = (uint64_t) v43;
        TASSIGN(v245, v246);
        TEXTRACT(v245, v58, j242, v43);
        set_flag(PIPE_MTE1, PIPE_M, EVENT_ID4);
        // pto: %21
        Tile<TileType::Left, bfloat16_t, 32, 32, BLayout::RowMajor, -1, -1, SLayout::RowMajor, 512, PadValue::Null, CompactMode::Null> v247 = Tile<TileType::Left, bfloat16_t, 32, 32, BLayout::RowMajor, -1, -1, SLayout::RowMajor, 512, PadValue::Null, CompactMode::Null>(v50, v50);
        // pto: %21
        uint64_t v248 = (uint64_t) v42;
        TASSIGN(v247, v248);
        // pto: %178
        int64_t v249 = (int64_t) ((uint64_t) j242 + (uint64_t) v50);
        wait_flag(PIPE_M, PIPE_MTE1, EVENT_ID1);
        TEXTRACT(v247, v241, v43, v249);
        // pto: %22
        Tile<TileType::Right, bfloat16_t, 32, 512, BLayout::RowMajor, -1, -1, SLayout::ColMajor, 512, PadValue::Null, CompactMode::Null> v250 = Tile<TileType::Right, bfloat16_t, 32, 512, BLayout::RowMajor, -1, -1, SLayout::ColMajor, 512, PadValue::Null, CompactMode::Null>(v50, v40);
        // pto: %22
        uint64_t v251 = (uint64_t) v45;
        TASSIGN(v250, v251);
        pipe_barrier(PIPE_MTE1);
        TEXTRACT(v250, v58, v249, v43);
        set_flag(PIPE_MTE1, PIPE_M, EVENT_ID5);
        // pto: %180
        wait_flag(PIPE_MTE1, PIPE_M, EVENT_ID4);
        if (j242 == v43) {
          pipe_barrier(PIPE_M);
          TMATMUL(v239, v243, v245);
        } else {
          pipe_barrier(PIPE_M);
          TMATMUL_ACC(v239, v239, v243, v245);
        }
        set_flag(PIPE_M, PIPE_MTE1, EVENT_ID7);
        // pto: %181
        wait_flag(PIPE_MTE1, PIPE_M, EVENT_ID5);
        if (j242 == v29) {
          pipe_barrier(PIPE_M);
          TMATMUL(v239, v247, v250);
        } else {
          pipe_barrier(PIPE_M);
          TMATMUL_ACC(v239, v239, v247, v250);
        }
        set_flag(PIPE_M, PIPE_MTE1, EVENT_ID1);
      }
      wait_flag(PIPE_M, PIPE_MTE1, EVENT_ID7);
      wait_flag(PIPE_M, PIPE_MTE1, EVENT_ID1);
      set_flag(PIPE_M, PIPE_MTE1, EVENT_ID1);
      set_flag(PIPE_M, PIPE_FIX, EVENT_ID2);
      TFREE<TPipe<0, Direction::DIR_BOTH, 16384, 2, 2, true>, TileSplitAxis::TILE_NO_SPLIT>(v76);
      // pto: %184
      int64_t v252 = (int64_t) ((uint64_t) v82 * (uint64_t) v28);
      // pto: %185
      int64_t v253 = (int64_t) ((uint64_t) v83 + (uint64_t) v252);
      // pto: %t__tile
      Tile<TileType::Acc, float, 16, 512, BLayout::ColMajor, -1, -1, SLayout::RowMajor, 1024, PadValue::Null, CompactMode::Null> v254 = Tile<TileType::Acc, float, 16, 512, BLayout::ColMajor, -1, -1, SLayout::RowMajor, 1024, PadValue::Null, CompactMode::Null>(v28, v40);
      // pto: %t__tile
      uint64_t v255 = (uint64_t) v43;
      TASSIGN(v254, v255);
      // pto: %slice_view
      Tile<TileType::Acc, float, 32, 512, BLayout::ColMajor, 16, 512, SLayout::RowMajor, 1024, PadValue::Null, CompactMode::Null> v256;
      // pto: %slice_view
      Tile<TileType::Acc, float, 32, 512, BLayout::ColMajor, 16, 512, SLayout::RowMajor, 1024, PadValue::Null, CompactMode::Null> v257 = v256;
      // pto: %slice_view
      uint64_t v258 = (uint64_t) v43;
      TASSIGN(v257, v258);
      // pto: %sparse_blk_oi_inline2398__iter_v1_pview
      pto::Shape<1, 1, 1, 16, 512> v259 = pto::Shape<1, 1, 1, 16, 512>();
      // pto: %sparse_blk_oi_inline2398__iter_v1_pview
      pto::Stride<8192, 8192, 8192, 512, 1> v260 = pto::Stride<8192, 8192, 8192, 512, 1>();
      // pto: %186, %sparse_blk_oi_inline2398__iter_v1_pview
      GlobalTensor<float, pto::Shape<1, 1, 1, 16, 512>, pto::Stride<8192, 8192, 8192, 512, 1>, pto::Layout::ND> v261 = GlobalTensor<float, pto::Shape<1, 1, 1, 16, 512>, pto::Stride<8192, 8192, 8192, 512, 1>, pto::Layout::ND>(v3 + (v43 + (v253 < v43 ? v43 : v253) * v40), v259, v260);
      wait_flag(PIPE_M, PIPE_FIX, EVENT_ID2);
      pipe_barrier(PIPE_FIX);
      TSTORE(v261, v257);
      // pto: %188, %190
      int64_t v262 = (int64_t) ((uint64_t) ((int64_t) ((uint64_t) v83 + (uint64_t) v46)) + (uint64_t) v252);
      // pto: %24
      Tile<TileType::Acc, float, 16, 512, BLayout::ColMajor, -1, -1, SLayout::RowMajor, 1024, PadValue::Null, CompactMode::Null> v263 = Tile<TileType::Acc, float, 16, 512, BLayout::ColMajor, -1, -1, SLayout::RowMajor, 1024, PadValue::Null, CompactMode::Null>(v28, v40);
      // pto: %24
      uint64_t v264 = (uint64_t) v43;
      TASSIGN(v263, v264);
      // pto: %191
      Tile<TileType::Acc, float, 32, 512, BLayout::ColMajor, 16, 512, SLayout::RowMajor, 1024, PadValue::Null, CompactMode::Null> v265;
      // pto: %191
      Tile<TileType::Acc, float, 32, 512, BLayout::ColMajor, 16, 512, SLayout::RowMajor, 1024, PadValue::Null, CompactMode::Null> v266 = v265;
      // pto: %191
      uint64_t v267 = (uint64_t) v51;
      TASSIGN(v266, v267);
      // pto: %sparse_blk_oi_inline2398__tile_pview
      pto::Shape<1, 1, 1, 16, 512> v268 = pto::Shape<1, 1, 1, 16, 512>();
      // pto: %sparse_blk_oi_inline2398__tile_pview
      pto::Stride<8192, 8192, 8192, 512, 1> v269 = pto::Stride<8192, 8192, 8192, 512, 1>();
      // pto: %193, %sparse_blk_oi_inline2398__tile_pview
      GlobalTensor<float, pto::Shape<1, 1, 1, 16, 512>, pto::Stride<8192, 8192, 8192, 512, 1>, pto::Layout::ND> v270 = GlobalTensor<float, pto::Shape<1, 1, 1, 16, 512>, pto::Stride<8192, 8192, 8192, 512, 1>, pto::Layout::ND>(v3 + (v43 + (v262 < v43 ? v43 : v262) * v40), v268, v269);
      pipe_barrier(PIPE_FIX);
      TSTORE(v270, v266);
      set_flag(PIPE_FIX, PIPE_M, EVENT_ID3);
      // pto: %25
      Tile<TileType::Acc, float, 32, 512, BLayout::ColMajor, -1, -1, SLayout::RowMajor, 1024, PadValue::Null, CompactMode::Null> v271 = Tile<TileType::Acc, float, 32, 512, BLayout::ColMajor, -1, -1, SLayout::RowMajor, 1024, PadValue::Null, CompactMode::Null>(v50, v40);
      // pto: %25
      uint64_t v272 = (uint64_t) v43;
      TASSIGN(v271, v272);
      // pto: %194
      Tile<TileType::Mat, bfloat16_t, 32, 128, BLayout::ColMajor, -1, -1, SLayout::RowMajor, 512, PadValue::Null, CompactMode::Null> v273 = Tile<TileType::Mat, bfloat16_t, 32, 128, BLayout::ColMajor, -1, -1, SLayout::RowMajor, 512, PadValue::Null, CompactMode::Null>(v27, v26);
      TPOP<TPipe<0, Direction::DIR_BOTH, 16384, 2, 2, true>, Tile<TileType::Mat, bfloat16_t, 32, 128, BLayout::ColMajor, -1, -1, SLayout::RowMajor, 512, PadValue::Null, CompactMode::Null>, TileSplitAxis::TILE_NO_SPLIT>(v76, v273);
      set_flag(PIPE_MTE2, PIPE_MTE1, EVENT_ID3);
      wait_flag(PIPE_MTE2, PIPE_MTE1, EVENT_ID3);
      wait_flag(PIPE_M, PIPE_MTE1, EVENT_ID1);
      wait_flag(PIPE_FIX, PIPE_M, EVENT_ID3);
      set_flag(PIPE_M, PIPE_MTE1, EVENT_ID1);
      set_flag(PIPE_M, PIPE_MTE1, EVENT_ID2);
      for (int64_t j274 = v43; j274 < v38; j274 += v33) {
        // pto: %26
        Tile<TileType::Left, bfloat16_t, 32, 32, BLayout::RowMajor, -1, -1, SLayout::RowMajor, 512, PadValue::Null, CompactMode::Null> v275 = Tile<TileType::Left, bfloat16_t, 32, 32, BLayout::RowMajor, -1, -1, SLayout::RowMajor, 512, PadValue::Null, CompactMode::Null>(v50, v50);
        // pto: %26
        uint64_t v276 = (uint64_t) v43;
        TASSIGN(v275, v276);
        wait_flag(PIPE_M, PIPE_MTE1, EVENT_ID1);
        TEXTRACT(v275, v273, v43, j274);
        // pto: %27
        Tile<TileType::Right, bfloat16_t, 32, 512, BLayout::RowMajor, -1, -1, SLayout::ColMajor, 512, PadValue::Null, CompactMode::Null> v277 = Tile<TileType::Right, bfloat16_t, 32, 512, BLayout::RowMajor, -1, -1, SLayout::ColMajor, 512, PadValue::Null, CompactMode::Null>(v50, v40);
        // pto: %27
        uint64_t v278 = (uint64_t) v43;
        TASSIGN(v277, v278);
        TEXTRACT(v277, v58, j274, v43);
        set_flag(PIPE_MTE1, PIPE_M, EVENT_ID6);
        // pto: %28
        Tile<TileType::Left, bfloat16_t, 32, 32, BLayout::RowMajor, -1, -1, SLayout::RowMajor, 512, PadValue::Null, CompactMode::Null> v279 = Tile<TileType::Left, bfloat16_t, 32, 32, BLayout::RowMajor, -1, -1, SLayout::RowMajor, 512, PadValue::Null, CompactMode::Null>(v50, v50);
        // pto: %28
        uint64_t v280 = (uint64_t) v42;
        TASSIGN(v279, v280);
        // pto: %196
        int64_t v281 = (int64_t) ((uint64_t) j274 + (uint64_t) v50);
        wait_flag(PIPE_M, PIPE_MTE1, EVENT_ID2);
        TEXTRACT(v279, v273, v43, v281);
        // pto: %29
        Tile<TileType::Right, bfloat16_t, 32, 512, BLayout::RowMajor, -1, -1, SLayout::ColMajor, 512, PadValue::Null, CompactMode::Null> v282 = Tile<TileType::Right, bfloat16_t, 32, 512, BLayout::RowMajor, -1, -1, SLayout::ColMajor, 512, PadValue::Null, CompactMode::Null>(v50, v40);
        // pto: %29
        uint64_t v283 = (uint64_t) v45;
        TASSIGN(v282, v283);
        pipe_barrier(PIPE_MTE1);
        TEXTRACT(v282, v58, v281, v43);
        set_flag(PIPE_MTE1, PIPE_M, EVENT_ID7);
        // pto: %198
        wait_flag(PIPE_MTE1, PIPE_M, EVENT_ID6);
        if (j274 == v43) {
          pipe_barrier(PIPE_M);
          TMATMUL(v271, v275, v277);
        } else {
          pipe_barrier(PIPE_M);
          TMATMUL_ACC(v271, v271, v275, v277);
        }
        set_flag(PIPE_M, PIPE_MTE1, EVENT_ID1);
        // pto: %199
        wait_flag(PIPE_MTE1, PIPE_M, EVENT_ID7);
        if (j274 == v29) {
          pipe_barrier(PIPE_M);
          TMATMUL(v271, v279, v282);
        } else {
          pipe_barrier(PIPE_M);
          TMATMUL_ACC(v271, v271, v279, v282);
        }
        set_flag(PIPE_M, PIPE_MTE1, EVENT_ID2);
      }
      wait_flag(PIPE_M, PIPE_MTE1, EVENT_ID2);
      wait_flag(PIPE_M, PIPE_MTE1, EVENT_ID1);
      set_flag(PIPE_MTE1, PIPE_MTE2, EVENT_ID0);
      set_flag(PIPE_M, PIPE_MTE1, EVENT_ID0);
      set_flag(PIPE_M, PIPE_FIX, EVENT_ID3);
      TFREE<TPipe<0, Direction::DIR_BOTH, 16384, 2, 2, true>, TileSplitAxis::TILE_NO_SPLIT>(v76);
      // pto: %201, %203
      int64_t v284 = (int64_t) ((uint64_t) ((int64_t) ((uint64_t) v83 + (uint64_t) v47)) + (uint64_t) v252);
      // pto: %32
      Tile<TileType::Acc, float, 16, 512, BLayout::ColMajor, -1, -1, SLayout::RowMajor, 1024, PadValue::Null, CompactMode::Null> v285 = Tile<TileType::Acc, float, 16, 512, BLayout::ColMajor, -1, -1, SLayout::RowMajor, 1024, PadValue::Null, CompactMode::Null>(v28, v40);
      // pto: %32
      uint64_t v286 = (uint64_t) v43;
      TASSIGN(v285, v286);
      // pto: %204
      Tile<TileType::Acc, float, 32, 512, BLayout::ColMajor, 16, 512, SLayout::RowMajor, 1024, PadValue::Null, CompactMode::Null> v287;
      // pto: %204
      Tile<TileType::Acc, float, 32, 512, BLayout::ColMajor, 16, 512, SLayout::RowMajor, 1024, PadValue::Null, CompactMode::Null> v288 = v287;
      // pto: %204
      uint64_t v289 = (uint64_t) v43;
      TASSIGN(v288, v289);
      // pto: %207
      pto::Shape<1, 1, 1, 16, 512> v290 = pto::Shape<1, 1, 1, 16, 512>();
      // pto: %207
      pto::Stride<8192, 8192, 8192, 512, 1> v291 = pto::Stride<8192, 8192, 8192, 512, 1>();
      // pto: %206, %207
      GlobalTensor<float, pto::Shape<1, 1, 1, 16, 512>, pto::Stride<8192, 8192, 8192, 512, 1>, pto::Layout::ND> v292 = GlobalTensor<float, pto::Shape<1, 1, 1, 16, 512>, pto::Stride<8192, 8192, 8192, 512, 1>, pto::Layout::ND>(v3 + (v43 + (v284 < v43 ? v43 : v284) * v40), v290, v291);
      wait_flag(PIPE_M, PIPE_FIX, EVENT_ID3);
      pipe_barrier(PIPE_FIX);
      TSTORE(v292, v288);
      // pto: %209, %211
      int64_t v293 = (int64_t) ((uint64_t) ((int64_t) ((uint64_t) v83 + (uint64_t) v48)) + (uint64_t) v252);
      // pto: %33
      Tile<TileType::Acc, float, 16, 512, BLayout::ColMajor, -1, -1, SLayout::RowMajor, 1024, PadValue::Null, CompactMode::Null> v294 = Tile<TileType::Acc, float, 16, 512, BLayout::ColMajor, -1, -1, SLayout::RowMajor, 1024, PadValue::Null, CompactMode::Null>(v28, v40);
      // pto: %33
      uint64_t v295 = (uint64_t) v43;
      TASSIGN(v294, v295);
      // pto: %212
      Tile<TileType::Acc, float, 32, 512, BLayout::ColMajor, 16, 512, SLayout::RowMajor, 1024, PadValue::Null, CompactMode::Null> v296;
      // pto: %212
      Tile<TileType::Acc, float, 32, 512, BLayout::ColMajor, 16, 512, SLayout::RowMajor, 1024, PadValue::Null, CompactMode::Null> v297 = v296;
      // pto: %212
      uint64_t v298 = (uint64_t) v51;
      TASSIGN(v297, v298);
      // pto: %215
      pto::Shape<1, 1, 1, 16, 512> v299 = pto::Shape<1, 1, 1, 16, 512>();
      // pto: %215
      pto::Stride<8192, 8192, 8192, 512, 1> v300 = pto::Stride<8192, 8192, 8192, 512, 1>();
      // pto: %214, %215
      GlobalTensor<float, pto::Shape<1, 1, 1, 16, 512>, pto::Stride<8192, 8192, 8192, 512, 1>, pto::Layout::ND> v301 = GlobalTensor<float, pto::Shape<1, 1, 1, 16, 512>, pto::Stride<8192, 8192, 8192, 512, 1>, pto::Layout::ND>(v3 + (v43 + (v293 < v43 ? v43 : v293) * v40), v299, v300);
      pipe_barrier(PIPE_FIX);
      TSTORE(v301, v297);
      set_flag(PIPE_FIX, PIPE_M, EVENT_ID0);
    }
  }
  wait_flag(PIPE_M, PIPE_MTE1, EVENT_ID0);
  wait_flag(PIPE_MTE1, PIPE_MTE2, EVENT_ID0);
  wait_flag(PIPE_FIX, PIPE_M, EVENT_ID0);
  #endif // __DAV_CUBE__

  ptoas_auto_sync_tail(PTOAutoSyncTailMode::kBarrierAll);
  return;
}

static __aicore__ void qk_pv_aiv(__gm__ float* v1, __gm__ float* v2, __gm__ float* v3, __gm__ int32_t* v4, __gm__ float* v5, __gm__ int32_t* v6, __gm__ int32_t* v7, __gm__ int32_t* v8, __gm__ bfloat16_t* v9, __gm__ int32_t* v10, __gm__ int32_t* v11, __gm__ bfloat16_t* v12, __gm__ bfloat16_t* v13, __gm__ float* v14, int64_t v15, int64_t v16, int64_t v17, int64_t v18, int64_t v19, int64_t v20, int64_t v21, int64_t v22, int64_t v23, int32_t v24, int32_t v25, int32_t v26) {
  SaturationMode v27 = SaturationMode::OFF;
  RoundMode v28 = RoundMode::CAST_RINT;
  const int32_t v29 = 128;
  const int32_t v30 = 32;
  const int64_t v31 = 640;
  const float v32 = -3.00000001E+38f;
  const int64_t v33 = 4;
  const float v34 = 0.0f;
  const int64_t v35 = 16;
  const int64_t v36 = 80;
  const float v37 = 0.0441941731f;
  const int64_t v38 = 32;
  const int64_t v39 = 2;
  const int64_t v40 = 320;
  const int64_t v41 = 24;
  const int64_t v42 = 23;
  const int64_t v43 = 0;
  const int64_t v44 = 128;
  const int64_t v45 = 5;
  const int64_t v46 = 512;
  const int64_t v47 = 1;
  const int64_t v48 = 49792;
  const int64_t v49 = 49664;
  const int64_t v50 = 33280;
  const int64_t v51 = 49920;
  const int64_t v52 = 32768;
  const int32_t v53 = 0;
  const int64_t v54 = 160;
  const int64_t v55 = 49728;
  const int64_t v56 = 49856;
  using T = float;

  #if defined(__DAV_VEC__)
  set_mask_norm();
  set_vector_mask(-1, -1);
  // pto: %sparse_blk_li_inline2405__ssa_v0_view
  int64_t v57 = v16 * v47;
  // pto: %sparse_blk_li_inline2405__ssa_v0_view
  int64_t v58 = v47 * v57;
  // pto: %sparse_blk_li_inline2405__ssa_v0_view
  pto::Shape<1, 1, 1, -1, -1> v59 = pto::Shape<1, 1, 1, -1, -1>(v47, v47, v47, v16, v47);
  // pto: %sparse_blk_li_inline2405__ssa_v0_view
  pto::Stride<-1, -1, -1, -1, -1> v60 = pto::Stride<-1, -1, -1, -1, -1>(v47 * v58, v58, v57, v47, v16);
  // pto: %sparse_blk_li_inline2405__ssa_v0_view
  GlobalTensor<float, pto::Shape<1, 1, 1, -1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::DN> v61 = GlobalTensor<float, pto::Shape<1, 1, 1, -1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::DN>(v1, v59, v60);
  // pto: %sparse_blk_mi_inline2404__ssa_v0_view
  int64_t v62 = v16 * v47;
  // pto: %sparse_blk_mi_inline2404__ssa_v0_view
  int64_t v63 = v47 * v62;
  // pto: %sparse_blk_mi_inline2404__ssa_v0_view
  pto::Shape<1, 1, 1, -1, -1> v64 = pto::Shape<1, 1, 1, -1, -1>(v47, v47, v47, v16, v47);
  // pto: %sparse_blk_mi_inline2404__ssa_v0_view
  pto::Stride<-1, -1, -1, -1, -1> v65 = pto::Stride<-1, -1, -1, -1, -1>(v47 * v63, v63, v62, v47, v16);
  // pto: %sparse_blk_mi_inline2404__ssa_v0_view
  GlobalTensor<float, pto::Shape<1, 1, 1, -1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::DN> v66 = GlobalTensor<float, pto::Shape<1, 1, 1, -1, -1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::DN>(v2, v64, v65);
  auto v67 = TPipe<0, Direction::DIR_BOTH, 16384, 2, 2, true>(v14, v53, v53);
  // pto: %subblock_idx, %26
  set_flag(PIPE_V, PIPE_MTE2, EVENT_ID0);
  set_flag(PIPE_MTE3, PIPE_V, EVENT_ID0);
  set_flag(PIPE_V, PIPE_MTE2, EVENT_ID1);
  set_flag(PIPE_MTE3, PIPE_V, EVENT_ID1);
  set_flag(PIPE_MTE3, PIPE_V, EVENT_ID2);
  set_flag(PIPE_MTE3, PIPE_V, EVENT_ID3);
  set_flag(PIPE_MTE3, PIPE_V, EVENT_ID4);
  set_flag(PIPE_MTE3, PIPE_V, EVENT_ID6);
  set_flag(PIPE_V, PIPE_MTE2, EVENT_ID2);
  set_flag(PIPE_MTE3, PIPE_V, EVENT_ID7);
  if ((int64_t) v26 == v43) {
    // pto: %qk_core_inline2368__ssa_v0
    int64_t v68 = (int64_t) v24;
    // pto: %27, %28, %29
    for (int64_t i69 = v43; i69 < ((int64_t) ((uint64_t) ((int64_t) ((uint64_t) v15 - (uint64_t) v68)) + (uint64_t) v42) / v41); i69 += v47) {
      // pto: %31, %30, %32
      int32_t v70 = (v4)[(int64_t) ((uint64_t) v68 + (uint64_t) ((int64_t) ((uint64_t) i69 * (uint64_t) v41)))];
      // pto: %33
      int64_t v71 = (int64_t) v70;
      // pto: %34
      int64_t v72 = v71 / v45;
      // pto: %36, %35
      int64_t v73 = (int64_t) ((uint64_t) v71 - (uint64_t) ((int64_t) ((uint64_t) v72 * (uint64_t) v45)));
      // pto: %37
      int64_t v74 = (int64_t) ((uint64_t) v72 * (uint64_t) v40);
      // pto: %38
      int64_t v75 = (int64_t) ((uint64_t) v73 * (uint64_t) v44);
      // pto: %qk_bias_row_inline2419__tile
      Tile<TileType::Vec, float, 1, 128, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v76 = Tile<TileType::Vec, float, 1, 128, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v47, v44);
      // pto: %qk_bias_row_inline2419__tile
      uint64_t v77 = (uint64_t) v52;
      TASSIGN(v76, v77);
      // pto: %sparse_bias_inline2381__rv_v2_pview
      pto::Shape<1, 1, 1, 1, 128> v78 = pto::Shape<1, 1, 1, 1, 128>();
      // pto: %sparse_bias_inline2381__rv_v2_pview
      pto::Stride<640, 640, 640, 640, 1> v79 = pto::Stride<640, 640, 640, 640, 1>();
      // pto: %39, %sparse_bias_inline2381__rv_v2_pview, %40
      GlobalTensor<float, pto::Shape<1, 1, 1, 1, 128>, pto::Stride<640, 640, 640, 640, 1>, pto::Layout::ND> v80 = GlobalTensor<float, pto::Shape<1, 1, 1, 1, 128>, pto::Stride<640, 640, 640, 640, 1>, pto::Layout::ND>(v5 + ((v43 + (v72 < v43 ? v43 : v72) * v31) + (v75 < v43 ? v43 : v75)), v78, v79);
      wait_flag(PIPE_V, PIPE_MTE2, EVENT_ID0);
      TLOAD(v76, v80);
      // pto: %qk_block_valid_inline2422__tile
      int32_t v81 = (v6)[v71];
      // pto: %41, %42
      wait_flag(PIPE_MTE3, PIPE_V, EVENT_ID0);
      if ((int64_t) v81 > v43) {
        for (int64_t j82 = v43; j82 < v39; j82 += v47) {
          // pto: %qk_raw_inline2397__tile_Vec
          Tile<TileType::Vec, float, 32, 128, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v83 = Tile<TileType::Vec, float, 32, 128, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v30, v29);
          wait_flag(PIPE_V, PIPE_MTE2, EVENT_ID1);
          TPOP<TPipe<0, Direction::DIR_BOTH, 16384, 2, 2, true>, Tile<TileType::Vec, float, 32, 128, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>, TileSplitAxis::TILE_NO_SPLIT>(v67, v83);
          set_flag(PIPE_MTE2, PIPE_V, EVENT_ID0);
          // pto: %qk_scaled_inline2416__tile
          Tile<TileType::Vec, float, 32, 128, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v84 = Tile<TileType::Vec, float, 32, 128, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v38, v44);
          // pto: %qk_scaled_inline2416__tile
          uint64_t v85 = (uint64_t) v51;
          TASSIGN(v84, v85);
          wait_flag(PIPE_MTE2, PIPE_V, EVENT_ID0);
          wait_flag(PIPE_MTE3, PIPE_V, EVENT_ID1);
          pipe_barrier(PIPE_V);
          TMULS(v84, v83, v37);
          set_flag(PIPE_V, PIPE_MTE2, EVENT_ID1);
          TFREE<TPipe<0, Direction::DIR_BOTH, 16384, 2, 2, true>, TileSplitAxis::TILE_NO_SPLIT>(v67);
          // pto: %qk_scores_inline2325__tile
          Tile<TileType::Vec, float, 32, 128, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v86 = Tile<TileType::Vec, float, 32, 128, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v38, v44);
          // pto: %qk_scores_inline2325__tile
          uint64_t v87 = (uint64_t) v51;
          TASSIGN(v86, v87);
          pipe_barrier(PIPE_V);
          TCOLEXPANDADD(v86, v84, v76);
          // pto: %tmp_tile
          Tile<TileType::Vec, float, 32, 128, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v88 = Tile<TileType::Vec, float, 32, 128, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v38, v44);
          // pto: %tmp_tile
          uint64_t v89 = (uint64_t) v50;
          TASSIGN(v88, v89);
          // pto: %qk_mi_inline2360__tile
          Tile<TileType::Vec, float, 32, 1, BLayout::ColMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v90 = Tile<TileType::Vec, float, 32, 1, BLayout::ColMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v38, v47);
          // pto: %qk_mi_inline2360__tile
          uint64_t v91 = (uint64_t) v49;
          TASSIGN(v90, v91);
          pipe_barrier(PIPE_V);
          wait_flag(PIPE_MTE3, PIPE_V, EVENT_ID2);
          TROWMAX(v90, v86, v88);
          // pto: %t__tile
          Tile<TileType::Vec, float, 32, 128, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v92 = Tile<TileType::Vec, float, 32, 128, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v38, v44);
          // pto: %t__tile
          uint64_t v93 = (uint64_t) v51;
          TASSIGN(v92, v93);
          pipe_barrier(PIPE_V);
          TROWEXPANDSUB(v92, v86, v90);
          // pto: %qk_exp_inline2324__tile
          Tile<TileType::Vec, float, 32, 128, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v94 = Tile<TileType::Vec, float, 32, 128, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v38, v44);
          // pto: %qk_exp_inline2324__tile
          uint64_t v95 = (uint64_t) v51;
          TASSIGN(v94, v95);
          pipe_barrier(PIPE_V);
          TEXP(v94, v92);
          // pto: %0
          Tile<TileType::Vec, float, 32, 128, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v96 = Tile<TileType::Vec, float, 32, 128, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v38, v44);
          // pto: %0
          uint64_t v97 = (uint64_t) v50;
          TASSIGN(v96, v97);
          // pto: %qk_li_inline2323__tile
          Tile<TileType::Vec, float, 32, 1, BLayout::ColMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v98 = Tile<TileType::Vec, float, 32, 1, BLayout::ColMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v38, v47);
          // pto: %qk_li_inline2323__tile
          uint64_t v99 = (uint64_t) v48;
          TASSIGN(v98, v99);
          pipe_barrier(PIPE_V);
          wait_flag(PIPE_MTE3, PIPE_V, EVENT_ID3);
          TROWSUM(v98, v94, v96);
          // pto: %qk_exp_bf16_inline2322__tile
          Tile<TileType::Vec, bfloat16_t, 32, 128, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v100 = Tile<TileType::Vec, bfloat16_t, 32, 128, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v38, v44);
          // pto: %qk_exp_bf16_inline2322__tile
          uint64_t v101 = (uint64_t) v51;
          TASSIGN(v100, v101);
          pipe_barrier(PIPE_V);
          TCVT(v100, v94, v28, v27);
          set_flag(PIPE_V, PIPE_MTE3, EVENT_ID0);
          wait_flag(PIPE_V, PIPE_MTE3, EVENT_ID0);
          TPUSH<TPipe<0, Direction::DIR_BOTH, 16384, 2, 2, true>, Tile<TileType::Vec, bfloat16_t, 32, 128, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>, TileSplitAxis::TILE_NO_SPLIT>(v67, v100);
          set_flag(PIPE_MTE3, PIPE_V, EVENT_ID1);
          // pto: %46
          int64_t v102 = (int64_t) ((uint64_t) v73 * (uint64_t) v35);
          // pto: %45, %47
          int64_t v103 = (int64_t) ((uint64_t) ((int64_t) ((uint64_t) v74 + (uint64_t) ((int64_t) ((uint64_t) j82 * (uint64_t) v54)))) + (uint64_t) v102);
          // pto: %1
          Tile<TileType::Vec, float, 16, 1, BLayout::ColMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v104 = Tile<TileType::Vec, float, 16, 1, BLayout::ColMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v35, v47);
          // pto: %1
          uint64_t v105 = (uint64_t) v49;
          TASSIGN(v104, v105);
          // pto: %slice_view
          Tile<TileType::Vec, float, 32, 1, BLayout::ColMajor, 16, 1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v106;
          // pto: %slice_view
          Tile<TileType::Vec, float, 32, 1, BLayout::ColMajor, 16, 1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v107 = v106;
          // pto: %slice_view
          uint64_t v108 = (uint64_t) v49;
          TASSIGN(v107, v108);
          // pto: %49
          int64_t v109 = v103 < v43 ? v43 : v103;
          // pto: %sparse_blk_mi_inline2404__iter_v3_pview
          __gm__ float* v110 = PTOAS__GLOBAL_TENSOR_DATA(v66);
          // pto: %sparse_blk_mi_inline2404__iter_v3_pview
          int64_t v111 = v35 * v47;
          // pto: %sparse_blk_mi_inline2404__iter_v3_pview
          int64_t v112 = v47 * v111;
          // pto: %sparse_blk_mi_inline2404__iter_v3_pview
          pto::Shape<1, 1, 1, 16, 1> v113 = pto::Shape<1, 1, 1, 16, 1>(v47, v47, v47, v35, v47);
          // pto: %sparse_blk_mi_inline2404__iter_v3_pview
          pto::Stride<-1, -1, -1, -1, -1> v114 = pto::Stride<-1, -1, -1, -1, -1>(v47 * v112, v112, v111, v47, v16);
          // pto: %sparse_blk_mi_inline2404__iter_v3_pview
          GlobalTensor<float, pto::Shape<1, 1, 1, 16, 1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::DN> v115 = GlobalTensor<float, pto::Shape<1, 1, 1, 16, 1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::DN>(v110 + ((v43 + v109 * v47) + v43 * v16), v113, v114);
          TSTORE(v115, v107);
          // pto: %2
          Tile<TileType::Vec, float, 16, 1, BLayout::ColMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v116 = Tile<TileType::Vec, float, 16, 1, BLayout::ColMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v35, v47);
          // pto: %2
          uint64_t v117 = (uint64_t) v48;
          TASSIGN(v116, v117);
          // pto: %50
          Tile<TileType::Vec, float, 32, 1, BLayout::ColMajor, 16, 1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v118;
          // pto: %50
          Tile<TileType::Vec, float, 32, 1, BLayout::ColMajor, 16, 1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v119 = v118;
          // pto: %50
          uint64_t v120 = (uint64_t) v48;
          TASSIGN(v119, v120);
          // pto: %sparse_blk_li_inline2405__iter_v3_pview
          __gm__ float* v121 = PTOAS__GLOBAL_TENSOR_DATA(v61);
          // pto: %sparse_blk_li_inline2405__iter_v3_pview
          int64_t v122 = v35 * v47;
          // pto: %sparse_blk_li_inline2405__iter_v3_pview
          int64_t v123 = v47 * v122;
          // pto: %sparse_blk_li_inline2405__iter_v3_pview
          pto::Shape<1, 1, 1, 16, 1> v124 = pto::Shape<1, 1, 1, 16, 1>(v47, v47, v47, v35, v47);
          // pto: %sparse_blk_li_inline2405__iter_v3_pview
          pto::Stride<-1, -1, -1, -1, -1> v125 = pto::Stride<-1, -1, -1, -1, -1>(v47 * v123, v123, v122, v47, v16);
          // pto: %sparse_blk_li_inline2405__iter_v3_pview
          GlobalTensor<float, pto::Shape<1, 1, 1, 16, 1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::DN> v126 = GlobalTensor<float, pto::Shape<1, 1, 1, 16, 1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::DN>(v121 + ((v43 + v109 * v47) + v43 * v16), v124, v125);
          TSTORE(v126, v119);
          // pto: %56, %43, %54, %55, %58
          int64_t v127 = (int64_t) ((uint64_t) ((int64_t) ((uint64_t) v74 + (uint64_t) ((int64_t) ((uint64_t) ((int64_t) ((uint64_t) ((int64_t) ((uint64_t) j82 * (uint64_t) v39)) + (uint64_t) v47)) * (uint64_t) v36)))) + (uint64_t) v102);
          // pto: %3
          Tile<TileType::Vec, float, 16, 1, BLayout::ColMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v128 = Tile<TileType::Vec, float, 16, 1, BLayout::ColMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v35, v47);
          // pto: %3
          uint64_t v129 = (uint64_t) v49;
          TASSIGN(v128, v129);
          // pto: %59
          Tile<TileType::Vec, float, 32, 1, BLayout::ColMajor, 16, 1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v130;
          // pto: %59
          Tile<TileType::Vec, float, 32, 1, BLayout::ColMajor, 16, 1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v131 = v130;
          // pto: %59
          uint64_t v132 = (uint64_t) v55;
          TASSIGN(v131, v132);
          // pto: %61
          int64_t v133 = v127 < v43 ? v43 : v127;
          // pto: %sparse_blk_mi_inline2404__tile_pview
          __gm__ float* v134 = PTOAS__GLOBAL_TENSOR_DATA(v66);
          // pto: %sparse_blk_mi_inline2404__tile_pview
          int64_t v135 = v35 * v47;
          // pto: %sparse_blk_mi_inline2404__tile_pview
          int64_t v136 = v47 * v135;
          // pto: %sparse_blk_mi_inline2404__tile_pview
          pto::Shape<1, 1, 1, 16, 1> v137 = pto::Shape<1, 1, 1, 16, 1>(v47, v47, v47, v35, v47);
          // pto: %sparse_blk_mi_inline2404__tile_pview
          pto::Stride<-1, -1, -1, -1, -1> v138 = pto::Stride<-1, -1, -1, -1, -1>(v47 * v136, v136, v135, v47, v16);
          // pto: %sparse_blk_mi_inline2404__tile_pview
          GlobalTensor<float, pto::Shape<1, 1, 1, 16, 1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::DN> v139 = GlobalTensor<float, pto::Shape<1, 1, 1, 16, 1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::DN>(v134 + ((v43 + v133 * v47) + v43 * v16), v137, v138);
          pipe_barrier(PIPE_MTE3);
          TSTORE(v139, v131);
          set_flag(PIPE_MTE3, PIPE_V, EVENT_ID2);
          // pto: %4
          Tile<TileType::Vec, float, 16, 1, BLayout::ColMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v140 = Tile<TileType::Vec, float, 16, 1, BLayout::ColMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v35, v47);
          // pto: %4
          uint64_t v141 = (uint64_t) v48;
          TASSIGN(v140, v141);
          // pto: %62
          Tile<TileType::Vec, float, 32, 1, BLayout::ColMajor, 16, 1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v142;
          // pto: %62
          Tile<TileType::Vec, float, 32, 1, BLayout::ColMajor, 16, 1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v143 = v142;
          // pto: %62
          uint64_t v144 = (uint64_t) v56;
          TASSIGN(v143, v144);
          // pto: %sparse_blk_li_inline2405__tile_pview
          __gm__ float* v145 = PTOAS__GLOBAL_TENSOR_DATA(v61);
          // pto: %sparse_blk_li_inline2405__tile_pview
          int64_t v146 = v35 * v47;
          // pto: %sparse_blk_li_inline2405__tile_pview
          int64_t v147 = v47 * v146;
          // pto: %sparse_blk_li_inline2405__tile_pview
          pto::Shape<1, 1, 1, 16, 1> v148 = pto::Shape<1, 1, 1, 16, 1>(v47, v47, v47, v35, v47);
          // pto: %sparse_blk_li_inline2405__tile_pview
          pto::Stride<-1, -1, -1, -1, -1> v149 = pto::Stride<-1, -1, -1, -1, -1>(v47 * v147, v147, v146, v47, v16);
          // pto: %sparse_blk_li_inline2405__tile_pview
          GlobalTensor<float, pto::Shape<1, 1, 1, 16, 1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::DN> v150 = GlobalTensor<float, pto::Shape<1, 1, 1, 16, 1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::DN>(v145 + ((v43 + v133 * v47) + v43 * v16), v148, v149);
          TSTORE(v150, v143);
          set_flag(PIPE_MTE3, PIPE_V, EVENT_ID3);
        }
      } else {
        // pto: %qk_oi_zero_inline2318__tile
        Tile<TileType::Vec, float, 16, 512, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v151 = Tile<TileType::Vec, float, 16, 512, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v35, v46);
        // pto: %qk_oi_zero_inline2318__tile
        uint64_t v152 = (uint64_t) v51;
        TASSIGN(v151, v152);
        pipe_barrier(PIPE_V);
        TEXPANDS(v151, v34);
        for (int64_t j153 = v43; j153 < v33; j153 += v47) {
          // pto: %66, %65, %68, %67
          int64_t v154 = (int64_t) ((uint64_t) ((int64_t) ((uint64_t) v74 + (uint64_t) ((int64_t) ((uint64_t) j153 * (uint64_t) v36)))) + (uint64_t) ((int64_t) ((uint64_t) v73 * (uint64_t) v35)));
          // pto: %sparse_blk_mi_inline2404__tile
          Tile<TileType::Vec, float, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v155 = Tile<TileType::Vec, float, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v47, v35);
          // pto: %sparse_blk_mi_inline2404__tile
          uint64_t v156 = (uint64_t) v50;
          TASSIGN(v155, v156);
          wait_flag(PIPE_MTE3, PIPE_V, EVENT_ID4);
          TEXPANDS(v155, v32);
          set_flag(PIPE_V, PIPE_MTE3, EVENT_ID1);
          // pto: %5
          Tile<TileType::Vec, float, 16, 1, BLayout::ColMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v157 = Tile<TileType::Vec, float, 16, 1, BLayout::ColMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v35, v47);
          // pto: %5
          uint64_t v158 = (uint64_t) v50;
          TASSIGN(v157, v158);
          // pto: %69
          int64_t v159 = v154 < v43 ? v43 : v154;
          // pto: %sparse_blk_mi_inline2404__iter_v1_pview
          __gm__ float* v160 = PTOAS__GLOBAL_TENSOR_DATA(v66);
          // pto: %sparse_blk_mi_inline2404__iter_v1_pview
          int64_t v161 = v35 * v47;
          // pto: %sparse_blk_mi_inline2404__iter_v1_pview
          int64_t v162 = v47 * v161;
          // pto: %sparse_blk_mi_inline2404__iter_v1_pview
          pto::Shape<1, 1, 1, 16, 1> v163 = pto::Shape<1, 1, 1, 16, 1>(v47, v47, v47, v35, v47);
          // pto: %sparse_blk_mi_inline2404__iter_v1_pview
          pto::Stride<-1, -1, -1, -1, -1> v164 = pto::Stride<-1, -1, -1, -1, -1>(v47 * v162, v162, v161, v47, v16);
          // pto: %sparse_blk_mi_inline2404__iter_v1_pview
          GlobalTensor<float, pto::Shape<1, 1, 1, 16, 1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::DN> v165 = GlobalTensor<float, pto::Shape<1, 1, 1, 16, 1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::DN>(v160 + ((v43 + v159 * v47) + v43 * v16), v163, v164);
          wait_flag(PIPE_V, PIPE_MTE3, EVENT_ID1);
          pipe_barrier(PIPE_MTE3);
          TSTORE(v165, v157);
          set_flag(PIPE_MTE3, PIPE_V, EVENT_ID5);
          // pto: %sparse_blk_li_inline2405__tile
          Tile<TileType::Vec, float, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v166 = Tile<TileType::Vec, float, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v47, v35);
          // pto: %sparse_blk_li_inline2405__tile
          uint64_t v167 = (uint64_t) v50;
          TASSIGN(v166, v167);
          wait_flag(PIPE_MTE3, PIPE_V, EVENT_ID5);
          TEXPANDS(v166, v34);
          set_flag(PIPE_V, PIPE_MTE3, EVENT_ID2);
          // pto: %6
          Tile<TileType::Vec, float, 16, 1, BLayout::ColMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v168 = Tile<TileType::Vec, float, 16, 1, BLayout::ColMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v35, v47);
          // pto: %6
          uint64_t v169 = (uint64_t) v50;
          TASSIGN(v168, v169);
          // pto: %sparse_blk_li_inline2405__iter_v1_pview
          __gm__ float* v170 = PTOAS__GLOBAL_TENSOR_DATA(v61);
          // pto: %sparse_blk_li_inline2405__iter_v1_pview
          int64_t v171 = v35 * v47;
          // pto: %sparse_blk_li_inline2405__iter_v1_pview
          int64_t v172 = v47 * v171;
          // pto: %sparse_blk_li_inline2405__iter_v1_pview
          pto::Shape<1, 1, 1, 16, 1> v173 = pto::Shape<1, 1, 1, 16, 1>(v47, v47, v47, v35, v47);
          // pto: %sparse_blk_li_inline2405__iter_v1_pview
          pto::Stride<-1, -1, -1, -1, -1> v174 = pto::Stride<-1, -1, -1, -1, -1>(v47 * v172, v172, v171, v47, v16);
          // pto: %sparse_blk_li_inline2405__iter_v1_pview
          GlobalTensor<float, pto::Shape<1, 1, 1, 16, 1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::DN> v175 = GlobalTensor<float, pto::Shape<1, 1, 1, 16, 1>, pto::Stride<-1, -1, -1, -1, -1>, pto::Layout::DN>(v170 + ((v43 + v159 * v47) + v43 * v16), v173, v174);
          wait_flag(PIPE_V, PIPE_MTE3, EVENT_ID2);
          TSTORE(v175, v168);
          set_flag(PIPE_MTE3, PIPE_V, EVENT_ID4);
          // pto: %sparse_blk_oi_inline2398__iter_v7_pview
          pto::Shape<1, 1, 1, 16, 512> v176 = pto::Shape<1, 1, 1, 16, 512>();
          // pto: %sparse_blk_oi_inline2398__iter_v7_pview
          pto::Stride<8192, 8192, 8192, 512, 1> v177 = pto::Stride<8192, 8192, 8192, 512, 1>();
          // pto: %sparse_blk_oi_inline2398__iter_v7_pview
          GlobalTensor<float, pto::Shape<1, 1, 1, 16, 512>, pto::Stride<8192, 8192, 8192, 512, 1>, pto::Layout::ND> v178 = GlobalTensor<float, pto::Shape<1, 1, 1, 16, 512>, pto::Stride<8192, 8192, 8192, 512, 1>, pto::Layout::ND>(v3 + (v43 + v159 * v46), v176, v177);
          TSTORE(v178, v151);
        }
      }
      set_flag(PIPE_V, PIPE_MTE2, EVENT_ID0);
      set_flag(PIPE_MTE3, PIPE_V, EVENT_ID0);
    }
  } else {
    // pto: %72
    int64_t v179 = (int64_t) v24;
    // pto: %73, %74, %75
    for (int64_t i180 = v43; i180 < ((int64_t) ((uint64_t) ((int64_t) ((uint64_t) v15 - (uint64_t) v179)) + (uint64_t) v42) / v41); i180 += v47) {
      // pto: %78, %77, %79
      int32_t v181 = (v4)[(int64_t) ((uint64_t) v179 + (uint64_t) ((int64_t) ((uint64_t) i180 * (uint64_t) v41)))];
      // pto: %7
      Tile<TileType::Vec, float, 1, 128, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v182 = Tile<TileType::Vec, float, 1, 128, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v43, v43);
      // pto: %7
      uint64_t v183 = (uint64_t) v52;
      TASSIGN(v182, v183);
      // pto: %80, %84
      int32_t v184 = (v6)[(int64_t) v181];
      // pto: %87, %88
      wait_flag(PIPE_MTE3, PIPE_V, EVENT_ID6);
      if ((int64_t) v184 > v43) {
        for (int64_t j185 = v43; j185 < v39; j185 += v47) {
          // pto: %90
          Tile<TileType::Vec, float, 32, 128, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v186 = Tile<TileType::Vec, float, 32, 128, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v30, v29);
          v186.SetValidShape(v43, v43);
          wait_flag(PIPE_V, PIPE_MTE2, EVENT_ID2);
          TPOP<TPipe<0, Direction::DIR_BOTH, 16384, 2, 2, true>, Tile<TileType::Vec, float, 32, 128, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>, TileSplitAxis::TILE_NO_SPLIT>(v67, v186);
          set_flag(PIPE_MTE2, PIPE_V, EVENT_ID1);
          // pto: %8
          Tile<TileType::Vec, float, 32, 128, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v187 = Tile<TileType::Vec, float, 32, 128, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v43, v43);
          // pto: %8
          uint64_t v188 = (uint64_t) v51;
          TASSIGN(v187, v188);
          wait_flag(PIPE_MTE2, PIPE_V, EVENT_ID1);
          wait_flag(PIPE_MTE3, PIPE_V, EVENT_ID7);
          pipe_barrier(PIPE_V);
          TMULS(v187, v186, v37);
          set_flag(PIPE_V, PIPE_MTE2, EVENT_ID2);
          TFREE<TPipe<0, Direction::DIR_BOTH, 16384, 2, 2, true>, TileSplitAxis::TILE_NO_SPLIT>(v67);
          // pto: %9
          Tile<TileType::Vec, float, 32, 128, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v189 = Tile<TileType::Vec, float, 32, 128, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v43, v43);
          // pto: %9
          uint64_t v190 = (uint64_t) v51;
          TASSIGN(v189, v190);
          pipe_barrier(PIPE_V);
          TCOLEXPANDADD(v189, v187, v182);
          // pto: %10
          Tile<TileType::Vec, float, 32, 128, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v191 = Tile<TileType::Vec, float, 32, 128, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v43, v43);
          // pto: %10
          uint64_t v192 = (uint64_t) v50;
          TASSIGN(v191, v192);
          // pto: %11
          Tile<TileType::Vec, float, 32, 1, BLayout::ColMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v193 = Tile<TileType::Vec, float, 32, 1, BLayout::ColMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v43, v43);
          // pto: %11
          uint64_t v194 = (uint64_t) v49;
          TASSIGN(v193, v194);
          pipe_barrier(PIPE_V);
          TROWMAX(v193, v189, v191);
          // pto: %12
          Tile<TileType::Vec, float, 32, 128, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v195 = Tile<TileType::Vec, float, 32, 128, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v43, v43);
          // pto: %12
          uint64_t v196 = (uint64_t) v51;
          TASSIGN(v195, v196);
          pipe_barrier(PIPE_V);
          TROWEXPANDSUB(v195, v189, v193);
          // pto: %13
          Tile<TileType::Vec, float, 32, 128, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v197 = Tile<TileType::Vec, float, 32, 128, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v43, v43);
          // pto: %13
          uint64_t v198 = (uint64_t) v51;
          TASSIGN(v197, v198);
          pipe_barrier(PIPE_V);
          TEXP(v197, v195);
          // pto: %14
          Tile<TileType::Vec, float, 32, 128, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v199 = Tile<TileType::Vec, float, 32, 128, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v43, v43);
          // pto: %14
          uint64_t v200 = (uint64_t) v50;
          TASSIGN(v199, v200);
          // pto: %15
          Tile<TileType::Vec, float, 32, 1, BLayout::ColMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v201 = Tile<TileType::Vec, float, 32, 1, BLayout::ColMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v43, v43);
          // pto: %15
          uint64_t v202 = (uint64_t) v49;
          TASSIGN(v201, v202);
          pipe_barrier(PIPE_V);
          TROWSUM(v201, v197, v199);
          // pto: %16
          Tile<TileType::Vec, bfloat16_t, 32, 128, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v203 = Tile<TileType::Vec, bfloat16_t, 32, 128, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v43, v43);
          // pto: %16
          uint64_t v204 = (uint64_t) v51;
          TASSIGN(v203, v204);
          pipe_barrier(PIPE_V);
          TCVT(v203, v197, v28, v27);
          set_flag(PIPE_V, PIPE_MTE3, EVENT_ID3);
          wait_flag(PIPE_V, PIPE_MTE3, EVENT_ID3);
          TPUSH<TPipe<0, Direction::DIR_BOTH, 16384, 2, 2, true>, Tile<TileType::Vec, bfloat16_t, 32, 128, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>, TileSplitAxis::TILE_NO_SPLIT>(v67, v203);
          set_flag(PIPE_MTE3, PIPE_V, EVENT_ID7);
          // pto: %17
          Tile<TileType::Vec, float, 16, 1, BLayout::ColMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v205 = Tile<TileType::Vec, float, 16, 1, BLayout::ColMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v43, v43);
          // pto: %17
          uint64_t v206 = (uint64_t) v51;
          TASSIGN(v205, v206);
          // pto: %18
          Tile<TileType::Vec, float, 16, 1, BLayout::ColMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v207 = Tile<TileType::Vec, float, 16, 1, BLayout::ColMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v43, v43);
          // pto: %18
          uint64_t v208 = (uint64_t) v51;
          TASSIGN(v207, v208);
          // pto: %19
          Tile<TileType::Vec, float, 16, 1, BLayout::ColMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v209 = Tile<TileType::Vec, float, 16, 1, BLayout::ColMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v43, v43);
          // pto: %19
          uint64_t v210 = (uint64_t) v51;
          TASSIGN(v209, v210);
          // pto: %20
          Tile<TileType::Vec, float, 16, 1, BLayout::ColMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v211 = Tile<TileType::Vec, float, 16, 1, BLayout::ColMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v43, v43);
          // pto: %20
          uint64_t v212 = (uint64_t) v51;
          TASSIGN(v211, v212);
        }
      } else {
        // pto: %21
        Tile<TileType::Vec, float, 16, 512, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v213 = Tile<TileType::Vec, float, 16, 512, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v43, v43);
        // pto: %21
        uint64_t v214 = (uint64_t) v51;
        TASSIGN(v213, v214);
        pipe_barrier(PIPE_V);
        TEXPANDS(v213, v34);
        for (int64_t j215 = v43; j215 < v33; j215 += v47) {
          // pto: %22
          Tile<TileType::Vec, float, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v216 = Tile<TileType::Vec, float, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v43, v43);
          // pto: %22
          uint64_t v217 = (uint64_t) v51;
          TASSIGN(v216, v217);
          pipe_barrier(PIPE_V);
          TEXPANDS(v216, v32);
          // pto: %23
          Tile<TileType::Vec, float, 16, 1, BLayout::ColMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v218 = Tile<TileType::Vec, float, 16, 1, BLayout::ColMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v43, v43);
          // pto: %23
          uint64_t v219 = (uint64_t) v51;
          TASSIGN(v218, v219);
          // pto: %24
          Tile<TileType::Vec, float, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v220 = Tile<TileType::Vec, float, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v43, v43);
          // pto: %24
          uint64_t v221 = (uint64_t) v51;
          TASSIGN(v220, v221);
          pipe_barrier(PIPE_V);
          TEXPANDS(v220, v34);
          // pto: %25
          Tile<TileType::Vec, float, 16, 1, BLayout::ColMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v222 = Tile<TileType::Vec, float, 16, 1, BLayout::ColMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v43, v43);
          // pto: %25
          uint64_t v223 = (uint64_t) v51;
          TASSIGN(v222, v223);
        }
      }
      set_flag(PIPE_MTE3, PIPE_V, EVENT_ID6);
    }
  }
  wait_flag(PIPE_V, PIPE_MTE2, EVENT_ID0);
  wait_flag(PIPE_MTE3, PIPE_V, EVENT_ID0);
  wait_flag(PIPE_V, PIPE_MTE2, EVENT_ID1);
  wait_flag(PIPE_MTE3, PIPE_V, EVENT_ID1);
  wait_flag(PIPE_MTE3, PIPE_V, EVENT_ID2);
  wait_flag(PIPE_MTE3, PIPE_V, EVENT_ID3);
  wait_flag(PIPE_MTE3, PIPE_V, EVENT_ID4);
  wait_flag(PIPE_MTE3, PIPE_V, EVENT_ID6);
  wait_flag(PIPE_V, PIPE_MTE2, EVENT_ID2);
  wait_flag(PIPE_MTE3, PIPE_V, EVENT_ID7);
  #endif // __DAV_VEC__

  ptoas_auto_sync_tail(PTOAutoSyncTailMode::kBarrierAll);
  return;
}
// --- Kernel entry point ---
extern "C" __aicore__ __attribute__((always_inline)) void kernel_entry(__gm__ int64_t* args)
{
#if !defined(__CPU_SIM) && !defined(__COSTMODEL)
    // Reset AI Core atomic mode inherited from a prior kernel.
    set_atomic_none();
#endif

    // Read logical SPMD block identity from runtime dispatch payload
    int32_t __pypto_spmd_block_idx = get_block_idx(args);
    int32_t __pypto_spmd_block_num = get_block_num(args);

    // Unpack tensor: sparse_blk_li_inline2405__ssa_v0
    __gm__ Tensor* sparse_blk_li_inline2405__ssa_v0_tensor = reinterpret_cast<__gm__ Tensor*>(args[0]);
    __gm__ float* sparse_blk_li_inline2405__ssa_v0 = reinterpret_cast<__gm__ float*>(sparse_blk_li_inline2405__ssa_v0_tensor->buffer.addr) + sparse_blk_li_inline2405__ssa_v0_tensor->start_offset;

    // Unpack tensor: sparse_blk_mi_inline2404__ssa_v0
    __gm__ Tensor* sparse_blk_mi_inline2404__ssa_v0_tensor = reinterpret_cast<__gm__ Tensor*>(args[1]);
    __gm__ float* sparse_blk_mi_inline2404__ssa_v0 = reinterpret_cast<__gm__ float*>(sparse_blk_mi_inline2404__ssa_v0_tensor->buffer.addr) + sparse_blk_mi_inline2404__ssa_v0_tensor->start_offset;

    // Unpack tensor: sparse_blk_oi_inline2398__ssa_v0
    __gm__ Tensor* sparse_blk_oi_inline2398__ssa_v0_tensor = reinterpret_cast<__gm__ Tensor*>(args[2]);
    __gm__ float* sparse_blk_oi_inline2398__ssa_v0 = reinterpret_cast<__gm__ float*>(sparse_blk_oi_inline2398__ssa_v0_tensor->buffer.addr) + sparse_blk_oi_inline2398__ssa_v0_tensor->start_offset;

    // Unpack tensor: qk_order_inline2351__ssa_v0
    __gm__ Tensor* qk_order_inline2351__ssa_v0_tensor = reinterpret_cast<__gm__ Tensor*>(args[3]);
    __gm__ int32_t* qk_order_inline2351__ssa_v0 = reinterpret_cast<__gm__ int32_t*>(qk_order_inline2351__ssa_v0_tensor->buffer.addr) + qk_order_inline2351__ssa_v0_tensor->start_offset;

    // Unpack tensor: sparse_bias_inline2381__rv_v2
    __gm__ Tensor* sparse_bias_inline2381__rv_v2_tensor = reinterpret_cast<__gm__ Tensor*>(args[4]);
    __gm__ float* sparse_bias_inline2381__rv_v2 = reinterpret_cast<__gm__ float*>(sparse_bias_inline2381__rv_v2_tensor->buffer.addr) + sparse_bias_inline2381__rv_v2_tensor->start_offset;

    // Unpack tensor: valid_block_mask_inline2385__ssa_v0
    __gm__ Tensor* valid_block_mask_inline2385__ssa_v0_tensor = reinterpret_cast<__gm__ Tensor*>(args[5]);
    __gm__ int32_t* valid_block_mask_inline2385__ssa_v0 = reinterpret_cast<__gm__ int32_t*>(valid_block_mask_inline2385__ssa_v0_tensor->buffer.addr) + valid_block_mask_inline2385__ssa_v0_tensor->start_offset;

    // Unpack tensor: position_ids_t1_inline1288__ssa_v0
    __gm__ Tensor* position_ids_t1_inline1288__ssa_v0_tensor = reinterpret_cast<__gm__ Tensor*>(args[6]);
    __gm__ int32_t* position_ids_t1_inline1288__ssa_v0 = reinterpret_cast<__gm__ int32_t*>(position_ids_t1_inline1288__ssa_v0_tensor->buffer.addr) + position_ids_t1_inline1288__ssa_v0_tensor->start_offset;

    // Unpack tensor: window_swa_indices__ssa_v0
    __gm__ Tensor* window_swa_indices__ssa_v0_tensor = reinterpret_cast<__gm__ Tensor*>(args[7]);
    __gm__ int32_t* window_swa_indices__ssa_v0 = reinterpret_cast<__gm__ int32_t*>(window_swa_indices__ssa_v0_tensor->buffer.addr) + window_swa_indices__ssa_v0_tensor->start_offset;

    // Unpack tensor: ori_kv_flat_inline2344__ssa_v1
    __gm__ Tensor* ori_kv_flat_inline2344__ssa_v1_tensor = reinterpret_cast<__gm__ Tensor*>(args[8]);
    __gm__ bfloat16_t* ori_kv_flat_inline2344__ssa_v1 = reinterpret_cast<__gm__ bfloat16_t*>(ori_kv_flat_inline2344__ssa_v1_tensor->buffer.addr) + ori_kv_flat_inline2344__ssa_v1_tensor->start_offset;

    // Unpack tensor: cmp_sparse_indices_inline2383__rv_v2
    __gm__ Tensor* cmp_sparse_indices_inline2383__rv_v2_tensor = reinterpret_cast<__gm__ Tensor*>(args[9]);
    __gm__ int32_t* cmp_sparse_indices_inline2383__rv_v2 = reinterpret_cast<__gm__ int32_t*>(cmp_sparse_indices_inline2383__rv_v2_tensor->buffer.addr) + cmp_sparse_indices_inline2383__rv_v2_tensor->start_offset;

    // Unpack tensor: cmp_block_table__ssa_v0
    __gm__ Tensor* cmp_block_table__ssa_v0_tensor = reinterpret_cast<__gm__ Tensor*>(args[10]);
    __gm__ int32_t* cmp_block_table__ssa_v0 = reinterpret_cast<__gm__ int32_t*>(cmp_block_table__ssa_v0_tensor->buffer.addr) + cmp_block_table__ssa_v0_tensor->start_offset;

    // Unpack tensor: cmp_kv_flat_inline2401__ssa_v0
    __gm__ Tensor* cmp_kv_flat_inline2401__ssa_v0_tensor = reinterpret_cast<__gm__ Tensor*>(args[11]);
    __gm__ bfloat16_t* cmp_kv_flat_inline2401__ssa_v0 = reinterpret_cast<__gm__ bfloat16_t*>(cmp_kv_flat_inline2401__ssa_v0_tensor->buffer.addr) + cmp_kv_flat_inline2401__ssa_v0_tensor->start_offset;

    // Unpack tensor: q_flat_inline2355__ssa_v0
    __gm__ Tensor* q_flat_inline2355__ssa_v0_tensor = reinterpret_cast<__gm__ Tensor*>(args[12]);
    __gm__ bfloat16_t* q_flat_inline2355__ssa_v0 = reinterpret_cast<__gm__ bfloat16_t*>(q_flat_inline2355__ssa_v0_tensor->buffer.addr) + q_flat_inline2355__ssa_v0_tensor->start_offset;

    // Unpack tensor: __gm_pipe_buffer
    __gm__ Tensor* __gm_pipe_buffer_tensor = reinterpret_cast<__gm__ Tensor*>(args[13]);
    // SPMD: shard GM pipe workspace by logical block_idx to avoid overlap.
    int64_t __pypto_gm_block_num = static_cast<int64_t>(__pypto_spmd_block_num);
    if (__pypto_gm_block_num <= 0) __pypto_gm_block_num = 1;
    int64_t __pypto_gm_total_elems = static_cast<int64_t>(__gm_pipe_buffer_tensor->shapes[0]);
    int64_t __pypto_gm_elems_per_block = __pypto_gm_total_elems / __pypto_gm_block_num;
    int64_t __pypto_gm_block_offset = static_cast<int64_t>(__pypto_spmd_block_idx) * __pypto_gm_elems_per_block;
    __gm__ float* __gm_pipe_buffer = reinterpret_cast<__gm__ float*>(__gm_pipe_buffer_tensor->buffer.addr) + __gm_pipe_buffer_tensor->start_offset + __pypto_gm_block_offset;

    // Unpack scalar: qk_items_inline2347__ssa_v0
    union { uint64_t u64; int64_t val; } qk_items_inline2347__ssa_v0_conv;
    qk_items_inline2347__ssa_v0_conv.u64 = args[14];
    int64_t qk_items_inline2347__ssa_v0 = qk_items_inline2347__ssa_v0_conv.val;

    // Extract dynamic dim: t_blk_inline2373__ssa_v0
    int64_t t_blk_inline2373__ssa_v0 = static_cast<int64_t>(sparse_blk_li_inline2405__ssa_v0_tensor->shapes[0]);

    // Extract dynamic dim: t_dim_inline2369__ssa_v0
    int64_t t_dim_inline2369__ssa_v0 = static_cast<int64_t>(sparse_bias_inline2381__rv_v2_tensor->shapes[0]);

    // Extract dynamic dim: t_dim_inline1251__ssa_v0
    int64_t t_dim_inline1251__ssa_v0 = static_cast<int64_t>(position_ids_t1_inline1288__ssa_v0_tensor->shapes[0]);

    // Extract dynamic dim: T_DYN
    int64_t T_DYN = static_cast<int64_t>(window_swa_indices__ssa_v0_tensor->shapes[0]);

    // Extract dynamic dim: ori_block_num_inline2362__ssa_v0
    int64_t ori_block_num_inline2362__ssa_v0 = (static_cast<int64_t>(ori_kv_flat_inline2344__ssa_v1_tensor->shapes[0]) / 32);

    // Extract dynamic dim: B_DYN
    int64_t B_DYN = static_cast<int64_t>(cmp_block_table__ssa_v0_tensor->shapes[0]);

    // Extract dynamic dim: cmp_block_num_inline2376__ssa_v0
    int64_t cmp_block_num_inline2376__ssa_v0 = (static_cast<int64_t>(cmp_kv_flat_inline2401__ssa_v0_tensor->shapes[0]) / 32);

    // Extract dynamic dim: t_heads_inline2364__ssa_v0
    int64_t t_heads_inline2364__ssa_v0 = static_cast<int64_t>(q_flat_inline2355__ssa_v0_tensor->shapes[0]);

    // Forward to ptoas-generated function
    qk_pv_aic(sparse_blk_li_inline2405__ssa_v0, sparse_blk_mi_inline2404__ssa_v0, sparse_blk_oi_inline2398__ssa_v0, qk_order_inline2351__ssa_v0, sparse_bias_inline2381__rv_v2, valid_block_mask_inline2385__ssa_v0, position_ids_t1_inline1288__ssa_v0, window_swa_indices__ssa_v0, ori_kv_flat_inline2344__ssa_v1, cmp_sparse_indices_inline2383__rv_v2, cmp_block_table__ssa_v0, cmp_kv_flat_inline2401__ssa_v0, q_flat_inline2355__ssa_v0, __gm_pipe_buffer, qk_items_inline2347__ssa_v0, t_blk_inline2373__ssa_v0, t_dim_inline2369__ssa_v0, t_dim_inline1251__ssa_v0, T_DYN, ori_block_num_inline2362__ssa_v0, B_DYN, cmp_block_num_inline2376__ssa_v0, t_heads_inline2364__ssa_v0, __pypto_spmd_block_idx, __pypto_spmd_block_num);
}
