const $=(s,r=document)=>r.querySelector(s);const $$=(s,r=document)=>[...r.querySelectorAll(s)];let toastTimer;
const detail={correctness:{title:'正确性门禁',body:`<div class="drawer-card"><h3>当前状态</h3><dl class="drawer-list"><dt>状态</dt><dd>未验证</dd><dt>原因</dt><dd>缺少 Golden / Oracle</dd><dt>可用输入</dt><dd>debug/run.py · inline random</dd><dt>建议</dt><dd>先固定输入，再生成 Tensor diff</dd></dl></div><div class="drawer-card"><h3>为什么重要</h3><p class="muted-copy">没有正确性证据，这次 Run 只能用于调试现场，不能作为性能 Baseline。</p></div><button class="button primary full" data-action="run-check">运行对拍并进入异常分析</button>`},memory:{title:'内存分配报告',body:`<div class="drawer-card"><h3>down_proj · Right space</h3><dl class="drawer-list"><dt>Used</dt><dd>64.0 KB</dd><dt>Limit</dt><dd>64.0 KB</dd><dt>Usage</dt><dd class="warn-text">100.0%</dd><dt>MemRefs</dt><dd>2</dd><dt>Live range</dt><dd>[12, 70]</dd></dl></div><div class="drawer-card"><h3>关联产物</h3><div class="drawer-code">report/memory_after_AllocateMemoryAddr.txt<br/>kernels/aic/down_proj.cpp<br/><span class="bad">risk: no headroom for tile expansion</span></div></div>`},artifact:{title:'产物索引',body:`<div class="drawer-card"><h3>206 项有效产物</h3><dl class="drawer-list"><dt>passes_dump</dt><dd>42 files · 13.2 MB</dd><dt>ptoas</dt><dd>76 files · 4.8 MB</dd><dt>kernels</dt><dd>78 files · 9.1 MB</dd><dt>dfx_outputs</dt><dd>12 files · 10.4 MB</dd><dt>report</dt><dd>16 hints · 2 reports</dd></dl></div><button class="button secondary full" data-action="copy">复制 Manifest 路径</button>`}};
function toast(message){const el=$('#toast');el.textContent=message;el.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('show'),2600)}
function openDrawer(kind){const d=detail[kind]||detail.correctness;$('#drawer-title').textContent=d.title;$('#drawer-body').innerHTML=d.body;$('#drawer').classList.add('open');$('#drawer').setAttribute('aria-hidden','false')}
function closeDrawer(){$('#drawer').classList.remove('open');$('#drawer').setAttribute('aria-hidden','true')}
function runCheck(){const gate=$('#correctness-gate');gate.classList.remove('pending');gate.classList.add('warn');gate.querySelector('span').textContent='!';$('#correctness-label').textContent='发现偏差';gate.querySelector('em').textContent='Task 142';$('#status-title').textContent='发现 1 处首个偏差';$('#status-copy').textContent='Tensor diff 已生成，可进入异常分析定位 Task 与 Kernel。';$$('[data-action="correctness"]').forEach(b=>b.textContent='进入异常分析');toast('正确性对拍完成：发现首个偏差');}
document.addEventListener('click',e=>{const scroll=e.target.closest('[data-scroll]');if(scroll){e.preventDefault();const el=$('#'+scroll.dataset.scroll);if(el)el.scrollIntoView({behavior:'smooth',block:'start'});$$('.side-link').forEach(x=>x.classList.toggle('active',x===scroll));return}const act=e.target.closest('[data-action]');if(!act)return;const type=act.dataset.action;if(type==='correctness'||type==='run-check'){if(type==='correctness'&&$('#correctness-label').textContent==='发现偏差'){toast('请从异常分析继续查看 Tensor、Task 和 Kernel');}else runCheck();if(type==='run-check')closeDrawer();return}if(type==='debug'){toast('已打开异常分析上下文（Demo）');return}if(type==='compare'){toast('已准备 Baseline / Candidate 对比上下文（Demo）');return}if(type==='reproduce'){toast('复现命令已复制：seed 13371337 · Ascend 910B');return}if(type==='export'){toast('报告已准备导出（Demo）');return}if(type==='manifest'){openDrawer('artifact');return}if(type==='artifact'){openDrawer('artifact');return}if(type==='memory'){openDrawer('memory');return}if(type==='copy'){toast('已复制到剪贴板（Demo）');return}if(type==='close'){closeDrawer();return}if(type==='task-filter'){toast('已展开全部 Task trace（Demo）');return}});
$('#drawer').addEventListener('click',e=>{if(e.target.id==='drawer')closeDrawer()});
document.querySelector('[data-scroll="memory"]')?.addEventListener('click',()=>openDrawer('memory'));
